/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[7],{444:function(Aa,ua,r){r.r(ua);var pa=r(1),ka=r(471),ma=r(472),ha;(function(da){da[da.EXTERNAL_XFDF_NOT_REQUESTED=0]="EXTERNAL_XFDF_NOT_REQUESTED";da[da.EXTERNAL_XFDF_NOT_AVAILABLE=1]="EXTERNAL_XFDF_NOT_AVAILABLE";da[da.EXTERNAL_XFDF_AVAILABLE=2]="EXTERNAL_XFDF_AVAILABLE"})(ha||(ha={}));Aa=function(){function da(aa){this.aa=aa;this.state=ha.EXTERNAL_XFDF_NOT_REQUESTED}da.prototype.kca=function(){var aa=this;return function(x,
y,h){return Object(pa.b)(aa,void 0,void 0,function(){var e,b,a,f,n,z,w,ea=this,ja;return Object(pa.d)(this,function(ca){switch(ca.label){case 0:if(this.state!==ha.EXTERNAL_XFDF_NOT_REQUESTED)return[3,2];e=this.aa.getDocument().rs();return[4,this.zaa(e)];case 1:b=ca.ea(),a=this.y6(b),this.hI=null!==(ja=null===a||void 0===a?void 0:a.parse())&&void 0!==ja?ja:null,this.state=null===this.hI?ha.EXTERNAL_XFDF_NOT_AVAILABLE:ha.EXTERNAL_XFDF_AVAILABLE,ca.label=2;case 2:if(this.state===ha.EXTERNAL_XFDF_NOT_AVAILABLE)return h(x),
[2];f=new DOMParser;n=f.parseFromString(x,"text/xml");y.forEach(function(ba){ea.merge(n,ea.hI,ba-1)});z=new XMLSerializer;w=z.serializeToString(n);h(w);return[2]}})})}};da.prototype.ZL=function(aa){this.zaa=aa};da.prototype.oe=function(){this.hI=void 0;this.state=ha.EXTERNAL_XFDF_NOT_REQUESTED};da.prototype.y6=function(aa){return aa?Array.isArray(aa)?new ka.a(aa):"string"!==typeof aa?null:(new DOMParser).parseFromString(aa,"text/xml").querySelector("xfdf > add")?new ka.a(aa):new ma.a(aa):null};da.prototype.merge=
function(aa,x,y){var h=this;0===y&&(this.Cea(aa,x.hp),this.Eea(aa,x.PH));var e=x.ca[y];e&&(this.Fea(aa,e.an),this.Hea(aa,e.OZ,x.Yv),this.Gea(aa,e.page,y),this.Dea(aa,e.LR));e=this.aa.Jb();if(y===e-1){var b=x.Yv;Object.keys(b).forEach(function(a){b[a].wJ||h.yV(aa,a,b[a])})}};da.prototype.Cea=function(aa,x){null!==x&&(aa=this.lv(aa),this.xq(aa,"calculation-order",x))};da.prototype.Eea=function(aa,x){null!==x&&(aa=this.lv(aa),this.xq(aa,"document-actions",x))};da.prototype.Fea=function(aa,x){var y=this,
h=this.kv(aa.querySelector("xfdf"),"annots");Object.keys(x).forEach(function(e){y.xq(h,'[name="'+e+'"]',x[e])})};da.prototype.Hea=function(aa,x,y){var h=this;if(0!==x.length){var e=this.lv(aa);x.forEach(function(b){var a=b.getAttribute("field"),f=y[a];f&&(h.yV(aa,a,f),h.xq(e,"null",b))})}};da.prototype.yV=function(aa,x,y){var h=this.lv(aa);null!==y.PB&&this.xq(h,'ffield [name="'+x+'"]',y.PB);aa=this.kv(aa.querySelector("xfdf"),"fields");x=x.split(".");this.iL(aa,x,0,y.value);y.wJ=!0};da.prototype.Gea=
function(aa,x,y){null!==x&&(aa=this.lv(aa),aa=this.kv(aa,"pages"),this.xq(aa,'[number="'+(y+1)+'"]',x))};da.prototype.Dea=function(aa,x){Object.keys(x).forEach(function(y){(y=aa.querySelector('annots [name="'+y+'"]'))&&y.parentElement.removeChild(y)})};da.prototype.iL=function(aa,x,y,h){if(y===x.length)x=document.createElementNS("","value"),x.textContent=h,this.xq(aa,"value",x);else{var e=x[y];this.kv(aa,'[name="'+e+'"]',"field").setAttribute("name",e);aa=aa.querySelectorAll('[name="'+e+'"]');1===
aa.length?this.iL(aa[0],x,y+1,h):(e=this.m$(aa),this.iL(y===x.length-1?e:this.vla(aa,e),x,y+1,h))}};da.prototype.m$=function(aa){for(var x=null,y=0;y<aa.length;y++){var h=aa[y];if(0===h.childElementCount||1===h.childElementCount&&"value"===h.children[0].tagName){x=h;break}}return x};da.prototype.vla=function(aa,x){for(var y=0;y<aa.length;y++)if(aa[y]!==x)return aa[y];return null};da.prototype.xq=function(aa,x,y){x=aa.querySelector(x);null!==x&&aa.removeChild(x);aa.appendChild(y)};da.prototype.lv=
function(aa){var x=aa.querySelector("pdf-info");if(null!==x)return x;x=this.kv(aa.querySelector("xfdf"),"pdf-info");x.setAttribute("xmlns","http://www.pdftron.com/pdfinfo");x.setAttribute("version","2");x.setAttribute("import-version","4");return x};da.prototype.kv=function(aa,x,y){var h=aa.querySelector(x);if(null!==h)return h;h=document.createElementNS("",y||x);aa.appendChild(h);return h};return da}();ua["default"]=Aa},456:function(Aa,ua){Aa=function(){function r(){}r.prototype.qA=function(pa){var ka=
{hp:null,PH:null,Yv:{},ca:{}};pa=(new DOMParser).parseFromString(pa,"text/xml");ka.hp=pa.querySelector("pdf-info calculation-order");ka.PH=pa.querySelector("pdf-info document-actions");ka.Yv=this.Afa(pa);ka.ca=this.Mfa(pa);return ka};r.prototype.Afa=function(pa){var ka=pa.querySelector("fields");pa=pa.querySelectorAll("pdf-info > ffield");if(null===ka&&null===pa)return{};var ma={};this.V3(ma,ka);this.T3(ma,pa);return ma};r.prototype.V3=function(pa,ka){if(null!==ka&&ka.children){for(var ma=[],ha=0;ha<
ka.children.length;ha++){var da=ka.children[ha];ma.push({name:da.getAttribute("name"),element:da})}for(;0!==ma.length;)for(ka=ma.shift(),ha=0;ha<ka.element.children.length;ha++)da=ka.element.children[ha],"value"===da.tagName?pa[ka.name]={value:da.textContent,PB:null,wJ:!1}:da.children&&ma.push({name:ka.name+"."+da.getAttribute("name"),element:da})}};r.prototype.T3=function(pa,ka){ka.forEach(function(ma){var ha=ma.getAttribute("name");pa[ha]?pa[ha].PB=ma:pa[ha]={value:null,PB:ma,wJ:!1}})};r.prototype.Mfa=
function(pa){var ka=this,ma={};pa.querySelectorAll("pdf-info widget").forEach(function(ha){var da=parseInt(ha.getAttribute("page"),10)-1;ka.PC(ma,da);ma[da].OZ.push(ha)});pa.querySelectorAll("pdf-info page").forEach(function(ha){var da=parseInt(ha.getAttribute("number"),10)-1;ka.PC(ma,da);ma[da].page=ha});this.nT(pa).forEach(function(ha){var da=parseInt(ha.getAttribute("page"),10),aa=ha.getAttribute("name");ka.PC(ma,da);ma[da].an[aa]=ha});this.$S(pa).forEach(function(ha){var da=parseInt(ha.getAttribute("page"),
10);ha=ha.textContent;ka.PC(ma,da);ma[da].LR[ha]=!0});return ma};r.prototype.PC=function(pa,ka){pa[ka]||(pa[ka]={an:{},LR:{},OZ:[],page:null})};return r}();ua.a=Aa},471:function(Aa,ua,r){var pa=r(1),ka=r(0);r.n(ka);Aa=function(ma){function ha(da){var aa=ma.call(this)||this;aa.Y9=Array.isArray(da)?da:[da];return aa}Object(pa.c)(ha,ma);ha.prototype.parse=function(){var da=this,aa={hp:null,PH:null,Yv:{},ca:{}};this.Y9.forEach(function(x){aa=Object(ka.merge)(aa,da.qA(x))});return aa};ha.prototype.nT=
function(da){var aa=[];da.querySelectorAll("add > *").forEach(function(x){aa.push(x)});da.querySelectorAll("modify > *").forEach(function(x){aa.push(x)});return aa};ha.prototype.$S=function(da){return da.querySelectorAll("delete > *")};return ha}(r(456).a);ua.a=Aa},472:function(Aa,ua,r){var pa=r(1);Aa=function(ka){function ma(ha){var da=ka.call(this)||this;da.Z9=ha;return da}Object(pa.c)(ma,ka);ma.prototype.parse=function(){return this.qA(this.Z9)};ma.prototype.nT=function(ha){return ha.querySelectorAll("annots > *")};
ma.prototype.$S=function(){return[]};return ma}(r(456).a);ua.a=Aa}}]);}).call(this || window)
