/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
<<<<<<< HEAD
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[7],{447:function(Ba,ua,r){r.r(ua);var pa=r(1),ka=r(474),ma=r(475),fa;(function(da){da[da.EXTERNAL_XFDF_NOT_REQUESTED=0]="EXTERNAL_XFDF_NOT_REQUESTED";da[da.EXTERNAL_XFDF_NOT_AVAILABLE=1]="EXTERNAL_XFDF_NOT_AVAILABLE";da[da.EXTERNAL_XFDF_AVAILABLE=2]="EXTERNAL_XFDF_AVAILABLE"})(fa||(fa={}));Ba=function(){function da(z){this.aa=z;this.state=fa.EXTERNAL_XFDF_NOT_REQUESTED}da.prototype.Xca=function(){var z=this;return function(x,y,f){return Object(pa.b)(z,
void 0,void 0,function(){var e,b,a,h,n,aa,w,ea=this,ja;return Object(pa.d)(this,function(ba){switch(ba.label){case 0:if(this.state!==fa.EXTERNAL_XFDF_NOT_REQUESTED)return[3,2];e=this.aa.getDocument().As();return[4,this.kba(e)];case 1:b=ba.ea(),a=this.j7(b),this.xI=null!==(ja=null===a||void 0===a?void 0:a.parse())&&void 0!==ja?ja:null,this.state=null===this.xI?fa.EXTERNAL_XFDF_NOT_AVAILABLE:fa.EXTERNAL_XFDF_AVAILABLE,ba.label=2;case 2:if(this.state===fa.EXTERNAL_XFDF_NOT_AVAILABLE)return f(x),[2];
h=new DOMParser;n=h.parseFromString(x,"text/xml");y.forEach(function(ca){ea.merge(n,ea.xI,ca-1)});aa=new XMLSerializer;w=aa.serializeToString(n);f(w);return[2]}})})}};da.prototype.qM=function(z){this.kba=z};da.prototype.qe=function(){this.xI=void 0;this.state=fa.EXTERNAL_XFDF_NOT_REQUESTED};da.prototype.j7=function(z){return z?Array.isArray(z)?new ka.a(z):"string"!==typeof z?null:(new DOMParser).parseFromString(z,"text/xml").querySelector("xfdf > add")?new ka.a(z):new ma.a(z):null};da.prototype.merge=
function(z,x,y){var f=this;0===y&&(this.pfa(z,x.rp),this.rfa(z,x.eI));var e=x.ca[y];e&&(this.sfa(z,e.sn),this.ufa(z,e.v_,x.hw),this.tfa(z,e.page,y),this.qfa(z,e.fS));e=this.aa.Lb();if(y===e-1){var b=x.hw;Object.keys(b).forEach(function(a){b[a].OJ||f.XV(z,a,b[a])})}};da.prototype.pfa=function(z,x){null!==x&&(z=this.vv(z),this.Hq(z,"calculation-order",x))};da.prototype.rfa=function(z,x){null!==x&&(z=this.vv(z),this.Hq(z,"document-actions",x))};da.prototype.sfa=function(z,x){var y=this,f=this.uv(z.querySelector("xfdf"),
"annots");Object.keys(x).forEach(function(e){y.Hq(f,'[name="'+e+'"]',x[e])})};da.prototype.ufa=function(z,x,y){var f=this;if(0!==x.length){var e=this.vv(z);x.forEach(function(b){var a=b.getAttribute("field"),h=y[a];h&&(f.XV(z,a,h),f.Hq(e,"null",b))})}};da.prototype.XV=function(z,x,y){var f=this.vv(z);null!==y.$B&&this.Hq(f,'ffield [name="'+x+'"]',y.$B);z=this.uv(z.querySelector("xfdf"),"fields");x=x.split(".");this.AL(z,x,0,y.value);y.OJ=!0};da.prototype.tfa=function(z,x,y){null!==x&&(z=this.vv(z),
z=this.uv(z,"pages"),this.Hq(z,'[number="'+(y+1)+'"]',x))};da.prototype.qfa=function(z,x){Object.keys(x).forEach(function(y){(y=z.querySelector('annots [name="'+y+'"]'))&&y.parentElement.removeChild(y)})};da.prototype.AL=function(z,x,y,f){if(y===x.length)x=document.createElementNS("","value"),x.textContent=f,this.Hq(z,"value",x);else{var e=x[y];this.uv(z,'[name="'+e+'"]',"field").setAttribute("name",e);z=z.querySelectorAll('[name="'+e+'"]');1===z.length?this.AL(z[0],x,y+1,f):(e=this.X$(z),this.AL(y===
x.length-1?e:this.gma(z,e),x,y+1,f))}};da.prototype.X$=function(z){for(var x=null,y=0;y<z.length;y++){var f=z[y];if(0===f.childElementCount||1===f.childElementCount&&"value"===f.children[0].tagName){x=f;break}}return x};da.prototype.gma=function(z,x){for(var y=0;y<z.length;y++)if(z[y]!==x)return z[y];return null};da.prototype.Hq=function(z,x,y){x=z.querySelector(x);null!==x&&z.removeChild(x);z.appendChild(y)};da.prototype.vv=function(z){var x=z.querySelector("pdf-info");if(null!==x)return x;x=this.uv(z.querySelector("xfdf"),
"pdf-info");x.setAttribute("xmlns","http://www.pdftron.com/pdfinfo");x.setAttribute("version","2");x.setAttribute("import-version","4");return x};da.prototype.uv=function(z,x,y){var f=z.querySelector(x);if(null!==f)return f;f=document.createElementNS("",y||x);z.appendChild(f);return f};return da}();ua["default"]=Ba},459:function(Ba,ua){Ba=function(){function r(){}r.prototype.BA=function(pa){var ka={rp:null,eI:null,hw:{},ca:{}};pa=(new DOMParser).parseFromString(pa,"text/xml");ka.rp=pa.querySelector("pdf-info calculation-order");
ka.eI=pa.querySelector("pdf-info document-actions");ka.hw=this.mga(pa);ka.ca=this.yga(pa);return ka};r.prototype.mga=function(pa){var ka=pa.querySelector("fields");pa=pa.querySelectorAll("pdf-info > ffield");if(null===ka&&null===pa)return{};var ma={};this.J4(ma,ka);this.H4(ma,pa);return ma};r.prototype.J4=function(pa,ka){if(null!==ka&&ka.children){for(var ma=[],fa=0;fa<ka.children.length;fa++){var da=ka.children[fa];ma.push({name:da.getAttribute("name"),element:da})}for(;0!==ma.length;)for(ka=ma.shift(),
fa=0;fa<ka.element.children.length;fa++)da=ka.element.children[fa],"value"===da.tagName?pa[ka.name]={value:da.textContent,$B:null,OJ:!1}:da.children&&ma.push({name:ka.name+"."+da.getAttribute("name"),element:da})}};r.prototype.H4=function(pa,ka){ka.forEach(function(ma){var fa=ma.getAttribute("name");pa[fa]?pa[fa].$B=ma:pa[fa]={value:null,$B:ma,OJ:!1}})};r.prototype.yga=function(pa){var ka=this,ma={};pa.querySelectorAll("pdf-info widget").forEach(function(fa){var da=parseInt(fa.getAttribute("page"),
10)-1;ka.aD(ma,da);ma[da].v_.push(fa)});pa.querySelectorAll("pdf-info page").forEach(function(fa){var da=parseInt(fa.getAttribute("number"),10)-1;ka.aD(ma,da);ma[da].page=fa});this.MT(pa).forEach(function(fa){var da=parseInt(fa.getAttribute("page"),10),z=fa.getAttribute("name");ka.aD(ma,da);ma[da].sn[z]=fa});this.vT(pa).forEach(function(fa){var da=parseInt(fa.getAttribute("page"),10);fa=fa.textContent;ka.aD(ma,da);ma[da].fS[fa]=!0});return ma};r.prototype.aD=function(pa,ka){pa[ka]||(pa[ka]={sn:{},
fS:{},v_:[],page:null})};return r}();ua.a=Ba},474:function(Ba,ua,r){var pa=r(1),ka=r(0);r.n(ka);Ba=function(ma){function fa(da){var z=ma.call(this)||this;z.J$=Array.isArray(da)?da:[da];return z}Object(pa.c)(fa,ma);fa.prototype.parse=function(){var da=this,z={rp:null,eI:null,hw:{},ca:{}};this.J$.forEach(function(x){z=Object(ka.merge)(z,da.BA(x))});return z};fa.prototype.MT=function(da){var z=[];da.querySelectorAll("add > *").forEach(function(x){z.push(x)});da.querySelectorAll("modify > *").forEach(function(x){z.push(x)});
return z};fa.prototype.vT=function(da){return da.querySelectorAll("delete > *")};return fa}(r(459).a);ua.a=Ba},475:function(Ba,ua,r){var pa=r(1);Ba=function(ka){function ma(fa){var da=ka.call(this)||this;da.K$=fa;return da}Object(pa.c)(ma,ka);ma.prototype.parse=function(){return this.BA(this.K$)};ma.prototype.MT=function(fa){return fa.querySelectorAll("annots > *")};ma.prototype.vT=function(){return[]};return ma}(r(459).a);ua.a=Ba}}]);}).call(this || window)
=======
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[5],{471:function(Ba,wa,r){r.r(wa);var oa=r(0),na=r(493),ma=r(494),fa;(function(da){da[da.EXTERNAL_XFDF_NOT_REQUESTED=0]="EXTERNAL_XFDF_NOT_REQUESTED";da[da.EXTERNAL_XFDF_NOT_AVAILABLE=1]="EXTERNAL_XFDF_NOT_AVAILABLE";da[da.EXTERNAL_XFDF_AVAILABLE=2]="EXTERNAL_XFDF_AVAILABLE"})(fa||(fa={}));Ba=function(){function da(aa){this.aa=aa;this.state=fa.EXTERNAL_XFDF_NOT_REQUESTED}da.prototype.Hfa=function(){var aa=this;return function(w,
y,h){return Object(oa.b)(aa,void 0,void 0,function(){var a,b,e,f,n,z,x,ea=this,ja;return Object(oa.d)(this,function(ca){switch(ca.label){case 0:if(this.state!==fa.EXTERNAL_XFDF_NOT_REQUESTED)return[3,2];a=this.aa.getDocument().et();return[4,this.Rda(a)];case 1:b=ca.ca(),e=this.K9(b),this.BJ=null!==(ja=null===e||void 0===e?void 0:e.parse())&&void 0!==ja?ja:null,this.state=null===this.BJ?fa.EXTERNAL_XFDF_NOT_AVAILABLE:fa.EXTERNAL_XFDF_AVAILABLE,ca.label=2;case 2:if(this.state===fa.EXTERNAL_XFDF_NOT_AVAILABLE)return h(w),
[2];f=new DOMParser;n=f.parseFromString(w,"text/xml");y.forEach(function(ba){ea.merge(n,ea.BJ,ba-1)});z=new XMLSerializer;x=z.serializeToString(n);h(x);return[2]}})})}};da.prototype.BN=function(aa){this.Rda=aa};da.prototype.ye=function(){this.BJ=void 0;this.state=fa.EXTERNAL_XFDF_NOT_REQUESTED};da.prototype.K9=function(aa){return aa?Array.isArray(aa)?new na.a(aa):"string"!==typeof aa?null:(new DOMParser).parseFromString(aa,"text/xml").querySelector("xfdf > add")?new na.a(aa):new ma.a(aa):null};da.prototype.merge=
function(aa,w,y){var h=this;0===y&&(this.bia(aa,w.Lp),this.dia(aa,w.iJ));var a=w.da[y];a&&(this.eia(aa,a.Mn),this.gia(aa,a.D1,w.Qw),this.fia(aa,a.page,y),this.cia(aa,a.ST));a=this.aa.Ob();if(y===a-1){var b=w.Qw;Object.keys(b).forEach(function(e){b[e].QK||h.UX(aa,e,b[e])})}};da.prototype.bia=function(aa,w){null!==w&&(aa=this.bw(aa),this.br(aa,"calculation-order",w))};da.prototype.dia=function(aa,w){null!==w&&(aa=this.bw(aa),this.br(aa,"document-actions",w))};da.prototype.eia=function(aa,w){var y=this,
h=this.aw(aa.querySelector("xfdf"),"annots");Object.keys(w).forEach(function(a){y.br(h,'[name="'+a+'"]',w[a])})};da.prototype.gia=function(aa,w,y){var h=this;if(0!==w.length){var a=this.bw(aa);w.forEach(function(b){var e=b.getAttribute("field"),f=y[e];f&&(h.UX(aa,e,f),h.br(a,"null",b))})}};da.prototype.UX=function(aa,w,y){var h=this.bw(aa);null!==y.KC&&this.br(h,'ffield [name="'+w+'"]',y.KC);aa=this.aw(aa.querySelector("xfdf"),"fields");w=w.split(".");this.IM(aa,w,0,y.value);y.QK=!0};da.prototype.fia=
function(aa,w,y){null!==w&&(aa=this.bw(aa),aa=this.aw(aa,"pages"),this.br(aa,'[number="'+(y+1)+'"]',w))};da.prototype.cia=function(aa,w){Object.keys(w).forEach(function(y){(y=aa.querySelector('annots [name="'+y+'"]'))&&y.parentElement.removeChild(y)})};da.prototype.IM=function(aa,w,y,h){if(y===w.length)w=document.createElementNS("","value"),w.textContent=h,this.br(aa,"value",w);else{var a=w[y];this.aw(aa,'[name="'+a+'"]',"field").setAttribute("name",a);aa=aa.querySelectorAll('[name="'+a+'"]');1===
aa.length?this.IM(aa[0],w,y+1,h):(a=this.zca(aa),this.IM(y===w.length-1?a:this.upa(aa,a),w,y+1,h))}};da.prototype.zca=function(aa){for(var w=null,y=0;y<aa.length;y++){var h=aa[y];if(0===h.childElementCount||1===h.childElementCount&&"value"===h.children[0].tagName){w=h;break}}return w};da.prototype.upa=function(aa,w){for(var y=0;y<aa.length;y++)if(aa[y]!==w)return aa[y];return null};da.prototype.br=function(aa,w,y){w=aa.querySelector(w);null!==w&&aa.removeChild(w);aa.appendChild(y)};da.prototype.bw=
function(aa){var w=aa.querySelector("pdf-info");if(null!==w)return w;w=this.aw(aa.querySelector("xfdf"),"pdf-info");w.setAttribute("xmlns","http://www.pdftron.com/pdfinfo");w.setAttribute("version","2");w.setAttribute("import-version","4");return w};da.prototype.aw=function(aa,w,y){var h=aa.querySelector(w);if(null!==h)return h;h=document.createElementNS("",y||w);aa.appendChild(h);return h};return da}();wa["default"]=Ba},482:function(Ba,wa){Ba=function(){function r(){}r.prototype.oB=function(oa){var na=
{Lp:null,iJ:null,Qw:{},da:{}};oa=(new DOMParser).parseFromString(oa,"text/xml");na.Lp=oa.querySelector("pdf-info calculation-order");na.iJ=oa.querySelector("pdf-info document-actions");na.Qw=this.$ia(oa);na.da=this.lja(oa);return na};r.prototype.$ia=function(oa){var na=oa.querySelector("fields");oa=oa.querySelectorAll("pdf-info > ffield");if(null===na&&null===oa)return{};var ma={};this.W6(ma,na);this.U6(ma,oa);return ma};r.prototype.W6=function(oa,na){if(null!==na&&na.children){for(var ma=[],fa=0;fa<
na.children.length;fa++){var da=na.children[fa];ma.push({name:da.getAttribute("name"),element:da})}for(;0!==ma.length;)for(na=ma.shift(),fa=0;fa<na.element.children.length;fa++)da=na.element.children[fa],"value"===da.tagName?oa[na.name]={value:da.textContent,KC:null,QK:!1}:da.children&&ma.push({name:na.name+"."+da.getAttribute("name"),element:da})}};r.prototype.U6=function(oa,na){na.forEach(function(ma){var fa=ma.getAttribute("name");oa[fa]?oa[fa].KC=ma:oa[fa]={value:null,KC:ma,QK:!1}})};r.prototype.lja=
function(oa){var na=this,ma={};oa.querySelectorAll("pdf-info widget").forEach(function(fa){var da=parseInt(fa.getAttribute("page"),10)-1;na.ND(ma,da);ma[da].D1.push(fa)});oa.querySelectorAll("pdf-info page").forEach(function(fa){var da=parseInt(fa.getAttribute("number"),10)-1;na.ND(ma,da);ma[da].page=fa});this.AV(oa).forEach(function(fa){var da=parseInt(fa.getAttribute("page"),10),aa=fa.getAttribute("name");na.ND(ma,da);ma[da].Mn[aa]=fa});this.lV(oa).forEach(function(fa){var da=parseInt(fa.getAttribute("page"),
10);fa=fa.textContent;na.ND(ma,da);ma[da].ST[fa]=!0});return ma};r.prototype.ND=function(oa,na){oa[na]||(oa[na]={Mn:{},ST:{},D1:[],page:null})};return r}();wa.a=Ba},493:function(Ba,wa,r){var oa=r(0),na=r(1);r.n(na);Ba=function(ma){function fa(da){var aa=ma.call(this)||this;aa.kca=Array.isArray(da)?da:[da];return aa}Object(oa.c)(fa,ma);fa.prototype.parse=function(){var da=this,aa={Lp:null,iJ:null,Qw:{},da:{}};this.kca.forEach(function(w){aa=Object(na.merge)(aa,da.oB(w))});return aa};fa.prototype.AV=
function(da){var aa=[];da.querySelectorAll("add > *").forEach(function(w){aa.push(w)});da.querySelectorAll("modify > *").forEach(function(w){aa.push(w)});return aa};fa.prototype.lV=function(da){return da.querySelectorAll("delete > *")};return fa}(r(482).a);wa.a=Ba},494:function(Ba,wa,r){var oa=r(0);Ba=function(na){function ma(fa){var da=na.call(this)||this;da.lca=fa;return da}Object(oa.c)(ma,na);ma.prototype.parse=function(){return this.oB(this.lca)};ma.prototype.AV=function(fa){return fa.querySelectorAll("annots > *")};
ma.prototype.lV=function(){return[]};return ma}(r(482).a);wa.a=Ba}}]);}).call(this || window)
>>>>>>> 161efc3... Update lib to 8.10
