/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[4],{529:function(wa,sa,h){h.r(sa);var pa=h(0),na=h(552),ma=h(553),ja;(function(ia){ia[ia.EXTERNAL_XFDF_NOT_REQUESTED=0]="EXTERNAL_XFDF_NOT_REQUESTED";ia[ia.EXTERNAL_XFDF_NOT_AVAILABLE=1]="EXTERNAL_XFDF_NOT_AVAILABLE";ia[ia.EXTERNAL_XFDF_AVAILABLE=2]="EXTERNAL_XFDF_AVAILABLE"})(ja||(ja={}));wa=function(){function ia(ea){this.aa=ea;this.state=ja.EXTERNAL_XFDF_NOT_REQUESTED}ia.prototype.Sma=function(){var ea=this;return function(y,
z,f){return Object(pa.b)(ea,void 0,void 0,function(){var e,a,b,n,r,aa,w,ba=this,fa;return Object(pa.d)(this,function(x){switch(x.label){case 0:if(this.state!==ja.EXTERNAL_XFDF_NOT_REQUESTED)return[3,2];e=this.aa.getDocument().Ju();return[4,this.$ka(e)];case 1:a=x.ba(),b=this.ofa(a),this.JM=null!==(fa=null===b||void 0===b?void 0:b.parse())&&void 0!==fa?fa:null,this.state=null===this.JM?ja.EXTERNAL_XFDF_NOT_AVAILABLE:ja.EXTERNAL_XFDF_AVAILABLE,x.label=2;case 2:if(this.state===ja.EXTERNAL_XFDF_NOT_AVAILABLE)return f(y),
[2];n=new DOMParser;r=n.parseFromString(y,"text/xml");z.forEach(function(ca){ba.merge(r,ba.JM,ca-1)});aa=new XMLSerializer;w=aa.serializeToString(r);f(w);return[2]}})})}};ia.prototype.gR=function(ea){this.$ka=ea};ia.prototype.Ue=function(){this.JM=void 0;this.state=ja.EXTERNAL_XFDF_NOT_REQUESTED};ia.prototype.ofa=function(ea){return ea?Array.isArray(ea)?new na.a(ea):"string"!==typeof ea?null:(new DOMParser).parseFromString(ea,"text/xml").querySelector("xfdf > add")?new na.a(ea):new ma.a(ea):null};
ia.prototype.merge=function(ea,y,z){var f=this;0===z&&(this.Hpa(ea,y.Zq),this.Jpa(ea,y.oM));var e=y.ea[z];e&&(this.Kpa(ea,e.Oo),this.Mpa(ea,e.F7,y.Gy),this.Lpa(ea,e.page,z),this.Ipa(ea,e.oY));e=this.aa.Eb();if(z===e-1){var a=y.Gy;Object.keys(a).forEach(function(b){a[b].nO||f.X1(ea,b,a[b])})}};ia.prototype.Hpa=function(ea,y){null!==y&&(ea=this.Lx(ea),this.zs(ea,"calculation-order",y))};ia.prototype.Jpa=function(ea,y){null!==y&&(ea=this.Lx(ea),this.zs(ea,"document-actions",y))};ia.prototype.Kpa=function(ea,
y){var z=this,f=this.Kx(ea.querySelector("xfdf"),"annots");Object.keys(y).forEach(function(e){z.zs(f,'[name="'+e+'"]',y[e])})};ia.prototype.Mpa=function(ea,y,z){var f=this;if(0!==y.length){var e=this.Lx(ea);y.forEach(function(a){var b=a.getAttribute("field"),n=z[b];n&&(f.X1(ea,b,n),f.zs(e,"null",a))})}};ia.prototype.X1=function(ea,y,z){var f=this.Lx(ea),e=f.querySelector('ffield[name="'+y+'"]');null!==z.aF&&null===e&&this.zs(f,'ffield[name="'+y+'"]',z.aF);ea=this.Kx(ea.querySelector("xfdf"),"xfdf > fields",
"fields");y=y.split(".");this.jQ(ea,y,0,z.value);z.nO=!0};ia.prototype.Lpa=function(ea,y,z){null!==y&&(ea=this.Lx(ea),ea=this.Kx(ea,"pages"),this.zs(ea,'[number="'+(z+1)+'"]',y))};ia.prototype.Ipa=function(ea,y){Object.keys(y).forEach(function(z){(z=ea.querySelector('annots [name="'+z+'"]'))&&z.parentElement.removeChild(z)})};ia.prototype.jQ=function(ea,y,z,f){if(z===y.length)y=document.createElementNS("","value"),y.textContent=f,this.zs(ea,"value",y);else{var e=y[z];this.Kx(ea,'[name="'+e+'"]',"field").setAttribute("name",
e);ea=ea.querySelectorAll('[name="'+e+'"]');1===ea.length?this.jQ(ea[0],y,z+1,f):(e=this.oja(ea),this.jQ(z===y.length-1?e:this.Sxa(ea,e),y,z+1,f))}};ia.prototype.oja=function(ea){for(var y=null,z=0;z<ea.length;z++){var f=ea[z];if(0===f.childElementCount||1===f.childElementCount&&"value"===f.children[0].tagName){y=f;break}}return y};ia.prototype.Sxa=function(ea,y){for(var z=0;z<ea.length;z++)if(ea[z]!==y)return ea[z];return null};ia.prototype.zs=function(ea,y,z){y=ea.querySelector(y);null!==y&&ea.removeChild(y);
ea.appendChild(z)};ia.prototype.Lx=function(ea){var y=ea.querySelector("pdf-info");if(null!==y)return y;y=this.Kx(ea.querySelector("xfdf"),"pdf-info");y.setAttribute("xmlns","http://www.pdftron.com/pdfinfo");y.setAttribute("version","2");y.setAttribute("import-version","4");return y};ia.prototype.Kx=function(ea,y,z){var f=ea.querySelector(y);if(null!==f)return f;f=document.createElementNS("",z||y);ea.appendChild(f);return f};return ia}();sa["default"]=wa},541:function(wa,sa){wa=function(){function h(){}
h.prototype.zD=function(pa){var na={Zq:null,oM:null,Gy:{},ea:{}};pa=(new DOMParser).parseFromString(pa,"text/xml");na.Zq=pa.querySelector("pdf-info calculation-order");na.oM=pa.querySelector("pdf-info document-actions");na.Gy=this.$qa(pa);na.ea=this.nra(pa);return na};h.prototype.$qa=function(pa){var na=pa.querySelector("fields");pa=pa.querySelectorAll("pdf-info > ffield");if(null===na&&null===pa)return{};var ma={};this.mca(ma,na);this.kca(ma,pa);return ma};h.prototype.mca=function(pa,na){if(null!==
na&&na.children){for(var ma=[],ja=0;ja<na.children.length;ja++){var ia=na.children[ja];ma.push({name:ia.getAttribute("name"),element:ia})}for(;0!==ma.length;)for(na=ma.shift(),ja=0;ja<na.element.children.length;ja++)ia=na.element.children[ja],"value"===ia.tagName?pa[na.name]={value:ia.textContent,aF:null,nO:!1}:ia.children&&ma.push({name:na.name+"."+ia.getAttribute("name"),element:ia})}};h.prototype.kca=function(pa,na){na.forEach(function(ma){var ja=ma.getAttribute("name");pa[ja]?pa[ja].aF=ma:pa[ja]=
{value:null,aF:ma,nO:!1}})};h.prototype.nra=function(pa){var na=this,ma={};pa.querySelectorAll("pdf-info widget").forEach(function(ja){var ia=parseInt(ja.getAttribute("page"),10)-1;na.oG(ma,ia);ma[ia].F7.push(ja)});pa.querySelectorAll("pdf-info page").forEach(function(ja){var ia=parseInt(ja.getAttribute("number"),10)-1;na.oG(ma,ia);ma[ia].page=ja});this.k_(pa).forEach(function(ja){var ia=parseInt(ja.getAttribute("page"),10),ea=ja.getAttribute("name");na.oG(ma,ia);ma[ia].Oo[ea]=ja});this.XZ(pa).forEach(function(ja){var ia=
parseInt(ja.getAttribute("page"),10);ja=ja.textContent;na.oG(ma,ia);ma[ia].oY[ja]=!0});return ma};h.prototype.oG=function(pa,na){pa[na]||(pa[na]={Oo:{},oY:{},F7:[],page:null})};return h}();sa.a=wa},552:function(wa,sa,h){var pa=h(0),na=h(1);h.n(na);wa=function(ma){function ja(ia){var ea=ma.call(this)||this;ea.Yia=Array.isArray(ia)?ia:[ia];return ea}Object(pa.c)(ja,ma);ja.prototype.parse=function(){var ia=this,ea={Zq:null,oM:null,Gy:{},ea:{}};this.Yia.forEach(function(y){ea=Object(na.merge)(ea,ia.zD(y))});
return ea};ja.prototype.k_=function(ia){var ea=[];ia.querySelectorAll("add > *").forEach(function(y){ea.push(y)});ia.querySelectorAll("modify > *").forEach(function(y){ea.push(y)});return ea};ja.prototype.XZ=function(ia){return ia.querySelectorAll("delete > *")};return ja}(h(541).a);sa.a=wa},553:function(wa,sa,h){var pa=h(0);wa=function(na){function ma(ja){var ia=na.call(this)||this;ia.Zia=ja;return ia}Object(pa.c)(ma,na);ma.prototype.parse=function(){return this.zD(this.Zia)};ma.prototype.k_=function(ja){return ja.querySelectorAll("annots > *")};
ma.prototype.XZ=function(){return[]};return ma}(h(541).a);sa.a=wa}}]);}).call(this || window)
