/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[0],{429:function(Aa,ua,r){r.r(ua);r.d(ua,"ByteRangeRequest",function(){return z});var pa=r(1),ka=r(0);r.n(ka);var ma=r(2),ha=r(147);Aa=r(94);var da=r(245),aa=r(73),x=r(70),y=r(244),h=r(165);r=r(372);var e=[],b=[],a=window,f=function(){return function(){this.am=1}}(),n;(function(ea){ea[ea.UNSENT=0]="UNSENT";ea[ea.DONE=4]="DONE"})(n||(n={}));var z=function(){function ea(ja,ca,ba,fa){var ia=this;this.url=ja;this.range=ca;this.cf=ba;
this.withCredentials=fa;this.F1=n;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);a.Uint8Array&&(this.request.responseType="arraybuffer");fa&&(this.request.withCredentials=fa);w.DISABLE_RANGE_HEADER||(Object(ka.isUndefined)(ca.stop)?this.request.setRequestHeader("Range","bytes="+ca.start):this.request.setRequestHeader("Range",["bytes=",ca.start,"-",ca.stop-1].join("")));ba&&Object.keys(ba).forEach(function(la){ia.request.setRequestHeader(la,ba[la])});this.request.overrideMimeType?
this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=y.a.NOT_STARTED}ea.prototype.start=function(ja){var ca=this,ba=this.request;ba.onreadystatechange=function(){if(ca.aborted)return ca.status=y.a.ABORTED,ja({code:y.a.ABORTED});if(this.readyState===ca.F1.DONE){ca.pC();var fa=0===window.document.URL.indexOf("file:///");200===ba.status||206===ba.status||fa&&0===ba.status?(fa=a.AT(this),ca.HM(fa,ja)):(ca.status=
y.a.ERROR,ja({code:ca.status,status:ca.status}))}};this.request.send(null);this.status=y.a.STARTED};ea.prototype.HM=function(ja,ca){this.status=y.a.SUCCESS;if(ca)return ca(!1,ja)};ea.prototype.abort=function(){this.pC();this.aborted=!0;this.request.abort()};ea.prototype.pC=function(){var ja=Object(h.c)(this.url,this.range,b);-1!==ja&&b.splice(ja,1);if(0<e.length){ja=e.shift();var ca=new ea(ja.url,ja.range,this.cf,this.withCredentials);ja.request=ca;b.push(ja);ca.start(Object(h.d)(ja))}};ea.prototype.extend=
function(ja){var ca=Object.assign({},this,ja.prototype);ca.constructor=ja;return ca};return ea}(),w=function(ea){function ja(ca,ba,fa,ia,la){fa=ea.call(this,ca,fa,ia)||this;fa.em={};fa.SA=ba;fa.url=ca;fa.DISABLE_RANGE_HEADER=!1;fa.Kx=z;fa.EN=3;fa.cf=la||{};return fa}Object(pa.c)(ja,ea);ja.prototype.Ev=function(ca,ba,fa){var ia=-1===ca.indexOf("?")?"?":"&";switch(fa){case !1:case x.a.NEVER_CACHE:ca=ca+ia+"_="+Object(ka.uniqueId)();break;case !0:case x.a.CACHE:ca=ca+ia+"_="+ba.start+","+(Object(ka.isUndefined)(ba.stop)?
"":ba.stop)}return ca};ja.prototype.yR=function(ca,ba,fa,ia){void 0===fa&&(fa={});return new this.Kx(ca,ba,fa,ia)};ja.prototype.O9=function(ca,ba,fa,ia,la){for(var na=0;na<e.length;na++)if(Object(ka.isEqual)(e[na].range,ba)&&Object(ka.isEqual)(e[na].url,ca))return e[na].Kg.push(ia),e[na].tD++,null;for(na=0;na<b.length;na++)if(Object(ka.isEqual)(b[na].range,ba)&&Object(ka.isEqual)(b[na].url,ca))return b[na].Kg.push(ia),b[na].tD++,null;fa={url:ca,range:ba,SA:fa,Kg:[ia],tD:1};if(0===e.length&&b.length<
this.EN)return b.push(fa),fa.request=this.yR(ca,ba,la,this.withCredentials),fa;e.push(fa);return null};ja.prototype.Un=function(ca,ba,fa){var ia=this.Ev(ca,ba,this.SA);(ca=this.O9(ia,ba,this.SA,fa,this.cf))&&ca.request.start(Object(h.d)(ca));return function(){var la=Object(h.c)(ia,ba,b);if(-1!==la){var na=--b[la].tD;0===na&&b[la].request&&b[la].request.abort()}else la=Object(h.c)(ia,ba,e),-1!==la&&(na=--e[la].tD,0===na&&e.splice(la,1))}};ja.prototype.eT=function(){return{start:-ha.a}};ja.prototype.tca=
function(){var ca=-(ha.a+ha.e);return{start:ca-ha.d,end:ca}};ja.prototype.et=function(ca){var ba=this;this.ZA=!0;var fa=ha.a;this.Un(this.url,this.eT(),function(ia,la,na){function ra(){var qa=ba.Yd.aT();ba.Un(ba.url,qa,function(ta,va){if(ta)return Object(ma.j)("Error loading central directory: "+ta),ca(ta);va=Object(aa.a)(va);if(va.length!==qa.stop-qa.start)return ca("Invalid XOD file: Zip central directory data is wrong size! Should be "+(qa.stop-qa.start)+" but is "+va.length);ba.Yd.UW(va);ba.rH=
!0;ba.ZA=!1;return ca(!1)})}if(ia)return Object(ma.j)("Error loading end header: "+ia),ca(ia,la,na);la=Object(aa.a)(la);if(la.length!==fa)return ca("Invalid XOD file: Zip end header data is wrong size!");try{ba.Yd=new da.a(la)}catch(qa){return ca(qa)}ba.Yd.Wda?ba.Un(ba.url,ba.tca(),function(qa,ta){if(qa)return Object(ma.j)("Error loading zip64 header: "+qa),ca(qa);ta=Object(aa.a)(ta);ba.Yd.oea(ta);ra()}):ra()})};ja.prototype.xT=function(ca){ca(Object.keys(this.Yd.sn))};ja.prototype.lL=function(ca,
ba){var fa=this;if(this.Yd.nR(ca)){var ia=this.Yd.jC(ca);if(ia in this.em){var la=this.Vh[ca];la.Pr=this.em[ia];la.Pr.am++;la.cancel=la.Pr.cancel}else{var na=this.Yd.Gaa(ca),ra=this.Un(this.url,na,function(ta,va){ta?(Object(ma.j)('Error loading part "'+ca+'": '+ta),fa.Un(fa.url,na,function(oa,wa){if(oa)return ba(oa,ca);fa.YW(wa,na,ia,ca,ba)})):fa.YW(va,na,ia,ca,ba)}),qa=this.Vh[ca];qa&&(qa.$Y=!0,qa.cancel=function(){qa.Pr.am--;0===qa.Pr.am&&(ra(),delete fa.em[ia])},this.em[ia]=new f(ia),qa.Pr=this.em[ia],
qa.Pr.cancel=qa.cancel)}}else delete this.Vh[ca],ba(Error('File not found: "'+ca+'"'),ca)};ja.prototype.YW=function(ca,ba,fa,ia,la){if(ca.length!==ba.stop-ba.start)la(Error("Part data is wrong size!"),ia);else{do{if(!this.em[fa])return;ia=this.em[fa].am;for(var na=ba.yq.length,ra=0;ra<na;++ra){var qa=ba.yq[ra];la(!1,qa.uq,ca["string"===typeof ca?"substring":"subarray"](qa.start,qa.stop),this.Yd.BU(qa.uq));qa.uq in this.Vh&&delete this.Vh[qa.uq]}}while(ia!==this.em[fa].am);delete this.em[fa]}};ja.DISABLE_RANGE_HEADER=
!1;ja.EN=3;return ja}(Aa.a);(function(ea){function ja(ca,ba,fa){var ia=ea.call(this)||this,la;for(la in ca)ia[la]=ca[la];ia.vpa=ca;ia.startOffset=ba;ia.endOffset=fa;ia.yR=function(na,ra,qa,ta){Object(ka.isUndefined)(ra.stop)?(ra.start+=ia.endOffset,ra.stop=ia.endOffset):(ra.start+=ia.startOffset,ra.stop+=ia.startOffset);na=ia.Ev(ia.url,ra,ia.SA);return new ca.Kx(na,ra,qa,ta)};return ia}Object(pa.c)(ja,ea);return ja})(w);Object(r.a)(w);Object(r.b)(w);ua["default"]=w}}]);}).call(this || window)
