/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
<<<<<<< HEAD
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[0],{432:function(Ba,ua,r){r.r(ua);r.d(ua,"ByteRangeRequest",function(){return aa});var pa=r(1),ka=r(0);r.n(ka);var ma=r(2),fa=r(149);Ba=r(94);var da=r(246),z=r(73),x=r(71),y=r(245),f=r(166);r=r(374);var e=[],b=[],a=window,h=function(){return function(){this.lm=1}}(),n;(function(ea){ea[ea.UNSENT=0]="UNSENT";ea[ea.DONE=4]="DONE"})(n||(n={}));var aa=function(){function ea(ja,ba,ca,ia){var ha=this;this.url=ja;this.range=ba;this.df=ca;
this.withCredentials=ia;this.q2=n;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);a.Uint8Array&&(this.request.responseType="arraybuffer");ia&&(this.request.withCredentials=ia);w.DISABLE_RANGE_HEADER||(Object(ka.isUndefined)(ba.stop)?this.request.setRequestHeader("Range","bytes="+ba.start):this.request.setRequestHeader("Range",["bytes=",ba.start,"-",ba.stop-1].join("")));ca&&Object.keys(ca).forEach(function(la){ha.request.setRequestHeader(la,ca[la])});this.request.overrideMimeType?
this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=y.a.NOT_STARTED}ea.prototype.start=function(ja){var ba=this,ca=this.request;ca.onreadystatechange=function(){if(ba.aborted)return ba.status=y.a.ABORTED,ja({code:y.a.ABORTED});if(this.readyState===ba.q2.DONE){ba.BC();var ia=0===window.document.URL.indexOf("file:///");200===ca.status||206===ca.status||ia&&0===ca.status?(ia=a.bU(this),ba.bN(ia,ja)):(ba.status=
y.a.ERROR,ja({code:ba.status,status:ba.status}))}};this.request.send(null);this.status=y.a.STARTED};ea.prototype.bN=function(ja,ba){this.status=y.a.SUCCESS;if(ba)return ba(!1,ja)};ea.prototype.abort=function(){this.BC();this.aborted=!0;this.request.abort()};ea.prototype.BC=function(){var ja=Object(f.c)(this.url,this.range,b);-1!==ja&&b.splice(ja,1);if(0<e.length){ja=e.shift();var ba=new ea(ja.url,ja.range,this.df,this.withCredentials);ja.request=ba;b.push(ja);ba.start(Object(f.d)(ja))}};ea.prototype.extend=
function(ja){var ba=Object.assign({},this,ja.prototype);ba.constructor=ja;return ba};return ea}(),w=function(ea){function ja(ba,ca,ia,ha,la){ia=ea.call(this,ba,ia,ha)||this;ia.pm={};ia.dB=ca;ia.url=ba;ia.DISABLE_RANGE_HEADER=!1;ia.Vx=aa;ia.ZN=3;ia.df=la||{};return ia}Object(pa.c)(ja,ea);ja.prototype.Ov=function(ba,ca,ia){var ha=-1===ba.indexOf("?")?"?":"&";switch(ia){case !1:case x.a.NEVER_CACHE:ba=ba+ha+"_="+Object(ka.uniqueId)();break;case !0:case x.a.CACHE:ba=ba+ha+"_="+ca.start+","+(Object(ka.isUndefined)(ca.stop)?
"":ca.stop)}return ba};ja.prototype.SR=function(ba,ca,ia,ha){void 0===ia&&(ia={});return new this.Vx(ba,ca,ia,ha)};ja.prototype.z$=function(ba,ca,ia,ha,la){for(var na=0;na<e.length;na++)if(Object(ka.isEqual)(e[na].range,ca)&&Object(ka.isEqual)(e[na].url,ba))return e[na].Og.push(ha),e[na].GD++,null;for(na=0;na<b.length;na++)if(Object(ka.isEqual)(b[na].range,ca)&&Object(ka.isEqual)(b[na].url,ba))return b[na].Og.push(ha),b[na].GD++,null;ia={url:ba,range:ca,dB:ia,Og:[ha],GD:1};if(0===e.length&&b.length<
this.ZN)return b.push(ia),ia.request=this.SR(ba,ca,la,this.withCredentials),ia;e.push(ia);return null};ja.prototype.io=function(ba,ca,ia){var ha=this.Ov(ba,ca,this.dB);(ba=this.z$(ha,ca,this.dB,ia,this.df))&&ba.request.start(Object(f.d)(ba));return function(){var la=Object(f.c)(ha,ca,b);if(-1!==la){var na=--b[la].GD;0===na&&b[la].request&&b[la].request.abort()}else la=Object(f.c)(ha,ca,e),-1!==la&&(na=--e[la].GD,0===na&&e.splice(la,1))}};ja.prototype.AT=function(){return{start:-fa.a}};ja.prototype.fda=
function(){var ba=-(fa.a+fa.e);return{start:ba-fa.d,end:ba}};ja.prototype.qt=function(ba){var ca=this;this.jB=!0;var ia=fa.a;this.io(this.url,this.AT(),function(ha,la,na){function qa(){var ra=ca.Zd.wT();ca.io(ca.url,ra,function(ta,va){if(ta)return Object(ma.j)("Error loading central directory: "+ta),ba(ta);va=Object(z.a)(va);if(va.length!==ra.stop-ra.start)return ba("Invalid XOD file: Zip central directory data is wrong size! Should be "+(ra.stop-ra.start)+" but is "+va.length);ca.Zd.uX(va);ca.GH=
!0;ca.jB=!1;return ba(!1)})}if(ha)return Object(ma.j)("Error loading end header: "+ha),ba(ha,la,na);la=Object(z.a)(la);if(la.length!==ia)return ba("Invalid XOD file: Zip end header data is wrong size!");try{ca.Zd=new da.a(la)}catch(ra){return ba(ra)}ca.Zd.Jea?ca.io(ca.url,ca.fda(),function(ra,ta){if(ra)return Object(ma.j)("Error loading zip64 header: "+ra),ba(ra);ta=Object(z.a)(ta);ca.Zd.bfa(ta);qa()}):qa()})};ja.prototype.ZT=function(ba){ba(Object.keys(this.Zd.Hn))};ja.prototype.DL=function(ba,ca){var ia=
this;if(this.Zd.HR(ba)){var ha=this.Zd.vC(ba);if(ha in this.pm){var la=this.Zh[ba];la.Yr=this.pm[ha];la.Yr.lm++;la.cancel=la.Yr.cancel}else{var na=this.Zd.rba(ba),qa=this.io(this.url,na,function(ta,va){ta?(Object(ma.j)('Error loading part "'+ba+'": '+ta),ia.io(ia.url,na,function(oa,wa){if(oa)return ca(oa,ba);ia.yX(wa,na,ha,ba,ca)})):ia.yX(va,na,ha,ba,ca)}),ra=this.Zh[ba];ra&&(ra.DZ=!0,ra.cancel=function(){ra.Yr.lm--;0===ra.Yr.lm&&(qa(),delete ia.pm[ha])},this.pm[ha]=new h(ha),ra.Yr=this.pm[ha],ra.Yr.cancel=
ra.cancel)}}else delete this.Zh[ba],ca(Error('File not found: "'+ba+'"'),ba)};ja.prototype.yX=function(ba,ca,ia,ha,la){if(ba.length!==ca.stop-ca.start)la(Error("Part data is wrong size!"),ha);else{do{if(!this.pm[ia])return;ha=this.pm[ia].lm;for(var na=ca.Iq.length,qa=0;qa<na;++qa){var ra=ca.Iq[qa];la(!1,ra.Eq,ba["string"===typeof ba?"substring":"subarray"](ra.start,ra.stop),this.Zd.$U(ra.Eq));ra.Eq in this.Zh&&delete this.Zh[ra.Eq]}}while(ha!==this.pm[ia].lm);delete this.pm[ia]}};ja.DISABLE_RANGE_HEADER=
!1;ja.ZN=3;return ja}(Ba.a);(function(ea){function ja(ba,ca,ia){var ha=ea.call(this)||this,la;for(la in ba)ha[la]=ba[la];ha.dqa=ba;ha.startOffset=ca;ha.endOffset=ia;ha.SR=function(na,qa,ra,ta){Object(ka.isUndefined)(qa.stop)?(qa.start+=ha.endOffset,qa.stop=ha.endOffset):(qa.start+=ha.startOffset,qa.stop+=ha.startOffset);na=ha.Ov(ha.url,qa,ha.dB);return new ba.Vx(na,qa,ra,ta)};return ha}Object(pa.c)(ja,ea);return ja})(w);Object(r.a)(w);Object(r.b)(w);ua["default"]=w}}]);}).call(this || window)
=======
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[0],{456:function(Ba,wa,r){r.r(wa);r.d(wa,"ByteRangeRequest",function(){return z});var oa=r(0),na=r(1);r.n(na);var ma=r(2),fa=r(157);Ba=r(100);var da=r(261),aa=r(78),w=r(74),y=r(260),h=r(177);r=r(393);var a=[],b=[],e=window,f=function(){return function(){this.Nm=1}}(),n;(function(ea){ea[ea.UNSENT=0]="UNSENT";ea[ea.DONE=4]="DONE"})(n||(n={}));var z=function(){function ea(ja,ca,ba,ha){var ia=this;this.url=ja;this.range=ca;this.nf=ba;
this.withCredentials=ha;this.I4=n;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);e.Uint8Array&&(this.request.responseType="arraybuffer");ha&&(this.request.withCredentials=ha);x.DISABLE_RANGE_HEADER||(Object(na.isUndefined)(ca.stop)?this.request.setRequestHeader("Range","bytes="+ca.start):this.request.setRequestHeader("Range",["bytes=",ca.start,"-",ca.stop-1].join("")));ba&&Object.keys(ba).forEach(function(la){ia.request.setRequestHeader(la,ba[la])});this.request.overrideMimeType?
this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=y.a.NOT_STARTED}ea.prototype.start=function(ja){var ca=this,ba=this.request;ba.onreadystatechange=function(){if(ca.aborted)return ca.status=y.a.ABORTED,ja({code:y.a.ABORTED});if(this.readyState===ca.I4.DONE){ca.nD();var ha=0===window.document.URL.indexOf("file:///");200===ba.status||206===ba.status||ha&&0===ba.status?(ha=e.NV(this),ca.pO(ha,ja)):(ca.status=
y.a.ERROR,ja({code:ca.status,status:ca.status}))}};this.request.send(null);this.status=y.a.STARTED};ea.prototype.pO=function(ja,ca){this.status=y.a.SUCCESS;if(ca)return ca(!1,ja)};ea.prototype.abort=function(){this.nD();this.aborted=!0;this.request.abort()};ea.prototype.nD=function(){var ja=Object(h.c)(this.url,this.range,b);-1!==ja&&b.splice(ja,1);if(0<a.length){ja=a.shift();var ca=new ea(ja.url,ja.range,this.nf,this.withCredentials);ja.request=ca;b.push(ja);ca.start(Object(h.d)(ja))}};ea.prototype.extend=
function(ja){var ca=Object.assign({},this,ja.prototype);ca.constructor=ja;return ca};return ea}(),x=function(ea){function ja(ca,ba,ha,ia,la){ha=ea.call(this,ca,ha,ia)||this;ha.tj={};ha.PB=ba;ha.url=ca;ha.DISABLE_RANGE_HEADER=!1;ha.Ky=z;ha.iP=3;ha.nf=la||{};return ha}Object(oa.c)(ja,ea);ja.prototype.uw=function(ca,ba,ha){var ia=-1===ca.indexOf("?")?"?":"&";switch(ha){case !1:case w.a.NEVER_CACHE:ca=ca+ia+"_="+Object(na.uniqueId)();break;case !0:case w.a.CACHE:ca=ca+ia+"_="+ba.start+","+(Object(na.isUndefined)(ba.stop)?
"":ba.stop)}return ca};ja.prototype.yT=function(ca,ba,ha,ia){void 0===ha&&(ha={});return new this.Ky(ca,ba,ha,ia)};ja.prototype.$ba=function(ca,ba,ha,ia,la){for(var ka=0;ka<a.length;ka++)if(Object(na.isEqual)(a[ka].range,ba)&&Object(na.isEqual)(a[ka].url,ca))return a[ka].ah.push(ia),a[ka].tE++,null;for(ka=0;ka<b.length;ka++)if(Object(na.isEqual)(b[ka].range,ba)&&Object(na.isEqual)(b[ka].url,ca))return b[ka].ah.push(ia),b[ka].tE++,null;ha={url:ca,range:ba,PB:ha,ah:[ia],tE:1};if(0===a.length&&b.length<
this.iP)return b.push(ha),ha.request=this.yT(ca,ba,la,this.withCredentials),ha;a.push(ha);return null};ja.prototype.Do=function(ca,ba,ha){var ia=this.uw(ca,ba,this.PB);(ca=this.$ba(ia,ba,this.PB,ha,this.nf))&&ca.request.start(Object(h.d)(ca));return function(){var la=Object(h.c)(ia,ba,b);if(-1!==la){var ka=--b[la].tE;0===ka&&b[la].request&&b[la].request.abort()}else la=Object(h.c)(ia,ba,a),-1!==la&&(ka=--a[la].tE,0===ka&&a.splice(la,1))}};ja.prototype.qV=function(){return{start:-fa.a}};ja.prototype.Ofa=
function(){var ca=-(fa.a+fa.e);return{start:ca-fa.d,end:ca}};ja.prototype.Xt=function(ca){var ba=this;this.VB=!0;var ha=fa.a;this.Do(this.url,this.qV(),function(ia,la,ka){function qa(){var pa=ba.Bd.mV();ba.Do(ba.url,pa,function(ra,ua){if(ra)return Object(ma.j)("Error loading central directory: "+ra),ca(ra);ua=Object(aa.a)(ua);if(ua.length!==pa.stop-pa.start)return ca("Invalid XOD file: Zip central directory data is wrong size! Should be "+(pa.stop-pa.start)+" but is "+ua.length);ba.Bd.rZ(ua);ba.HI=
!0;ba.VB=!1;return ca(!1)})}if(ia)return Object(ma.j)("Error loading end header: "+ia),ca(ia,la,ka);la=Object(aa.a)(la);if(la.length!==ha)return ca("Invalid XOD file: Zip end header data is wrong size!");try{ba.Bd=new da.a(la)}catch(pa){return ca(pa)}ba.Bd.wha?ba.Do(ba.url,ba.Ofa(),function(pa,ra){if(pa)return Object(ma.j)("Error loading zip64 header: "+pa),ca(pa);ra=Object(aa.a)(ra);ba.Bd.Pha(ra);qa()}):qa()})};ja.prototype.KV=function(ca){ca(Object.keys(this.Bd.$n))};ja.prototype.NM=function(ca,
ba){var ha=this;if(this.Bd.nT(ca)){var ia=this.Bd.gx(ca);if(ia in this.tj){var la=this.vh[ca];la.Ds=this.tj[ia];la.Ds.Nm++;la.cancel=la.Ds.cancel}else{var ka=this.Bd.Yda(ca),qa=this.Do(this.url,ka,function(ra,ua){ra?(Object(ma.j)('Error loading part "'+ca+'": '+ra),ha.Do(ha.url,ka,function(va,sa){if(va)return ba(va,ca);ha.vZ(sa,ka,ia,ca,ba)})):ha.vZ(ua,ka,ia,ca,ba)}),pa=this.vh[ca];pa&&(pa.G0=!0,pa.cancel=function(){pa.Ds.Nm--;0===pa.Ds.Nm&&(qa(),delete ha.tj[ia])},this.tj[ia]=new f(ia),pa.Ds=this.tj[ia],
pa.Ds.cancel=pa.cancel)}}else delete this.vh[ca],ba(Error('File not found: "'+ca+'"'),ca)};ja.prototype.vZ=function(ca,ba,ha,ia,la){if(ca.length!==ba.stop-ba.start)la(Error("Part data is wrong size!"),ia);else{do{if(!this.tj[ha])return;ia=this.tj[ha].Nm;for(var ka=ba.dr.length,qa=0;qa<ka;++qa){var pa=ba.dr[qa];la(!1,pa.Zq,ca["string"===typeof ca?"substring":"subarray"](pa.start,pa.stop),this.Bd.RW(pa.Zq));pa.Zq in this.vh&&delete this.vh[pa.Zq]}}while(ia!==this.tj[ha].Nm);delete this.tj[ha]}};ja.DISABLE_RANGE_HEADER=
!1;ja.iP=3;return ja}(Ba.a);(function(ea){function ja(ca,ba,ha){var ia=ea.call(this)||this,la;for(la in ca)ia[la]=ca[la];ia.wta=ca;ia.startOffset=ba;ia.endOffset=ha;ia.yT=function(ka,qa,pa,ra){Object(na.isUndefined)(qa.stop)?(qa.start+=ia.endOffset,qa.stop=ia.endOffset):(qa.start+=ia.startOffset,qa.stop+=ia.startOffset);ka=ia.uw(ia.url,qa,ia.PB);return new ca.Ky(ka,qa,pa,ra)};return ia}Object(oa.c)(ja,ea);return ja})(x);Object(r.a)(x);Object(r.b)(x);wa["default"]=x}}]);}).call(this || window)
>>>>>>> 161efc3... Update lib to 8.10
