/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[0],{514:function(wa,sa,h){h.r(sa);h.d(sa,"ByteRangeRequest",function(){return aa});var pa=h(0),na=h(1);h.n(na);var ma=h(3),ja=h(176);wa=h(112);var ia=h(290),ea=h(87),y=h(82),z=h(289),f=h(193);h=h(435);var e=[],a=[],b=window,n=function(){return function(){this.Mn=1}}(),r;(function(ba){ba[ba.UNSENT=0]="UNSENT";ba[ba.DONE=4]="DONE"})(r||(r={}));var aa=function(){function ba(fa,x,ca,ha){var oa=this;this.url=fa;this.range=x;this.Rf=ca;
this.withCredentials=ha;this.R$=r;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);b.Uint8Array&&(this.request.responseType="arraybuffer");ha&&(this.request.withCredentials=ha);w.DISABLE_RANGE_HEADER||(Object(na.isUndefined)(x.stop)?this.request.setRequestHeader("Range","bytes="+x.start):this.request.setRequestHeader("Range",["bytes=",x.start,"-",x.stop-1].join("")));ca&&Object.keys(ca).forEach(function(la){oa.request.setRequestHeader(la,ca[la])});this.request.overrideMimeType?
this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=z.a.NOT_STARTED}ba.prototype.start=function(fa){var x=this,ca=this.request;ca.onreadystatechange=function(){if(x.aborted)return x.status=z.a.ABORTED,fa({code:z.a.ABORTED});if(this.readyState===x.R$.DONE){x.KF();var ha=0===window.document.URL.indexOf("file:///");200===ca.status||206===ca.status||ha&&0===ca.status?(ha=b.B_(this),x.YR(ha,fa)):(x.status=z.a.ERROR,
fa({code:x.status,status:x.status}))}};this.request.send(null);this.status=z.a.STARTED};ba.prototype.YR=function(fa,x){this.status=z.a.SUCCESS;if(x)return x(!1,fa)};ba.prototype.abort=function(){this.KF();this.aborted=!0;this.request.abort()};ba.prototype.KF=function(){var fa=Object(f.c)(this.url,this.range,a);-1!==fa&&a.splice(fa,1);if(0<e.length){fa=e.shift();var x=new ba(fa.url,fa.range,this.Rf,this.withCredentials);fa.request=x;a.push(fa);x.start(Object(f.d)(fa))}};ba.prototype.extend=function(fa){var x=
Object.assign({},this,fa.prototype);x.constructor=fa;return x};return ba}(),w=function(ba){function fa(x,ca,ha,oa,la){ha=ba.call(this,x,ha,oa)||this;ha.$j={};ha.bE=ca;ha.url=x;ha.DISABLE_RANGE_HEADER=!1;ha.LA=aa;ha.gT=3;ha.Rf=la||{};return ha}Object(pa.c)(fa,ba);fa.prototype.jy=function(x,ca,ha){var oa=-1===x.indexOf("?")?"?":"&";switch(ha){case !1:case y.a.NEVER_CACHE:x=x+oa+"_="+Object(na.uniqueId)();break;case !0:case y.a.CACHE:x=x+oa+"_="+ca.start+","+(Object(na.isUndefined)(ca.stop)?"":ca.stop)}return x};
fa.prototype.XX=function(x,ca,ha,oa){void 0===ha&&(ha={});return new this.LA(x,ca,ha,oa)};fa.prototype.Nia=function(x,ca,ha,oa,la){for(var ka=0;ka<e.length;ka++)if(Object(na.isEqual)(e[ka].range,ca)&&Object(na.isEqual)(e[ka].url,x))return e[ka].Dh.push(oa),e[ka].dH++,null;for(ka=0;ka<a.length;ka++)if(Object(na.isEqual)(a[ka].range,ca)&&Object(na.isEqual)(a[ka].url,x))return a[ka].Dh.push(oa),a[ka].dH++,null;ha={url:x,range:ca,bE:ha,Dh:[oa],dH:1};if(0===e.length&&a.length<this.gT)return a.push(ha),
ha.request=this.XX(x,ca,la,this.withCredentials),ha;e.push(ha);return null};fa.prototype.Lp=function(x,ca,ha){var oa=this.jy(x,ca,this.bE);(x=this.Nia(oa,ca,this.bE,ha,this.Rf))&&x.request.start(Object(f.d)(x));return function(){var la=Object(f.c)(oa,ca,a);if(-1!==la){var ka=--a[la].dH;0===ka&&a[la].request&&a[la].request.abort()}else la=Object(f.c)(oa,ca,e),-1!==la&&(ka=--e[la].dH,0===ka&&e.splice(la,1))}};fa.prototype.$Z=function(){return{start:-ja.a}};fa.prototype.Zma=function(){var x=-(ja.a+ja.e);
return{start:x-ja.d,end:x}};fa.prototype.wv=function(x){var ca=this;this.jE=!0;var ha=ja.a;this.Lp(this.url,this.$Z(),function(oa,la,ka){function qa(){var ra=ca.Wd.YZ();ca.Lp(ca.url,ra,function(ta,va){if(ta)return Object(ma.j)("Error loading central directory: "+ta),x(ta);va=Object(ea.a)(va);if(va.length!==ra.stop-ra.start)return x("Invalid XOD file: Zip central directory data is wrong size! Should be "+(ra.stop-ra.start)+" but is "+va.length);ca.Wd.U3(va);ca.FL=!0;ca.jE=!1;return x(!1)})}if(oa)return Object(ma.j)("Error loading end header: "+
oa),x(oa,la,ka);la=Object(ea.a)(la);if(la.length!==ha)return x("Invalid XOD file: Zip end header data is wrong size!");try{ca.Wd=new ia.a(la)}catch(ra){return x(ra)}ca.Wd.Voa?ca.Lp(ca.url,ca.Zma(),function(ra,ta){if(ra)return Object(ma.j)("Error loading zip64 header: "+ra),x(ra);ta=Object(ea.a)(ta);ca.Wd.tpa(ta);qa()}):qa()})};fa.prototype.x_=function(x){x(Object.keys(this.Wd.kp))};fa.prototype.mQ=function(x,ca){var ha=this;if(this.Wd.LX(x)){var oa=this.Wd.$y(x);if(oa in this.$j){var la=this.Yh[x];
la.iu=this.$j[oa];la.iu.Mn++;la.cancel=la.iu.cancel}else{var ka=this.Wd.gla(x),qa=this.Lp(this.url,ka,function(ta,va){ta?(Object(ma.j)('Error loading part "'+x+'": '+ta),ha.Lp(ha.url,ka,function(xa,Na){if(xa)return ca(xa,x);ha.Y3(Na,ka,oa,x,ca)})):ha.Y3(va,ka,oa,x,ca)}),ra=this.Yh[x];ra&&(ra.A6=!0,ra.cancel=function(){ra.iu.Mn--;0===ra.iu.Mn&&(qa(),delete ha.$j[oa])},this.$j[oa]=new n(oa),ra.iu=this.$j[oa],ra.iu.cancel=ra.cancel)}}else delete this.Yh[x],ca(Error('File not found: "'+x+'"'),x)};fa.prototype.Y3=
function(x,ca,ha,oa,la){if(x.length!==ca.stop-ca.start)la(Error("Part data is wrong size!"),oa);else{do{if(!this.$j[ha])return;oa=this.$j[ha].Mn;for(var ka=ca.As.length,qa=0;qa<ka;++qa){var ra=ca.As[qa];la(!1,ra.ws,x["string"===typeof x?"substring":"subarray"](ra.start,ra.stop),this.Wd.M0(ra.ws));ra.ws in this.Yh&&delete this.Yh[ra.ws]}}while(oa!==this.$j[ha].Mn);delete this.$j[ha]}};fa.DISABLE_RANGE_HEADER=!1;fa.gT=3;return fa}(wa.a);(function(ba){function fa(x,ca,ha){var oa=ba.call(this)||this,
la;for(la in x)oa[la]=x[la];oa.vCa=x;oa.startOffset=ca;oa.endOffset=ha;oa.XX=function(ka,qa,ra,ta){Object(na.isUndefined)(qa.stop)?(qa.start+=oa.endOffset,qa.stop=oa.endOffset):(qa.start+=oa.startOffset,qa.stop+=oa.startOffset);ka=oa.jy(oa.url,qa,oa.bE);return new x.LA(ka,qa,ra,ta)};return oa}Object(pa.c)(fa,ba);return fa})(w);Object(h.a)(w);Object(h.b)(w);sa["default"]=w}}]);}).call(this || window)
