/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
<<<<<<< HEAD
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[11],{435:function(Ba,ua,r){r.r(ua);var pa=r(1);Ba=r(49);var ka=r(374),ma=r(231),fa=r(20),da=window;r=function(){function z(x){var y=this;this.jea=function(f){return f&&("image"===f.type.split("/")[0].toLowerCase()||f.name&&!!f.name.match(/.(jpg|jpeg|png|gif)$/i))};this.file=x;this.wea=new Promise(function(f){return Object(pa.b)(y,void 0,void 0,function(){var e;return Object(pa.d)(this,function(b){switch(b.label){case 0:return this.jea(this.file)?
[4,Object(ma.b)(x)]:[3,2];case 1:e=b.ea(),this.file=fa.p?new Blob([e],{type:x.type}):new File([e],null===x||void 0===x?void 0:x.name,{type:x.type}),b.label=2;case 2:return f(!0),[2]}})})})}z.prototype.getFileData=function(x){var y=this,f=new FileReader;f.onload=function(e){y.trigger(z.Events.DOCUMENT_LOADING_PROGRESS,[e.loaded,e.loaded]);x(new Uint8Array(e.target.result))};f.onprogress=function(e){e.lengthComputable&&y.trigger(z.Events.DOCUMENT_LOADING_PROGRESS,[e.loaded,0<e.total?e.total:0])};f.readAsArrayBuffer(this.file)};
z.prototype.getFile=function(){return Object(pa.b)(this,void 0,Promise,function(){return Object(pa.d)(this,function(x){switch(x.label){case 0:return[4,this.wea];case 1:return x.ea(),da.utils.isJSWorker?[2,this.file.path]:[2,this.file]}})})};z.Events={DOCUMENT_LOADING_PROGRESS:"documentLoadingProgress"};return z}();Object(Ba.a)(r);Object(ka.a)(r);Object(ka.b)(r);ua["default"]=r}}]);}).call(this || window)
=======
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[9],{459:function(Ba,wa,r){r.r(wa);var oa=r(0);Ba=r(48);var na=r(393),ma=r(223),fa=r(20),da=window;r=function(){function aa(w){var y=this;this.Vga=function(h){return h&&("image"===h.type.split("/")[0].toLowerCase()||h.name&&!!h.name.match(/.(jpg|jpeg|png|gif)$/i))};this.file=w;this.iha=new Promise(function(h){return Object(oa.b)(y,void 0,void 0,function(){var a;return Object(oa.d)(this,function(b){switch(b.label){case 0:return this.Vga(this.file)?
[4,Object(ma.b)(w)]:[3,2];case 1:a=b.ca(),this.file=fa.q?new Blob([a],{type:w.type}):new File([a],null===w||void 0===w?void 0:w.name,{type:w.type}),b.label=2;case 2:return h(!0),[2]}})})})}aa.prototype.getFileData=function(w){var y=this,h=new FileReader;h.onload=function(a){y.trigger(aa.Events.DOCUMENT_LOADING_PROGRESS,[a.loaded,a.loaded]);w(new Uint8Array(a.target.result))};h.onprogress=function(a){a.lengthComputable&&y.trigger(aa.Events.DOCUMENT_LOADING_PROGRESS,[a.loaded,0<a.total?a.total:0])};
h.readAsArrayBuffer(this.file)};aa.prototype.getFile=function(){return Object(oa.b)(this,void 0,Promise,function(){return Object(oa.d)(this,function(w){switch(w.label){case 0:return[4,this.iha];case 1:return w.ca(),da.utils.isJSWorker?[2,this.file.path]:[2,this.file]}})})};aa.Events={DOCUMENT_LOADING_PROGRESS:"documentLoadingProgress"};return aa}();Object(Ba.a)(r);Object(na.a)(r);Object(na.b)(r);wa["default"]=r}}]);}).call(this || window)
>>>>>>> 161efc3... Update lib to 8.10
