/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
<<<<<<< HEAD
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[10],{434:function(Ba,ua,r){r.r(ua);var pa=r(1),ka=r(2),ma=r(149);Ba=r(94);var fa=r(246);r=r(374);var da=window;Ba=function(z){function x(y,f,e){f=z.call(this,y,f,e)||this;if(y.name&&"xod"!==y.name.toLowerCase().split(".").pop())throw Error("Not an XOD file");if(!da.FileReader||!da.File||!da.Blob)throw Error("File API is not supported in this browser");f.file=y;f.nB=[];f.UH=0;return f}Object(pa.c)(x,z);x.prototype.GK=function(y,f,
e){var b=this,a=new FileReader;a.onloadend=function(h){if(0<b.nB.length){var n=b.nB.shift();n.Lha.readAsBinaryString(n.file)}else b.UH--;if(a.error){h=a.error;if(h.code===h.ABORT_ERR){Object(ka.j)("Request for chunk "+f.start+"-"+f.stop+" was aborted");return}return e(h)}if(h=a.content||h.target.result)return e(!1,h);Object(ka.j)("No data was returned from FileReader.")};f&&(y=(y.slice||y.webkitSlice||y.mozSlice||y.lpa).call(y,f.start,f.stop));0===b.nB.length&&50>b.UH?(a.readAsBinaryString(y),b.UH++):
b.nB.push({Lha:a,file:y});return function(){a.abort()}};x.prototype.qt=function(y){var f=this;f.jB=!0;var e=ma.a;f.GK(f.file,{start:-e,stop:f.file.size},function(b,a){if(b)return Object(ka.j)("Error loading end header: %s "+b),y(b);if(a.length!==e)throw Error("Zip end header data is wrong size!");f.Zd=new fa.a(a);var h=f.Zd.wT();f.GK(f.file,h,function(n,aa){if(n)return Object(ka.j)("Error loading central directory: %s "+n),y(n);if(aa.length!==h.stop-h.start)throw Error("Zip central directory data is wrong size!");
f.Zd.uX(aa);f.GH=!0;f.jB=!1;return y(!1)})})};x.prototype.DL=function(y,f){var e=this,b=e.Zh[y];if(e.Zd.HR(y)){var a=e.Zd.uw(y),h=e.GK(e.file,a,function(n,aa){delete e.Zh[y];if(n)return Object(ka.j)('Error loading part "%s": %s, '+y+", "+n),f(n);if(aa.length!==a.stop-a.start)throw Error("Part data is wrong size!");f(!1,y,aa,e.Zd.$U(y))});b.DZ=!0;b.cancel=h}else f(Error('File not found: "'+y+'"'),y)};return x}(Ba.a);Object(r.a)(Ba);Object(r.b)(Ba);ua["default"]=Ba}}]);}).call(this || window)
=======
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[8],{458:function(Ba,wa,r){r.r(wa);var oa=r(0),na=r(2),ma=r(157);Ba=r(100);var fa=r(261);r=r(393);var da=window;Ba=function(aa){function w(y,h,a){h=aa.call(this,y,h,a)||this;if(y.name&&"xod"!==y.name.toLowerCase().split(".").pop())throw Error("Not an XOD file");if(!da.FileReader||!da.File||!da.Blob)throw Error("File API is not supported in this browser");h.file=y;h.ZB=[];h.WI=0;return h}Object(oa.c)(w,aa);w.prototype.NL=function(y,
h,a){var b=this,e=new FileReader;e.onloadend=function(f){if(0<b.ZB.length){var n=b.ZB.shift();n.zka.readAsBinaryString(n.file)}else b.WI--;if(e.error){f=e.error;if(f.code===f.ABORT_ERR){Object(na.j)("Request for chunk "+h.start+"-"+h.stop+" was aborted");return}return a(f)}if(f=e.content||f.target.result)return a(!1,f);Object(na.j)("No data was returned from FileReader.")};h&&(y=(y.slice||y.webkitSlice||y.mozSlice||y.Csa).call(y,h.start,h.stop));0===b.ZB.length&&50>b.WI?(e.readAsBinaryString(y),b.WI++):
b.ZB.push({zka:e,file:y});return function(){e.abort()}};w.prototype.Xt=function(y){var h=this;h.VB=!0;var a=ma.a;h.NL(h.file,{start:-a,stop:h.file.size},function(b,e){if(b)return Object(na.j)("Error loading end header: %s "+b),y(b);if(e.length!==a)throw Error("Zip end header data is wrong size!");h.Bd=new fa.a(e);var f=h.Bd.mV();h.NL(h.file,f,function(n,z){if(n)return Object(na.j)("Error loading central directory: %s "+n),y(n);if(z.length!==f.stop-f.start)throw Error("Zip central directory data is wrong size!");
h.Bd.rZ(z);h.HI=!0;h.VB=!1;return y(!1)})})};w.prototype.NM=function(y,h){var a=this,b=a.vh[y];if(a.Bd.nT(y)){var e=a.Bd.hx(y),f=a.NL(a.file,e,function(n,z){delete a.vh[y];if(n)return Object(na.j)('Error loading part "%s": %s, '+y+", "+n),h(n);if(z.length!==e.stop-e.start)throw Error("Part data is wrong size!");h(!1,y,z,a.Bd.RW(y))});b.G0=!0;b.cancel=f}else h(Error('File not found: "'+y+'"'),y)};return w}(Ba.a);Object(r.a)(Ba);Object(r.b)(Ba);wa["default"]=Ba}}]);}).call(this || window)
>>>>>>> 161efc3... Update lib to 8.10
