/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[9],{528:function(wa,sa,h){function pa(ca){ca.Oa();ca.advance();var ha=ca.current.textContent;ca.mb();return ha}function na(ca){var ha=[];for(ca.Oa();ca.advance();){var oa=ca.Sa();"field"===oa?ha.push(String(ca.ha("name"))):Object(b.j)("unrecognised field list element: "+oa)}ca.mb();return ha}function ma(ca,ha){return ha?"false"!==ca:"true"===ca}function ja(ca,ha){var oa=ca.Sa();switch(oa){case "javascript":return{name:"JavaScript",
javascript:ca.current.textContent};case "uri":return{name:"URI",uri:ca.ha("uri")};case "goto":oa=null;ca.Oa();if(ca.advance()){var la=ca.ha("fit");oa={page:ca.ha("page"),fit:la};if("0"===oa.page)Object(b.j)("null page encountered in dest");else switch(ha=ha(Number(oa.page)),la){case "Fit":case "FitB":break;case "FitH":case "FitBH":oa.top=ha.ta({x:0,y:ca.ha("top")||0}).y;break;case "FitV":case "FitBV":oa.left=ha.ta({x:ca.ha("left")||0,y:0}).x;break;case "FitR":la=ha.ta({x:ca.ha("left")||0,y:ca.ha("top")||
0});ha=ha.ta({x:ca.ha("right")||0,y:ca.ha("bottom")||0});ha=new aa.d(la.x,la.y,ha.x,ha.y);oa.top=ha.y1;oa.left=ha.x1;oa.bottom=ha.y2;oa.right=ha.x2;break;case "XYZ":la=ha.ta({x:ca.ha("left")||0,y:ca.ha("top")||0});oa.top=la.y;oa.left=la.x;oa.zoom=ca.ha("zoom")||0;break;default:Object(b.j)("unknown dest fit: "+la)}oa={name:"GoTo",dest:oa}}else Object(b.j)("missing dest in GoTo action");ca.mb();return oa;case "submit-form":oa={name:"SubmitForm",url:ca.ha("url"),format:ca.ha("format"),method:ca.ha("method")||
"POST",exclude:ma(ca.ha("exclude"),!1)};ha=ca.ha("flags");oa.flags=ha?ha.split(" "):[];for(ca.Oa();ca.advance();)switch(ha=ca.Sa(),ha){case "fields":oa.fields=na(ca);break;default:Object(b.j)("unrecognised submit-form child: "+ha)}ca.mb();return oa;case "reset-form":oa={name:"ResetForm",exclude:ma(ca.ha("exclude"),!1)};for(ca.Oa();ca.advance();)switch(ha=ca.Sa(),ha){case "fields":oa.fields=na(ca);break;default:Object(b.j)("unrecognised reset-form child: "+ha)}ca.mb();return oa;case "hide":oa={name:"Hide",
hide:ma(ca.ha("hide"),!0)};for(ca.Oa();ca.advance();)switch(ha=ca.Sa(),ha){case "fields":oa.fields=na(ca);break;default:Object(b.j)("unrecognised hide child: "+ha)}ca.mb();return oa;case "named":return{name:"Named",action:ca.ha("name")};default:Object(b.j)("Encountered unexpected action type: "+oa)}return null}function ia(ca,ha,oa){var la={};for(ca.Oa();ca.advance();){var ka=ca.Sa();switch(ka){case "action":ka=ca.ha("trigger");if(ha?-1!==ha.indexOf(ka):1){la[ka]=[];for(ca.Oa();ca.advance();){var qa=
ja(ca,oa);Object(n.isNull)(qa)||la[ka].push(qa)}ca.mb()}else Object(b.j)("encountered unexpected trigger on field: "+ka);break;default:Object(b.j)("encountered unknown action child: "+ka)}}ca.mb();return la}function ea(ca){return new w.a(ca.ha("r")||0,ca.ha("g")||0,ca.ha("b")||0,ca.ha("a")||1)}function y(ca,ha){var oa=ca.ha("name"),la=ca.ha("type")||"Type1",ka=ca.ha("size"),qa=ha.ta({x:0,y:0});ka=ha.ta({x:Number(ka),y:0});ha=qa.x-ka.x;qa=qa.y-ka.y;oa={name:oa,type:la,size:Math.sqrt(ha*ha+qa*qa)||
0,strokeColor:[0,0,0],fillColor:[0,0,0]};for(ca.Oa();ca.advance();)switch(la=ca.Sa(),la){case "stroke-color":oa.strokeColor=ea(ca);break;case "fill-color":oa.fillColor=ea(ca);break;default:Object(b.j)("unrecognised font child: "+la)}ca.mb();return oa}function z(ca){var ha=[];for(ca.Oa();ca.advance();){var oa=ca.Sa();switch(oa){case "option":oa=ha;var la=oa.push;var ka=ca;ka={value:ka.ha("value"),displayValue:ka.ha("display-value")||void 0};la.call(oa,ka);break;default:Object(b.j)("unrecognised options child: "+
oa)}}ca.mb();return ha}function f(ca,ha){var oa=ca.ha("name"),la={type:ca.ha("type"),quadding:ca.ha("quadding")||"Left-justified",maxLen:ca.ha("max-len")||-1},ka=ca.ha("flags");Object(n.isString)(ka)&&(la.flags=ka.split(" "));for(ca.Oa();ca.advance();)switch(ka=ca.Sa(),ka){case "actions":la.actions=ia(ca,["C","F","K","V"],function(){return ha});break;case "default-value":la.defaultValue=pa(ca);break;case "font":la.font=y(ca,ha);break;case "options":la.options=z(ca);break;default:Object(b.j)("unknown field child: "+
ka)}ca.mb();return new window.da.Annotations.ia.ra(oa,la)}function e(ca,ha){switch(ca.type){case "Tx":try{if(Object(fa.c)(ca.actions))return new r.a.DatePickerWidgetAnnotation(ca,ha)}catch(oa){Object(b.j)(oa)}return new r.a.TextWidgetAnnotation(ca,ha);case "Ch":return ca.flags.get(x.WidgetFlags.COMBO)?new r.a.ChoiceWidgetAnnotation(ca,ha):new r.a.ListWidgetAnnotation(ca,ha);case "Btn":return ca.flags.get(x.WidgetFlags.PUSH_BUTTON)?new r.a.PushButtonWidgetAnnotation(ca,ha):ca.flags.get(x.WidgetFlags.RADIO)?
new r.a.RadioButtonWidgetAnnotation(ca,ha):new r.a.CheckButtonWidgetAnnotation(ca,ha);case "Sig":return new r.a.SignatureWidgetAnnotation(ca,ha);default:Object(b.j)("Unrecognised field type: "+ca.type)}return null}function a(ca,ha,oa,la){var ka=[],qa={};ca.Oa();var ra=[],ta={},va=[];Object(ba.a)(function(){if(ca.advance()){var xa=ca.Sa();switch(xa){case "calculation-order":ra="calculation-order"===ca.Sa()?na(ca):[];break;case "document-actions":ta=ia(ca,["Init","Open"],ha);break;case "pages":xa=[];
for(ca.Oa();ca.advance();){var Na=ca.Sa();switch(Na){case "page":Na=xa;var Ia=Na.push,Da=ca,Oa=ha,Ca={number:Da.ha("number")};for(Da.Oa();Da.advance();){var Ma=Da.Sa();switch(Ma){case "actions":Ca.actions=ia(Da,["O","C"],Oa);break;default:Object(b.j)("unrecognised page child: "+Ma)}}Da.mb();Ia.call(Na,Ca);break;default:Object(b.j)("unrecognised page child: "+Na)}}ca.mb();va=xa;break;case "field":Na=f(ca,ha(1));qa[Na.name]=Na;break;case "widget":xa={border:{style:"Solid",width:1},backgroundColor:[],
fieldName:ca.ha("field"),page:ca.ha("page"),index:ca.ha("index")||0,rotation:ca.ha("rotation")||0,flags:[],isImporting:!0};(Na=ca.ha("appearance"))&&(xa.appearance=Na);(Na=ca.ha("flags"))&&(xa.flags=Na.split(" "));for(ca.Oa();ca.advance();)switch(Na=ca.Sa(),Na){case "rect":Ia=ca;Da=ha(Number(xa.page));Na=Da.ta({x:Ia.ha("x1")||0,y:Ia.ha("y1")||0});Ia=Da.ta({x:Ia.ha("x2")||0,y:Ia.ha("y2")||0});Na=new aa.d(Na.x,Na.y,Ia.x,Ia.y);Na.normalize();xa.rect={x1:Na.x1,y1:Na.y1,x2:Na.x2,y2:Na.y2};break;case "border":Na=
ca;Ia={style:Na.ha("style")||"Solid",width:Na.ha("width")||1,color:[0,0,0]};for(Na.Oa();Na.advance();)switch(Da=Na.Sa(),Da){case "color":Ia.color=ea(Na);break;default:Object(b.j)("unrecognised border child: "+Da)}Na.mb();xa.border=Ia;break;case "background-color":xa.backgroundColor=ea(ca);break;case "actions":xa.actions=ia(ca,"E X D U Fo Bl PO PC PV PI".split(" "),ha);break;case "appearances":Na=ca;Ia=Object(fa.b)(xa,"appearances");for(Na.Oa();Na.advance();)if(Da=Na.Sa(),"appearance"===Da){Da=Na.ha("name");
Oa=Object(fa.b)(Ia,Da);Da=Na;for(Da.Oa();Da.advance();)switch(Ca=Da.Sa(),Ca){case "Normal":Object(fa.b)(Oa,"Normal").data=Da.current.textContent;break;default:Object(b.j)("unexpected appearance state: ",Ca)}Da.mb()}else Object(b.j)("unexpected appearances child: "+Da);Na.mb();break;case "extra":Na=ca;Ia=ha;Da={};for(Na.Oa();Na.advance();)switch(Oa=Na.Sa(),Oa){case "font":Da.font=y(Na,Ia(1));break;default:Object(b.j)("unrecognised extra child: "+Oa)}Na.mb();Na=Da;Na.font&&(xa.font=Na.font);break;case "captions":Ia=
ca;Na={};(Da=Ia.ha("Normal"))&&(Na.Normal=Da);(Da=Ia.ha("Rollover"))&&(Na.Rollover=Da);(Ia=Ia.ha("Down"))&&(Na.Down=Ia);xa.captions=Na;break;default:Object(b.j)("unrecognised widget child: "+Na)}ca.mb();(Na=qa[xa.fieldName])?(xa=e(Na,xa),ka.push(xa)):Object(b.j)("ignoring widget with no corresponding field data: "+xa.fieldName);break;default:Object(b.j)("Unknown element encountered in PDFInfo: "+xa)}return!0}return!1},function(){ca.mb();oa({calculationOrder:ra,widgets:ka,fields:qa,documentActions:ta,
pages:va,custom:[]})},la)}h.r(sa);h.d(sa,"parse",function(){return a});var b=h(3),n=h(1);h.n(n);var r=h(137),aa=h(4),w=h(9),ba=h(23),fa=h(120),x=h(18)}}]);}).call(this || window)
