/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){/*
 Pikaday

 Copyright © 2014 David Bushell | BSD & MIT license | https://github.com/Pikaday/Pikaday
*/
<<<<<<< HEAD
(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[19],{433:function(Ba,ua){!function(r,pa){if("object"==typeof ua){try{var ka=require("moment")}catch(ma){}Ba.exports=pa(ka)}else"function"==typeof define&&define.amd?define(function(ma){try{ka=ma("moment")}catch(fa){}return pa(ka)}):r.Pikaday=pa(r.moment)}(this,function(r){function pa(ha){var la=this,na=la.config(ha);la._onMouseDown=function(qa){if(la._v){var ra=(qa=qa||window.event).target||qa.srcElement;if(ra)if(n(ra,"is-disabled")||
(!n(ra,"pika-button")||n(ra,"is-empty")||n(ra.parentNode,"is-disabled")?n(ra,"pika-prev")?la.prevMonth():n(ra,"pika-next")?la.nextMonth():n(ra,"pika-set-today")&&(la.setDate(new Date),la.hide()):(la.setDate(new Date(ra.getAttribute("data-pika-year"),ra.getAttribute("data-pika-month"),ra.getAttribute("data-pika-day"))),na.bound&&ca(function(){la.hide();na.blurFieldOnSelect&&na.field&&na.field.blur()},100))),n(ra,"pika-select"))la._c=!0;else{if(!qa.preventDefault)return qa.returnValue=!1,!1;qa.preventDefault()}}};
la._onChange=function(qa){var ra=(qa=qa||window.event).target||qa.srcElement;ra&&(n(ra,"pika-select-month")?la.gotoMonth(ra.value):n(ra,"pika-select-year")&&la.gotoYear(ra.value))};la._onKeyChange=function(qa){if(qa=qa||window.event,la.isVisible())switch(qa.keyCode){case 13:case 27:na.field&&na.field.blur();break;case 37:la.adjustDate("subtract",1);break;case 38:la.adjustDate("subtract",7);break;case 39:la.adjustDate("add",1);break;case 40:la.adjustDate("add",7);break;case 8:case 46:la.setDate(null)}};
la._parseFieldValue=function(){if(na.parse)return na.parse(na.field.value,na.format);if(ea){var qa=r(na.field.value,na.format,na.formatStrict);return qa&&qa.isValid()?qa.toDate():null}return new Date(Date.parse(na.field.value))};la._onInputChange=function(qa){var ra;qa.firedBy!==la&&(ra=la._parseFieldValue(),e(ra)&&la.setDate(ra),la._v||la.show())};la._onInputFocus=function(){la.show()};la._onInputClick=function(){la.show()};la._onInputBlur=function(){var qa=ba.activeElement;do if(n(qa,"pika-single"))return;
while(qa=qa.parentNode);la._c||(la._b=ca(function(){la.hide()},50));la._c=!1};la._onClick=function(qa){var ra=(qa=qa||window.event).target||qa.srcElement;if(qa=ra){!ja&&n(ra,"pika-select")&&(ra.onchange||(ra.setAttribute("onchange","return;"),w(ra,"change",la._onChange)));do if(n(qa,"pika-single")||qa===na.trigger)return;while(qa=qa.parentNode);la._v&&ra!==na.trigger&&qa!==na.trigger&&la.hide()}};la.el=ba.createElement("div");la.el.className="pika-single"+(na.isRTL?" is-rtl":"")+(na.theme?" "+na.theme:
"");w(la.el,"mousedown",la._onMouseDown,!0);w(la.el,"touchend",la._onMouseDown,!0);w(la.el,"change",la._onChange);na.keyboardInput&&w(ba,"keydown",la._onKeyChange);na.field&&(na.container?na.container.appendChild(la.el):na.bound?ba.body.appendChild(la.el):na.field.parentNode.insertBefore(la.el,na.field.nextSibling),w(na.field,"change",la._onInputChange),na.defaultDate||(na.defaultDate=la._parseFieldValue(),na.setDefaultDate=!0));ha=na.defaultDate;e(ha)?na.setDefaultDate?la.setDate(ha,!0):la.gotoDate(ha):
la.gotoDate(new Date);na.bound?(this.hide(),la.el.className+=" is-bound",w(na.trigger,"click",la._onInputClick),w(na.trigger,"focus",la._onInputFocus),w(na.trigger,"blur",la._onInputBlur)):this.show()}function ka(ha,la,na){return'<table cellpadding="0" cellspacing="0" class="pika-table" role="grid" aria-labelledby="'+na+'">'+function(qa){var ra,ta=[];qa.showWeekNumber&&ta.push("<th></th>");for(ra=0;7>ra;ra++)ta.push('<th scope="col"><abbr title="'+fa(qa,ra)+'">'+fa(qa,ra,!0)+"</abbr></th>");return"<thead><tr>"+
(qa.isRTL?ta.reverse():ta).join("")+"</tr></thead>"}(ha)+("<tbody>"+la.join("")+"</tbody>")+(ha.showTodayButton?function(qa){var ra=[];return ra.push('<td colspan="'+(qa.showWeekNumber?"8":"7")+'"><button class="pika-set-today">'+qa.i18n.today+"</button></td>"),"<tfoot>"+(qa.isRTL?ra.reverse():ra).join("")+"</tfoot>"}(ha):"")+"</table>"}function ma(ha,la,na,qa,ra,ta){var va,oa,wa=ha._o,Da=na===wa.minYear,Ha=na===wa.maxYear,La='<div id="'+ta+'" class="pika-title" role="heading" aria-live="assertive">',
Ca=!0,Ka=!0;var Ra=[];for(ta=0;12>ta;ta++)Ra.push('<option value="'+(na===ra?ta-la:12+ta-la)+'"'+(ta===qa?' selected="selected"':"")+(Da&&ta<wa.minMonth||Ha&&ta>wa.maxMonth?' disabled="disabled"':"")+">"+wa.i18n.months[ta]+"</option>");ra='<div class="pika-label">'+wa.i18n.months[qa]+'<select class="pika-select pika-select-month" tabindex="-1">'+Ra.join("")+"</select></div>";b(wa.yearRange)?(ta=wa.yearRange[0],va=wa.yearRange[1]+1):(ta=na-wa.yearRange,va=1+na+wa.yearRange);for(Ra=[];ta<va&&ta<=wa.maxYear;ta++)ta>=
wa.minYear&&Ra.push('<option value="'+ta+'"'+(ta===na?' selected="selected"':"")+">"+ta+"</option>");return oa='<div class="pika-label">'+na+wa.yearSuffix+'<select class="pika-select pika-select-year" tabindex="-1">'+Ra.join("")+"</select></div>",wa.showMonthAfterYear?La+=oa+ra:La+=ra+oa,Da&&(0===qa||wa.minMonth>=qa)&&(Ca=!1),Ha&&(11===qa||wa.maxMonth<=qa)&&(Ka=!1),0===la&&(La+='<button class="pika-prev'+(Ca?"":" is-disabled")+'" type="button">'+wa.i18n.previousMonth+"</button>"),la===ha._o.numberOfMonths-
1&&(La+='<button class="pika-next'+(Ka?"":" is-disabled")+'" type="button">'+wa.i18n.nextMonth+"</button>"),La+"</div>"}function fa(ha,la,na){for(la+=ha.firstDay;7<=la;)la-=7;return na?ha.i18n.weekdaysShort[la]:ha.i18n.weekdays[la]}function da(ha){return 0>ha.month&&(ha.year-=Math.ceil(Math.abs(ha.month)/12),ha.month+=12),11<ha.month&&(ha.year+=Math.floor(Math.abs(ha.month)/12),ha.month-=12),ha}function z(ha,la,na){var qa;ba.createEvent?((qa=ba.createEvent("HTMLEvents")).initEvent(la,!0,!1),qa=x(qa,
na),ha.dispatchEvent(qa)):ba.createEventObject&&(qa=ba.createEventObject(),qa=x(qa,na),ha.fireEvent("on"+la,qa))}function x(ha,la,na){var qa,ra;for(qa in la)(ra=void 0!==ha[qa])&&"object"==typeof la[qa]&&null!==la[qa]&&void 0===la[qa].nodeName?e(la[qa])?na&&(ha[qa]=new Date(la[qa].getTime())):b(la[qa])?na&&(ha[qa]=la[qa].slice(0)):ha[qa]=x({},la[qa],na):!na&&ra||(ha[qa]=la[qa]);return ha}function y(ha){e(ha)&&ha.setHours(0,0,0,0)}function f(ha,la){return[31,0==ha%4&&0!=ha%100||0==ha%400?29:28,31,
30,31,30,31,31,30,31,30,31][la]}function e(ha){return/Date/.test(Object.prototype.toString.call(ha))&&!isNaN(ha.getTime())}function b(ha){return/Array/.test(Object.prototype.toString.call(ha))}function a(ha,la){var na;ha.className=(na=(" "+ha.className+" ").replace(" "+la+" "," ")).trim?na.trim():na.replace(/^\s+|\s+$/g,"")}function h(ha,la){n(ha,la)||(ha.className=""===ha.className?la:ha.className+" "+la)}function n(ha,la){return-1!==(" "+ha.className+" ").indexOf(" "+la+" ")}function aa(ha,la,na,
qa){ja?ha.removeEventListener(la,na,!!qa):ha.detachEvent("on"+la,na)}function w(ha,la,na,qa){ja?ha.addEventListener(la,na,!!qa):ha.attachEvent("on"+la,na)}var ea="function"==typeof r,ja=!!window.addEventListener,ba=window.document,ca=window.setTimeout,ia={field:null,bound:void 0,ariaLabel:"Use the arrow keys to pick a date",position:"bottom left",reposition:!0,format:"YYYY-MM-DD",toString:null,parse:null,defaultDate:null,setDefaultDate:!1,firstDay:0,firstWeekOfYearMinDays:4,formatStrict:!1,minDate:null,
maxDate:null,yearRange:10,showWeekNumber:!1,showTodayButton:!1,pickWholeWeek:!1,minYear:0,maxYear:9999,minMonth:void 0,maxMonth:void 0,startRange:null,endRange:null,isRTL:!1,yearSuffix:"",showMonthAfterYear:!1,showDaysInNextAndPreviousMonths:!1,enableSelectionDaysInNextAndPreviousMonths:!1,numberOfMonths:1,mainCalendar:"left",container:void 0,blurFieldOnSelect:!0,i18n:{previousMonth:"Previous Month",nextMonth:"Next Month",today:"Today",months:"January February March April May June July August September October November December".split(" "),
weekdays:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),weekdaysShort:"Sun Mon Tue Wed Thu Fri Sat".split(" ")},theme:null,events:[],onSelect:null,onOpen:null,onClose:null,onDraw:null,keyboardInput:!0};return pa.prototype={config:function(ha){this._o||(this._o=x({},ia,!0));ha=x(this._o,ha,!0);ha.isRTL=!!ha.isRTL;ha.field=ha.field&&ha.field.nodeName?ha.field:null;ha.theme="string"==typeof ha.theme&&ha.theme?ha.theme:null;ha.bound=!!(void 0!==ha.bound?ha.field&&ha.bound:ha.field);
ha.trigger=ha.trigger&&ha.trigger.nodeName?ha.trigger:ha.field;ha.disableWeekends=!!ha.disableWeekends;ha.disableDayFn="function"==typeof ha.disableDayFn?ha.disableDayFn:null;var la=parseInt(ha.numberOfMonths,10)||1;(ha.numberOfMonths=4<la?4:la,e(ha.minDate)||(ha.minDate=!1),e(ha.maxDate)||(ha.maxDate=!1),ha.minDate&&ha.maxDate&&ha.maxDate<ha.minDate&&(ha.maxDate=ha.minDate=!1),ha.minDate&&this.setMinDate(ha.minDate),ha.maxDate&&this.setMaxDate(ha.maxDate),b(ha.yearRange))?(la=(new Date).getFullYear()-
10,ha.yearRange[0]=parseInt(ha.yearRange[0],10)||la,ha.yearRange[1]=parseInt(ha.yearRange[1],10)||la):(ha.yearRange=Math.abs(parseInt(ha.yearRange,10))||ia.yearRange,100<ha.yearRange&&(ha.yearRange=100));return ha},toString:function(ha){return ha=ha||this._o.format,e(this._d)?this._o.toString?this._o.toString(this._d,ha):ea?r(this._d).format(ha):this._d.toDateString():""},getMoment:function(){return ea?r(this._d):null},setMoment:function(ha,la){ea&&r.isMoment(ha)&&this.setDate(ha.toDate(),la)},getDate:function(){return e(this._d)?
new Date(this._d.getTime()):null},setDate:function(ha,la){if(!ha)return this._d=null,this._o.field&&(this._o.field.value="",z(this._o.field,"change",{firedBy:this})),this.draw();if("string"==typeof ha&&(ha=new Date(Date.parse(ha))),e(ha)){var na=this._o.minDate,qa=this._o.maxDate;e(na)&&ha<na?ha=na:e(qa)&&ha>qa&&(ha=qa);this._d=new Date(ha.getTime());this.gotoDate(this._d);this._o.field&&(this._o.field.value=this.toString(),z(this._o.field,"change",{firedBy:this}));la||"function"!=typeof this._o.onSelect||
this._o.onSelect.call(this,this.getDate())}},clear:function(){this.setDate(null)},gotoDate:function(ha){var la=!0;if(e(ha)){if(this.calendars){la=new Date(this.calendars[0].year,this.calendars[0].month,1);var na=new Date(this.calendars[this.calendars.length-1].year,this.calendars[this.calendars.length-1].month,1),qa=ha.getTime();na.setMonth(na.getMonth()+1);na.setDate(na.getDate()-1);la=qa<la.getTime()||na.getTime()<qa}la&&(this.calendars=[{month:ha.getMonth(),year:ha.getFullYear()}],"right"===this._o.mainCalendar&&
(this.calendars[0].month+=1-this._o.numberOfMonths));this.adjustCalendars()}},adjustDate:function(ha,la){var na,qa=this.getDate()||new Date;la=864E5*parseInt(la);"add"===ha?na=new Date(qa.valueOf()+la):"subtract"===ha&&(na=new Date(qa.valueOf()-la));this.setDate(na)},adjustCalendars:function(){this.calendars[0]=da(this.calendars[0]);for(var ha=1;ha<this._o.numberOfMonths;ha++)this.calendars[ha]=da({month:this.calendars[0].month+ha,year:this.calendars[0].year});this.draw()},gotoToday:function(){this.gotoDate(new Date)},
gotoMonth:function(ha){isNaN(ha)||(this.calendars[0].month=parseInt(ha,10),this.adjustCalendars())},nextMonth:function(){this.calendars[0].month++;this.adjustCalendars()},prevMonth:function(){this.calendars[0].month--;this.adjustCalendars()},gotoYear:function(ha){isNaN(ha)||(this.calendars[0].year=parseInt(ha,10),this.adjustCalendars())},setMinDate:function(ha){ha instanceof Date?(y(ha),this._o.minDate=ha,this._o.minYear=ha.getFullYear(),this._o.minMonth=ha.getMonth()):(this._o.minDate=ia.minDate,
this._o.minYear=ia.minYear,this._o.minMonth=ia.minMonth,this._o.startRange=ia.startRange);this.draw()},setMaxDate:function(ha){ha instanceof Date?(y(ha),this._o.maxDate=ha,this._o.maxYear=ha.getFullYear(),this._o.maxMonth=ha.getMonth()):(this._o.maxDate=ia.maxDate,this._o.maxYear=ia.maxYear,this._o.maxMonth=ia.maxMonth,this._o.endRange=ia.endRange);this.draw()},setStartRange:function(ha){this._o.startRange=ha},setEndRange:function(ha){this._o.endRange=ha},draw:function(ha){if(this._v||ha){var la=
this._o;var na=la.minYear;var qa=la.maxYear,ra=la.minMonth,ta=la.maxMonth;ha="";this._y<=na&&(this._y=na,!isNaN(ra)&&this._m<ra&&(this._m=ra));this._y>=qa&&(this._y=qa,!isNaN(ta)&&this._m>ta&&(this._m=ta));for(qa=0;qa<la.numberOfMonths;qa++)na="pika-title-"+Math.random().toString(36).replace(/[^a-z]+/g,"").substr(0,2),ha+='<div class="pika-lendar">'+ma(this,qa,this.calendars[qa].year,this.calendars[qa].month,this.calendars[0].year,na)+this.render(this.calendars[qa].year,this.calendars[qa].month,na)+
"</div>";this.el.innerHTML=ha;la.bound&&"hidden"!==la.field.type&&ca(function(){la.trigger.focus()},1);"function"==typeof this._o.onDraw&&this._o.onDraw(this);la.bound&&la.field.setAttribute("aria-label",la.ariaLabel)}},adjustPosition:function(){var ha,la,na,qa,ra,ta,va,oa,wa;if(!this._o.container){if(this.el.style.position="absolute",la=ha=this._o.trigger,na=this.el.offsetWidth,qa=this.el.offsetHeight,ra=window.innerWidth||ba.documentElement.clientWidth,ta=window.innerHeight||ba.documentElement.clientHeight,
va=window.pageYOffset||ba.body.scrollTop||ba.documentElement.scrollTop,oa=!0,wa=!0,"function"==typeof ha.getBoundingClientRect){var Da=(la=ha.getBoundingClientRect()).left+window.pageXOffset;var Ha=la.bottom+window.pageYOffset}else for(Da=la.offsetLeft,Ha=la.offsetTop+la.offsetHeight;la=la.offsetParent;)Da+=la.offsetLeft,Ha+=la.offsetTop;(this._o.reposition&&Da+na>ra||-1<this._o.position.indexOf("right")&&0<Da-na+ha.offsetWidth)&&(Da=Da-na+ha.offsetWidth,oa=!1);(this._o.reposition&&Ha+qa>ta+va||-1<
this._o.position.indexOf("top")&&0<Ha-qa-ha.offsetHeight)&&(Ha=Ha-qa-ha.offsetHeight,wa=!1);0>Da&&(Da=0);0>Ha&&(Ha=0);this.el.style.left=Da+"px";this.el.style.top=Ha+"px";h(this.el,oa?"left-aligned":"right-aligned");h(this.el,wa?"bottom-aligned":"top-aligned");a(this.el,oa?"right-aligned":"left-aligned");a(this.el,wa?"top-aligned":"bottom-aligned")}},render:function(ha,la,na){var qa=this._o,ra=new Date,ta=f(ha,la),va=(new Date(ha,la,1)).getDay(),oa=[],wa=[];y(ra);0<qa.firstDay&&0>(va-=qa.firstDay)&&
(va+=7);for(var Da=0===la?11:la-1,Ha=11===la?0:la+1,La=0===la?ha-1:ha,Ca=11===la?ha+1:ha,Ka=f(La,Da),Ra=ta+va,Ma=Ra;7<Ma;)Ma-=7;Ra+=7-Ma;for(var Aa=!1,Ja=Ma=0;Ma<Ra;Ma++){var Ia=new Date(ha,la,Ma-va+1),Pa=!!e(this._d)&&Ia.getTime()===this._d.getTime(),Wa=Ia.getTime()===ra.getTime(),Qa=-1!==qa.events.indexOf(Ia.toDateString()),Fa=Ma<va||Ma>=ta+va,Ea=Ma-va+1,Ua=la,Va=ha,Xa=qa.startRange&&qa.startRange.getTime()===Ia.getTime(),cb=qa.endRange&&qa.endRange.getTime()===Ia.getTime(),eb=qa.startRange&&qa.endRange&&
qa.startRange<Ia&&Ia<qa.endRange;Fa&&(Ma<va?(Ea=Ka+Ea,Ua=Da,Va=La):(Ea-=ta,Ua=Ha,Va=Ca));var hb=Pa,kb;!(kb=qa.minDate&&Ia<qa.minDate||qa.maxDate&&Ia>qa.maxDate)&&(kb=qa.disableWeekends)&&(kb=Ia.getDay(),kb=0===kb||6===kb);Fa={day:Ea,month:Ua,year:Va,hasEvent:Qa,isSelected:hb,isToday:Wa,isDisabled:kb||qa.disableDayFn&&qa.disableDayFn(Ia),isEmpty:Fa,isStartRange:Xa,isEndRange:cb,isInRange:eb,showDaysInNextAndPreviousMonths:qa.showDaysInNextAndPreviousMonths,enableSelectionDaysInNextAndPreviousMonths:qa.enableSelectionDaysInNextAndPreviousMonths};
qa.pickWholeWeek&&Pa&&(Aa=!0);Pa=wa;Ia=Pa.push;a:{Xa=Fa;cb=[];eb="false";if(Xa.isEmpty){if(!Xa.showDaysInNextAndPreviousMonths){Fa='<td class="is-empty"></td>';break a}cb.push("is-outside-current-month");Xa.enableSelectionDaysInNextAndPreviousMonths||cb.push("is-selection-disabled")}Fa=(Xa.isDisabled&&cb.push("is-disabled"),Xa.isToday&&cb.push("is-today"),Xa.isSelected&&(cb.push("is-selected"),eb="true"),Xa.hasEvent&&cb.push("has-event"),Xa.isInRange&&cb.push("is-inrange"),Xa.isStartRange&&cb.push("is-startrange"),
Xa.isEndRange&&cb.push("is-endrange"),'<td data-day="'+Xa.day+'" class="'+cb.join(" ")+'" aria-selected="'+eb+'"><button class="pika-button pika-day" type="button" data-pika-year="'+Xa.year+'" data-pika-month="'+Xa.month+'" data-pika-day="'+Xa.day+'">'+Xa.day+"</button></td>")}Ia.call(Pa,Fa);7==++Ja&&(qa.showWeekNumber&&(Ja=wa,Pa=Ja.unshift,Xa=qa.firstWeekOfYearMinDays,Ia=new Date(ha,la,Ma-va),ea?Ia=r(Ia).isoWeek():(Ia.setHours(0,0,0,0),cb=Ia.getDate(),Fa=Xa-1,Ia.setDate(cb+Fa-(Ia.getDay()+7-1)%7),
Xa=new Date(Ia.getFullYear(),0,Xa),Ia=1+Math.round(((Ia.getTime()-Xa.getTime())/864E5-Fa+(Xa.getDay()+7-1)%7)/7)),Pa.call(Ja,'<td class="pika-week">'+Ia+"</td>")),Ja=oa,Pa=Ja.push,wa='<tr class="pika-row'+(qa.pickWholeWeek?" pick-whole-week":"")+(Aa?" is-selected":"")+'">'+(qa.isRTL?wa.reverse():wa).join("")+"</tr>",Pa.call(Ja,wa),wa=[],Ja=0,Aa=!1)}return ka(qa,oa,na)},isVisible:function(){return this._v},show:function(){this.isVisible()||(this._v=!0,this.draw(),a(this.el,"is-hidden"),this._o.bound&&
(w(ba,"click",this._onClick),this.adjustPosition()),"function"==typeof this._o.onOpen&&this._o.onOpen.call(this))},hide:function(){var ha=this._v;!1!==ha&&(this._o.bound&&aa(ba,"click",this._onClick),this._o.container||(this.el.style.position="static",this.el.style.left="auto",this.el.style.top="auto"),h(this.el,"is-hidden"),this._v=!1,void 0!==ha&&"function"==typeof this._o.onClose&&this._o.onClose.call(this))},destroy:function(){var ha=this._o;this.hide();aa(this.el,"mousedown",this._onMouseDown,
!0);aa(this.el,"touchend",this._onMouseDown,!0);aa(this.el,"change",this._onChange);ha.keyboardInput&&aa(ba,"keydown",this._onKeyChange);ha.field&&(aa(ha.field,"change",this._onInputChange),ha.bound&&(aa(ha.trigger,"click",this._onInputClick),aa(ha.trigger,"focus",this._onInputFocus),aa(ha.trigger,"blur",this._onInputBlur)));this.el.parentNode&&this.el.parentNode.removeChild(this.el)}},pa})}}]);}).call(this || window)
=======
(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[17],{457:function(Ba,wa){!function(r,oa){if("object"==typeof wa){try{var na=require("moment")}catch(ma){}Ba.exports=oa(na)}else"function"==typeof define&&define.amd?define(function(ma){try{na=ma("moment")}catch(fa){}return oa(na)}):r.Pikaday=oa(r.moment)}(this,function(r){function oa(ia){var la=this,ka=la.config(ia);la._onMouseDown=function(qa){if(la._v){var pa=(qa=qa||window.event).target||qa.srcElement;if(pa)if(n(pa,"is-disabled")||
(!n(pa,"pika-button")||n(pa,"is-empty")||n(pa.parentNode,"is-disabled")?n(pa,"pika-prev")?la.prevMonth():n(pa,"pika-next")?la.nextMonth():n(pa,"pika-set-today")&&(la.setDate(new Date),la.hide()):(la.setDate(new Date(pa.getAttribute("data-pika-year"),pa.getAttribute("data-pika-month"),pa.getAttribute("data-pika-day"))),ka.bound&&ba(function(){la.hide();ka.blurFieldOnSelect&&ka.field&&ka.field.blur()},100))),n(pa,"pika-select"))la._c=!0;else{if(!qa.preventDefault)return qa.returnValue=!1,!1;qa.preventDefault()}}};
la._onChange=function(qa){var pa=(qa=qa||window.event).target||qa.srcElement;pa&&(n(pa,"pika-select-month")?la.gotoMonth(pa.value):n(pa,"pika-select-year")&&la.gotoYear(pa.value))};la._onKeyChange=function(qa){if(qa=qa||window.event,la.isVisible())switch(qa.keyCode){case 13:case 27:ka.field&&ka.field.blur();break;case 37:la.adjustDate("subtract",1);break;case 38:la.adjustDate("subtract",7);break;case 39:la.adjustDate("add",1);break;case 40:la.adjustDate("add",7);break;case 8:case 46:la.setDate(null)}};
la._parseFieldValue=function(){if(ka.parse)return ka.parse(ka.field.value,ka.format);if(ea){var qa=r(ka.field.value,ka.format,ka.formatStrict);return qa&&qa.isValid()?qa.toDate():null}return new Date(Date.parse(ka.field.value))};la._onInputChange=function(qa){var pa;qa.firedBy!==la&&(pa=la._parseFieldValue(),a(pa)&&la.setDate(pa),la._v||la.show())};la._onInputFocus=function(){la.show()};la._onInputClick=function(){la.show()};la._onInputBlur=function(){var qa=ca.activeElement;do if(n(qa,"pika-single"))return;
while(qa=qa.parentNode);la._c||(la._b=ba(function(){la.hide()},50));la._c=!1};la._onClick=function(qa){var pa=(qa=qa||window.event).target||qa.srcElement;if(qa=pa){!ja&&n(pa,"pika-select")&&(pa.onchange||(pa.setAttribute("onchange","return;"),x(pa,"change",la._onChange)));do if(n(qa,"pika-single")||qa===ka.trigger)return;while(qa=qa.parentNode);la._v&&pa!==ka.trigger&&qa!==ka.trigger&&la.hide()}};la.el=ca.createElement("div");la.el.className="pika-single"+(ka.isRTL?" is-rtl":"")+(ka.theme?" "+ka.theme:
"");x(la.el,"mousedown",la._onMouseDown,!0);x(la.el,"touchend",la._onMouseDown,!0);x(la.el,"change",la._onChange);ka.keyboardInput&&x(ca,"keydown",la._onKeyChange);ka.field&&(ka.container?ka.container.appendChild(la.el):ka.bound?ca.body.appendChild(la.el):ka.field.parentNode.insertBefore(la.el,ka.field.nextSibling),x(ka.field,"change",la._onInputChange),ka.defaultDate||(ka.defaultDate=la._parseFieldValue(),ka.setDefaultDate=!0));ia=ka.defaultDate;a(ia)?ka.setDefaultDate?la.setDate(ia,!0):la.gotoDate(ia):
la.gotoDate(new Date);ka.bound?(this.hide(),la.el.className+=" is-bound",x(ka.trigger,"click",la._onInputClick),x(ka.trigger,"focus",la._onInputFocus),x(ka.trigger,"blur",la._onInputBlur)):this.show()}function na(ia,la,ka){return'<table cellpadding="0" cellspacing="0" class="pika-table" role="grid" aria-labelledby="'+ka+'">'+function(qa){var pa,ra=[];qa.showWeekNumber&&ra.push("<th></th>");for(pa=0;7>pa;pa++)ra.push('<th scope="col"><abbr title="'+fa(qa,pa)+'">'+fa(qa,pa,!0)+"</abbr></th>");return"<thead><tr>"+
(qa.isRTL?ra.reverse():ra).join("")+"</tr></thead>"}(ia)+("<tbody>"+la.join("")+"</tbody>")+(ia.showTodayButton?function(qa){var pa=[];return pa.push('<td colspan="'+(qa.showWeekNumber?"8":"7")+'"><button class="pika-set-today">'+qa.i18n.today+"</button></td>"),"<tfoot>"+(qa.isRTL?pa.reverse():pa).join("")+"</tfoot>"}(ia):"")+"</table>"}function ma(ia,la,ka,qa,pa,ra){var ua,va,sa=ia._o,xa=ka===sa.minYear,Ea=ka===sa.maxYear,Ha='<div id="'+ra+'" class="pika-title" role="heading" aria-live="assertive">',
Aa=!0,Ja=!0;var La=[];for(ra=0;12>ra;ra++)La.push('<option value="'+(ka===pa?ra-la:12+ra-la)+'"'+(ra===qa?' selected="selected"':"")+(xa&&ra<sa.minMonth||Ea&&ra>sa.maxMonth?' disabled="disabled"':"")+">"+sa.i18n.months[ra]+"</option>");pa='<div class="pika-label">'+sa.i18n.months[qa]+'<select class="pika-select pika-select-month" tabindex="-1">'+La.join("")+"</select></div>";b(sa.yearRange)?(ra=sa.yearRange[0],ua=sa.yearRange[1]+1):(ra=ka-sa.yearRange,ua=1+ka+sa.yearRange);for(La=[];ra<ua&&ra<=sa.maxYear;ra++)ra>=
sa.minYear&&La.push('<option value="'+ra+'"'+(ra===ka?' selected="selected"':"")+">"+ra+"</option>");return va='<div class="pika-label">'+ka+sa.yearSuffix+'<select class="pika-select pika-select-year" tabindex="-1">'+La.join("")+"</select></div>",sa.showMonthAfterYear?Ha+=va+pa:Ha+=pa+va,xa&&(0===qa||sa.minMonth>=qa)&&(Aa=!1),Ea&&(11===qa||sa.maxMonth<=qa)&&(Ja=!1),0===la&&(Ha+='<button class="pika-prev'+(Aa?"":" is-disabled")+'" type="button">'+sa.i18n.previousMonth+"</button>"),la===ia._o.numberOfMonths-
1&&(Ha+='<button class="pika-next'+(Ja?"":" is-disabled")+'" type="button">'+sa.i18n.nextMonth+"</button>"),Ha+"</div>"}function fa(ia,la,ka){for(la+=ia.firstDay;7<=la;)la-=7;return ka?ia.i18n.weekdaysShort[la]:ia.i18n.weekdays[la]}function da(ia){return 0>ia.month&&(ia.year-=Math.ceil(Math.abs(ia.month)/12),ia.month+=12),11<ia.month&&(ia.year+=Math.floor(Math.abs(ia.month)/12),ia.month-=12),ia}function aa(ia,la,ka){var qa;ca.createEvent?((qa=ca.createEvent("HTMLEvents")).initEvent(la,!0,!1),qa=w(qa,
ka),ia.dispatchEvent(qa)):ca.createEventObject&&(qa=ca.createEventObject(),qa=w(qa,ka),ia.fireEvent("on"+la,qa))}function w(ia,la,ka){var qa,pa;for(qa in la)(pa=void 0!==ia[qa])&&"object"==typeof la[qa]&&null!==la[qa]&&void 0===la[qa].nodeName?a(la[qa])?ka&&(ia[qa]=new Date(la[qa].getTime())):b(la[qa])?ka&&(ia[qa]=la[qa].slice(0)):ia[qa]=w({},la[qa],ka):!ka&&pa||(ia[qa]=la[qa]);return ia}function y(ia){a(ia)&&ia.setHours(0,0,0,0)}function h(ia,la){return[31,0==ia%4&&0!=ia%100||0==ia%400?29:28,31,
30,31,30,31,31,30,31,30,31][la]}function a(ia){return/Date/.test(Object.prototype.toString.call(ia))&&!isNaN(ia.getTime())}function b(ia){return/Array/.test(Object.prototype.toString.call(ia))}function e(ia,la){var ka;ia.className=(ka=(" "+ia.className+" ").replace(" "+la+" "," ")).trim?ka.trim():ka.replace(/^\s+|\s+$/g,"")}function f(ia,la){n(ia,la)||(ia.className=""===ia.className?la:ia.className+" "+la)}function n(ia,la){return-1!==(" "+ia.className+" ").indexOf(" "+la+" ")}function z(ia,la,ka,
qa){ja?ia.removeEventListener(la,ka,!!qa):ia.detachEvent("on"+la,ka)}function x(ia,la,ka,qa){ja?ia.addEventListener(la,ka,!!qa):ia.attachEvent("on"+la,ka)}var ea="function"==typeof r,ja=!!window.addEventListener,ca=window.document,ba=window.setTimeout,ha={field:null,bound:void 0,ariaLabel:"Use the arrow keys to pick a date",position:"bottom left",reposition:!0,format:"YYYY-MM-DD",toString:null,parse:null,defaultDate:null,setDefaultDate:!1,firstDay:0,firstWeekOfYearMinDays:4,formatStrict:!1,minDate:null,
maxDate:null,yearRange:10,showWeekNumber:!1,showTodayButton:!1,pickWholeWeek:!1,minYear:0,maxYear:9999,minMonth:void 0,maxMonth:void 0,startRange:null,endRange:null,isRTL:!1,yearSuffix:"",showMonthAfterYear:!1,showDaysInNextAndPreviousMonths:!1,enableSelectionDaysInNextAndPreviousMonths:!1,numberOfMonths:1,mainCalendar:"left",container:void 0,blurFieldOnSelect:!0,i18n:{previousMonth:"Previous Month",nextMonth:"Next Month",today:"Today",months:"January February March April May June July August September October November December".split(" "),
weekdays:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),weekdaysShort:"Sun Mon Tue Wed Thu Fri Sat".split(" ")},theme:null,events:[],onSelect:null,onOpen:null,onClose:null,onDraw:null,keyboardInput:!0};return oa.prototype={config:function(ia){this._o||(this._o=w({},ha,!0));ia=w(this._o,ia,!0);ia.isRTL=!!ia.isRTL;ia.field=ia.field&&ia.field.nodeName?ia.field:null;ia.theme="string"==typeof ia.theme&&ia.theme?ia.theme:null;ia.bound=!!(void 0!==ia.bound?ia.field&&ia.bound:ia.field);
ia.trigger=ia.trigger&&ia.trigger.nodeName?ia.trigger:ia.field;ia.disableWeekends=!!ia.disableWeekends;ia.disableDayFn="function"==typeof ia.disableDayFn?ia.disableDayFn:null;var la=parseInt(ia.numberOfMonths,10)||1;(ia.numberOfMonths=4<la?4:la,a(ia.minDate)||(ia.minDate=!1),a(ia.maxDate)||(ia.maxDate=!1),ia.minDate&&ia.maxDate&&ia.maxDate<ia.minDate&&(ia.maxDate=ia.minDate=!1),ia.minDate&&this.setMinDate(ia.minDate),ia.maxDate&&this.setMaxDate(ia.maxDate),b(ia.yearRange))?(la=(new Date).getFullYear()-
10,ia.yearRange[0]=parseInt(ia.yearRange[0],10)||la,ia.yearRange[1]=parseInt(ia.yearRange[1],10)||la):(ia.yearRange=Math.abs(parseInt(ia.yearRange,10))||ha.yearRange,100<ia.yearRange&&(ia.yearRange=100));return ia},toString:function(ia){return ia=ia||this._o.format,a(this._d)?this._o.toString?this._o.toString(this._d,ia):ea?r(this._d).format(ia):this._d.toDateString():""},getMoment:function(){return ea?r(this._d):null},setMoment:function(ia,la){ea&&r.isMoment(ia)&&this.setDate(ia.toDate(),la)},getDate:function(){return a(this._d)?
new Date(this._d.getTime()):null},setDate:function(ia,la){if(!ia)return this._d=null,this._o.field&&(this._o.field.value="",aa(this._o.field,"change",{firedBy:this})),this.draw();if("string"==typeof ia&&(ia=new Date(Date.parse(ia))),a(ia)){var ka=this._o.minDate,qa=this._o.maxDate;a(ka)&&ia<ka?ia=ka:a(qa)&&ia>qa&&(ia=qa);this._d=new Date(ia.getTime());this.gotoDate(this._d);this._o.field&&(this._o.field.value=this.toString(),aa(this._o.field,"change",{firedBy:this}));la||"function"!=typeof this._o.onSelect||
this._o.onSelect.call(this,this.getDate())}},clear:function(){this.setDate(null)},gotoDate:function(ia){var la=!0;if(a(ia)){if(this.calendars){la=new Date(this.calendars[0].year,this.calendars[0].month,1);var ka=new Date(this.calendars[this.calendars.length-1].year,this.calendars[this.calendars.length-1].month,1),qa=ia.getTime();ka.setMonth(ka.getMonth()+1);ka.setDate(ka.getDate()-1);la=qa<la.getTime()||ka.getTime()<qa}la&&(this.calendars=[{month:ia.getMonth(),year:ia.getFullYear()}],"right"===this._o.mainCalendar&&
(this.calendars[0].month+=1-this._o.numberOfMonths));this.adjustCalendars()}},adjustDate:function(ia,la){var ka,qa=this.getDate()||new Date;la=864E5*parseInt(la);"add"===ia?ka=new Date(qa.valueOf()+la):"subtract"===ia&&(ka=new Date(qa.valueOf()-la));this.setDate(ka)},adjustCalendars:function(){this.calendars[0]=da(this.calendars[0]);for(var ia=1;ia<this._o.numberOfMonths;ia++)this.calendars[ia]=da({month:this.calendars[0].month+ia,year:this.calendars[0].year});this.draw()},gotoToday:function(){this.gotoDate(new Date)},
gotoMonth:function(ia){isNaN(ia)||(this.calendars[0].month=parseInt(ia,10),this.adjustCalendars())},nextMonth:function(){this.calendars[0].month++;this.adjustCalendars()},prevMonth:function(){this.calendars[0].month--;this.adjustCalendars()},gotoYear:function(ia){isNaN(ia)||(this.calendars[0].year=parseInt(ia,10),this.adjustCalendars())},setMinDate:function(ia){ia instanceof Date?(y(ia),this._o.minDate=ia,this._o.minYear=ia.getFullYear(),this._o.minMonth=ia.getMonth()):(this._o.minDate=ha.minDate,
this._o.minYear=ha.minYear,this._o.minMonth=ha.minMonth,this._o.startRange=ha.startRange);this.draw()},setMaxDate:function(ia){ia instanceof Date?(y(ia),this._o.maxDate=ia,this._o.maxYear=ia.getFullYear(),this._o.maxMonth=ia.getMonth()):(this._o.maxDate=ha.maxDate,this._o.maxYear=ha.maxYear,this._o.maxMonth=ha.maxMonth,this._o.endRange=ha.endRange);this.draw()},setStartRange:function(ia){this._o.startRange=ia},setEndRange:function(ia){this._o.endRange=ia},draw:function(ia){if(this._v||ia){var la=
this._o;var ka=la.minYear;var qa=la.maxYear,pa=la.minMonth,ra=la.maxMonth;ia="";this._y<=ka&&(this._y=ka,!isNaN(pa)&&this._m<pa&&(this._m=pa));this._y>=qa&&(this._y=qa,!isNaN(ra)&&this._m>ra&&(this._m=ra));for(qa=0;qa<la.numberOfMonths;qa++)ka="pika-title-"+Math.random().toString(36).replace(/[^a-z]+/g,"").substr(0,2),ia+='<div class="pika-lendar">'+ma(this,qa,this.calendars[qa].year,this.calendars[qa].month,this.calendars[0].year,ka)+this.render(this.calendars[qa].year,this.calendars[qa].month,ka)+
"</div>";this.el.innerHTML=ia;la.bound&&"hidden"!==la.field.type&&ba(function(){la.trigger.focus()},1);"function"==typeof this._o.onDraw&&this._o.onDraw(this);la.bound&&la.field.setAttribute("aria-label",la.ariaLabel)}},adjustPosition:function(){var ia,la,ka,qa,pa,ra,ua,va,sa;if(!this._o.container){if(this.el.style.position="absolute",la=ia=this._o.trigger,ka=this.el.offsetWidth,qa=this.el.offsetHeight,pa=window.innerWidth||ca.documentElement.clientWidth,ra=window.innerHeight||ca.documentElement.clientHeight,
ua=window.pageYOffset||ca.body.scrollTop||ca.documentElement.scrollTop,va=!0,sa=!0,"function"==typeof ia.getBoundingClientRect){var xa=(la=ia.getBoundingClientRect()).left+window.pageXOffset;var Ea=la.bottom+window.pageYOffset}else for(xa=la.offsetLeft,Ea=la.offsetTop+la.offsetHeight;la=la.offsetParent;)xa+=la.offsetLeft,Ea+=la.offsetTop;(this._o.reposition&&xa+ka>pa||-1<this._o.position.indexOf("right")&&0<xa-ka+ia.offsetWidth)&&(xa=xa-ka+ia.offsetWidth,va=!1);(this._o.reposition&&Ea+qa>ra+ua||-1<
this._o.position.indexOf("top")&&0<Ea-qa-ia.offsetHeight)&&(Ea=Ea-qa-ia.offsetHeight,sa=!1);0>xa&&(xa=0);0>Ea&&(Ea=0);this.el.style.left=xa+"px";this.el.style.top=Ea+"px";f(this.el,va?"left-aligned":"right-aligned");f(this.el,sa?"bottom-aligned":"top-aligned");e(this.el,va?"right-aligned":"left-aligned");e(this.el,sa?"top-aligned":"bottom-aligned")}},render:function(ia,la,ka){var qa=this._o,pa=new Date,ra=h(ia,la),ua=(new Date(ia,la,1)).getDay(),va=[],sa=[];y(pa);0<qa.firstDay&&0>(ua-=qa.firstDay)&&
(ua+=7);for(var xa=0===la?11:la-1,Ea=11===la?0:la+1,Ha=0===la?ia-1:ia,Aa=11===la?ia+1:ia,Ja=h(Ha,xa),La=ra+ua,Oa=La;7<Oa;)Oa-=7;La+=7-Oa;for(var Qa=!1,Da=Oa=0;Oa<La;Oa++){var Ga=new Date(ia,la,Oa-ua+1),Ta=!!a(this._d)&&Ga.getTime()===this._d.getTime(),Pa=Ga.getTime()===pa.getTime(),Wa=-1!==qa.events.indexOf(Ga.toDateString()),eb=Oa<ua||Oa>=ra+ua,Sa=Oa-ua+1,sb=la,jb=ia,hb=qa.startRange&&qa.startRange.getTime()===Ga.getTime(),Xa=qa.endRange&&qa.endRange.getTime()===Ga.getTime(),Ia=qa.startRange&&qa.endRange&&
qa.startRange<Ga&&Ga<qa.endRange;eb&&(Oa<ua?(Sa=Ja+Sa,sb=xa,jb=Ha):(Sa-=ra,sb=Ea,jb=Aa));var Ra=Ta,Va;!(Va=qa.minDate&&Ga<qa.minDate||qa.maxDate&&Ga>qa.maxDate)&&(Va=qa.disableWeekends)&&(Va=Ga.getDay(),Va=0===Va||6===Va);eb={day:Sa,month:sb,year:jb,hasEvent:Wa,isSelected:Ra,isToday:Pa,isDisabled:Va||qa.disableDayFn&&qa.disableDayFn(Ga),isEmpty:eb,isStartRange:hb,isEndRange:Xa,isInRange:Ia,showDaysInNextAndPreviousMonths:qa.showDaysInNextAndPreviousMonths,enableSelectionDaysInNextAndPreviousMonths:qa.enableSelectionDaysInNextAndPreviousMonths};
qa.pickWholeWeek&&Ta&&(Qa=!0);Ta=sa;Ga=Ta.push;a:{hb=eb;Xa=[];Ia="false";if(hb.isEmpty){if(!hb.showDaysInNextAndPreviousMonths){eb='<td class="is-empty"></td>';break a}Xa.push("is-outside-current-month");hb.enableSelectionDaysInNextAndPreviousMonths||Xa.push("is-selection-disabled")}eb=(hb.isDisabled&&Xa.push("is-disabled"),hb.isToday&&Xa.push("is-today"),hb.isSelected&&(Xa.push("is-selected"),Ia="true"),hb.hasEvent&&Xa.push("has-event"),hb.isInRange&&Xa.push("is-inrange"),hb.isStartRange&&Xa.push("is-startrange"),
hb.isEndRange&&Xa.push("is-endrange"),'<td data-day="'+hb.day+'" class="'+Xa.join(" ")+'" aria-selected="'+Ia+'"><button class="pika-button pika-day" type="button" data-pika-year="'+hb.year+'" data-pika-month="'+hb.month+'" data-pika-day="'+hb.day+'">'+hb.day+"</button></td>")}Ga.call(Ta,eb);7==++Da&&(qa.showWeekNumber&&(Da=sa,Ta=Da.unshift,hb=qa.firstWeekOfYearMinDays,Ga=new Date(ia,la,Oa-ua),ea?Ga=r(Ga).isoWeek():(Ga.setHours(0,0,0,0),Xa=Ga.getDate(),eb=hb-1,Ga.setDate(Xa+eb-(Ga.getDay()+7-1)%7),
hb=new Date(Ga.getFullYear(),0,hb),Ga=1+Math.round(((Ga.getTime()-hb.getTime())/864E5-eb+(hb.getDay()+7-1)%7)/7)),Ta.call(Da,'<td class="pika-week">'+Ga+"</td>")),Da=va,Ta=Da.push,sa='<tr class="pika-row'+(qa.pickWholeWeek?" pick-whole-week":"")+(Qa?" is-selected":"")+'">'+(qa.isRTL?sa.reverse():sa).join("")+"</tr>",Ta.call(Da,sa),sa=[],Da=0,Qa=!1)}return na(qa,va,ka)},isVisible:function(){return this._v},show:function(){this.isVisible()||(this._v=!0,this.draw(),e(this.el,"is-hidden"),this._o.bound&&
(x(ca,"click",this._onClick),this.adjustPosition()),"function"==typeof this._o.onOpen&&this._o.onOpen.call(this))},hide:function(){var ia=this._v;!1!==ia&&(this._o.bound&&z(ca,"click",this._onClick),this._o.container||(this.el.style.position="static",this.el.style.left="auto",this.el.style.top="auto"),f(this.el,"is-hidden"),this._v=!1,void 0!==ia&&"function"==typeof this._o.onClose&&this._o.onClose.call(this))},destroy:function(){var ia=this._o;this.hide();z(this.el,"mousedown",this._onMouseDown,
!0);z(this.el,"touchend",this._onMouseDown,!0);z(this.el,"change",this._onChange);ia.keyboardInput&&z(ca,"keydown",this._onKeyChange);ia.field&&(z(ia.field,"change",this._onInputChange),ia.bound&&(z(ia.trigger,"click",this._onInputClick),z(ia.trigger,"focus",this._onInputFocus),z(ia.trigger,"blur",this._onInputBlur)));this.el.parentNode&&this.el.parentNode.removeChild(this.el)}},oa})}}]);}).call(this || window)
>>>>>>> 161efc3... Update lib to 8.10
