/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[11],{523:function(wa,sa,h){h.r(sa);var pa=h(0),na=h(1);h.n(na);var ma=h(3),ja=h(176);wa=h(49);var ia=h(112),ea=h(290),y=h(82),z=h(289);h=h(435);var f=window,e=function(){function n(r,aa,w){var ba=-1===r.indexOf("?")?"?":"&";switch(aa){case y.a.NEVER_CACHE:this.url=r+ba+"_="+Object(na.uniqueId)();break;default:this.url=r}this.Rf=w;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);this.request.setRequestHeader("X-Requested-With",
"XMLHttpRequest");this.request.overrideMimeType?this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=z.a.NOT_STARTED}n.prototype.start=function(r,aa){var w=this,ba=this,fa=this.request,x;ba.Vz=0;r&&Object.keys(r).forEach(function(ca){w.request.setRequestHeader(ca,r[ca])});aa&&(this.request.withCredentials=aa);this.GH=setInterval(function(){var ca=0===window.document.URL.indexOf("file:///");ca=200===fa.status||
ca&&0===fa.status;if(fa.readyState!==z.b.DONE||ca){try{fa.responseText}catch(ha){return}ba.Vz<fa.responseText.length&&(x=ba.ksa())&&ba.trigger(n.Events.DATA,[x]);0===fa.readyState&&(clearInterval(ba.GH),ba.trigger(n.Events.DONE))}else clearInterval(ba.GH),ba.trigger(n.Events.DONE,["Error received return status "+fa.status])},1E3);this.request.send(null);this.status=z.a.STARTED};n.prototype.ksa=function(){var r=this.request,aa=r.responseText;if(0!==aa.length)if(this.Vz===aa.length)clearInterval(this.GH),
this.trigger(n.Events.DONE);else return aa=Math.min(this.Vz+3E6,aa.length),r=f.B_(r,this.Vz,!0,aa),this.Vz=aa,r};n.prototype.abort=function(){clearInterval(this.GH);var r=this;this.request.onreadystatechange=function(){Object(ma.j)("StreamingRequest aborted");r.status=z.a.ABORTED;return r.trigger(n.Events.ABORTED)};this.request.abort()};n.prototype.finish=function(){var r=this;this.request.onreadystatechange=function(){r.status=z.a.SUCCESS;return r.trigger(n.Events.DONE)};this.request.abort()};n.Events=
{DONE:"done",DATA:"data",ABORTED:"aborted"};return n}();Object(wa.a)(e);var a;(function(n){n[n.LOCAL_HEADER=0]="LOCAL_HEADER";n[n.FILE=1]="FILE";n[n.CENTRAL_DIR=2]="CENTRAL_DIR"})(a||(a={}));var b=function(n){function r(){var aa=n.call(this)||this;aa.buffer="";aa.state=a.LOCAL_HEADER;aa.PR=4;aa.wn=null;aa.Bv=ja.c;aa.kp={};return aa}Object(pa.c)(r,n);r.prototype.dsa=function(aa){var w;for(aa=this.buffer+aa;aa.length>=this.Bv;)switch(this.state){case a.LOCAL_HEADER:this.wn=w=this.osa(aa.slice(0,this.Bv));
if(w.jw!==ja.g)throw Error("Wrong signature in local header: "+w.jw);aa=aa.slice(this.Bv);this.state=a.FILE;this.Bv=w.uL+w.ns+w.Fy+this.PR;this.trigger(r.Events.HEADER,[w]);break;case a.FILE:this.wn.name=aa.slice(0,this.wn.ns);this.kp[this.wn.name]=this.wn;w=this.Bv-this.PR;var ba=aa.slice(this.wn.ns+this.wn.Fy,w);this.trigger(r.Events.FILE,[this.wn.name,ba,this.wn.NL]);aa=aa.slice(w);if(aa.slice(0,this.PR)===ja.h)this.state=a.LOCAL_HEADER,this.Bv=ja.c;else return this.state=a.CENTRAL_DIR,!0}this.buffer=
aa;return!1};r.Events={HEADER:"header",FILE:"file"};return r}(ea.a);Object(wa.a)(b);wa=function(n){function r(aa,w,ba,fa,x){ba=n.call(this,aa,ba,fa)||this;ba.url=aa;ba.stream=new e(aa,w);ba.Wd=new b;ba.A3=window.createPromiseCapability();ba.e4={};ba.Rf=x;return ba}Object(pa.c)(r,n);r.prototype.UA=function(aa){var w=this;this.request([this.lk,this.$l,this.kk]);this.stream.addEventListener(e.Events.DATA,function(ba){try{if(w.Wd.dsa(ba))return w.stream.finish()}catch(fa){throw w.stream.abort(),w.zr(fa),
aa(fa),fa;}});this.stream.addEventListener(e.Events.DONE,function(ba){w.Fra=!0;w.A3.resolve();ba&&(w.zr(ba),aa(ba))});this.Wd.addEventListener(b.Events.HEADER,Object(na.bind)(this.d4,this));this.Wd.addEventListener(b.Events.FILE,Object(na.bind)(this.Esa,this));return this.stream.start(this.Rf,this.withCredentials)};r.prototype.x_=function(aa){var w=this;this.A3.promise.then(function(){aa(Object.keys(w.Wd.kp))})};r.prototype.Wp=function(){return!0};r.prototype.request=function(aa){var w=this;this.Fra&&
aa.forEach(function(ba){w.e4[ba]||w.gya(ba)})};r.prototype.d4=function(){};r.prototype.abort=function(){this.stream&&this.stream.abort()};r.prototype.gya=function(aa){this.trigger(ia.a.Events.PART_READY,[{ob:aa,error:"Requested part not found",uj:!1,Ng:!1}])};r.prototype.Esa=function(aa,w,ba){this.e4[aa]=!0;this.trigger(ia.a.Events.PART_READY,[{ob:aa,data:w,uj:!1,Ng:!1,error:null,Dd:ba}])};return r}(ia.a);Object(h.a)(wa);Object(h.b)(wa);sa["default"]=wa}}]);}).call(this || window)
