/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[13],{525:function(wa,sa,h){function pa(){return!1}function na(w,ba,fa){if(!(ba in aa))return!0;ba=aa[ba];for(var x=0;x<ba.length;x++){var ca=w;var ha=ba[x];var oa=fa;if(ha.name in ca){var la="",ka=!1;ca=ca[ha.name];switch(ha.type){case "s":la="String";ka=Object(ia.isString)(ca);break;case "a":la="Array";ka=Object(ia.isArray)(ca);break;case "n":la="Number";ka=Object(ia.isNumber)(ca)&&Object(ia.isFinite)(ca);break;case "o":la="Object",
ka=Object(ia.isObject)(ca)&&!Object(ia.isArray)(ca)}ka||oa.reject('Expected response field "'+ha.name+'" to have type '+la);ha=ka}else oa.reject('Response missing field "'+ha.name+'"'),ha=!1;if(!ha)return!1}return!0}function ma(w){for(var ba=0,fa=["locale","excelMaxAllowedCellCount","applyPageBreaksToSheet","excelDefaultCellBorderWidth","displayChangeTracking"];ba<fa.length;ba++){var x=fa[ba],ca=x;x=x.charAt(0).toUpperCase()+x.slice(1);w[ca]&&(Object.defineProperty(w,x,Object.getOwnPropertyDescriptor(w,
ca)),delete w[ca])}return w}h.r(sa);var ja=h(0),ia=h(1);h.n(ia);var ea=h(3);wa=h(49);var y=h(27),z=h(543),f=h(112),e=h(435),a=h(47),b=h(193),n=function(){function w(){this.request=this.result=null;this.state=0;var ba=this;ba.promise=new Promise(function(fa,x){ba.resolve=function(){if(0===ba.state||4===ba.state)ba.state=1,ba.result=arguments[0],fa.apply(null,arguments)};ba.reject=function(){if(0===ba.state||4===ba.state)ba.state=2,x.apply(null,arguments)}})}w.prototype.qv=function(){return 1===(this.state&
1)};w.prototype.Ioa=function(){return 2===(this.state&2)};w.prototype.Kj=function(){return!this.Ioa()&&!this.qv()};w.prototype.goa=function(){return 4===(this.state&4)};w.prototype.hR=function(){this.state|=4};return w}(),r=function(){function w(){this.Zu={};this.Xb=[]}w.prototype.pop=function(){var ba=this.Xb.pop();this.Zu[ba.key]=void 0;return ba};w.prototype.push=function(ba,fa){fa={key:ba,data:fa};this.Xb.push(fa);this.Zu[ba]=fa.data};w.prototype.contains=function(ba){return!!this.Zu[ba]};w.prototype.get=
function(ba){return this.Zu[ba]};w.prototype.set=function(ba,fa){var x=this;this.Zu[ba]=fa;this.Xb.forEach(function(ca,ha){ca.key===ba&&(x.Xb[ha]=ca)})};w.prototype.remove=function(ba){var fa=this;this.Zu[ba]=void 0;this.Xb.forEach(function(x,ca){x.key===ba&&fa.Xb.splice(ca,1)})};w.prototype.length=function(){return this.Xb.length};return w}(),aa={pages:[{name:"pages",type:"a"}],pdf:[{name:"url",type:"s"}],docmod:[{name:"url",type:"s"},{name:"rID",type:"s"}],health:[],tiles:[{name:"z",type:"n"},{name:"rID",
type:"n"},{name:"tiles",type:"a"},{name:"size",type:"n"}],cAnnots:[{name:"annots",type:"a"}],annots:[{name:"url",type:"s"},{name:"name",type:"s"}],image:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],text:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],ApString2Xod:[{name:"url",type:"s"},{name:"rID",type:"s"}]};h=function(){function w(ba,fa,x){var ca=this;this.QR=this.xY=!1;this.Xh=this.$I=this.Fw=this.bf=this.Sx=this.Pp=this.Rx=this.fo=null;this.Gn=new n;this.ir=
new n;this.uE=!1;this.jg=this.gf=this.hf=this.$f=null;this.Eg=[];this.gF=[];this.cache={};this.timeStamp=0;this.Rh=[];this.Tj=[];this.PM=null;this.jY=!1;this.s5=this.id=null;this.jP=this.m0=pa;this.Ri=0;this.kO=!1;this.m2=1;this.Qj={};this.Tt=0;this.Sv=new r;fa.endsWith("/")||(fa+="/");x=x||{};this.xY=x.disableWebsockets||!1;this.QR=x.singleServerMode||!1;null!=x.customQueryParameters&&Object(a.b)("wvsQueryParameters",x.customQueryParameters);fa.endsWith("blackbox/")||(fa+="blackbox/");this.fo=x.uploadData||
null;this.Fw=x.uriData||null;this.Rx=x.cacheKey||null;if(this.Pp=x.officeOptions||null)this.Pp=ma(this.Pp);this.bf=x.rasterizerOptions||null;this.Sx=x.cadOptions||null;this.Ef=fa;this.nM=ba;this.$p(!0);this.mu=(new z.a(fa,null,this.Di())).Kja(!this.xY,function(ha){ca.Bqa(ha)},function(){return null},function(){ca.uE=!1},function(){ca.Xta()})}w.prototype.ega=function(){var ba=this;return new Promise(function(fa,x){var ca=new XMLHttpRequest;ca.open("GET",ba.Ef+"ck");ca.withCredentials=ba.Di();ca.onreadystatechange=
function(){ca.readyState===XMLHttpRequest.DONE&&(200===ca.status?fa():x())};ca.send()})};w.prototype.Sva=function(ba){this.m0=ba||pa;this.jP=pa};w.prototype.Gea=function(){this.S4();return this.mu.wr(!0)};w.prototype.S4=function(){Object(ja.b)(this,void 0,void 0,function(){return Object(ja.d)(this,function(ba){switch(ba.label){case 0:return this.ir=new n,this.Gn=new n,this.uE=!1,this.id=null,this.jY=!1,[4,this.ega()];case 1:return ba.ba(),[2]}})})};w.prototype.Xta=function(){this.m0();this.S4();this.$f&&
(this.$f.Kj()?this.di(this.$f.request):this.$f.qv()&&this.jP(this.$f.result.url,"pdf")&&(this.$f=null,this.Q4()));this.jg&&this.jg.Kj()&&this.di(this.jg.request);this.hf&&this.hf.Kj()?this.di(this.hf.request):this.gf&&this.gf.Kj()&&this.W_();var ba;for(ba=0;ba<this.Rh.length;ba++)this.Rh[ba]&&(this.Rh[ba].Kj()?this.di(this.Rh[ba].request):this.Rh[ba].qv()&&this.jP(this.Rh[ba].result.url,"image")&&(this.Rh[ba]=null,this.VH(Object(ia.uniqueId)(),ba)));for(ba=0;ba<this.Tj.length;ba++)this.Tj[ba]&&this.Tj[ba].Kj()&&
!this.Tj[ba].goa()&&this.di(this.Tj[ba].request);for(ba=0;ba<this.Eg.length;ba++)this.Eg[ba]&&this.Eg[ba].Kj()&&this.di(this.Eg[ba].request)};w.prototype.Ina=function(){return this.uE?Promise.resolve():(this.uE=!0,this.timeStamp=Date.now(),this.mu.pG())};w.prototype.Iya=function(){var ba=this,fa,x,ca,ha,oa;return new Promise(function(la,ka){if(ba.fo)fa=new FormData,fa.append("file",ba.fo.fileHandle,ba.fo.fileHandle.name),ba.Pp&&fa.append("officeOptions",JSON.stringify(ba.Pp)),ba.bf&&fa.append("rasterizerOptions",
JSON.stringify(ba.bf)),ba.Sx&&fa.append("cadOptions",ba.Sx.getJsonString()),ba.Rx&&fa.append("cacheKey",ba.Rx),x=ba.fo.loadCallback,ha="upload",ca=ba.fo.extension;else if(ba.Fw)fa={uri:ba.Fw.uri,TCa:ba.Fw.shareId},fa=Object.keys(fa).map(function(ta){return ta+"="+(fa[ta]?encodeURIComponent(fa[ta]):"")}).join("&"),oa="application/x-www-form-urlencoded; charset=UTF-8",x=ba.Fw.loadCallback,ha="url",ca=ba.Fw.extension;else{la();return}var qa=new XMLHttpRequest,ra=Object(y.k)(ba.Ef,"AuxUpload");ra=Object(b.a)(ra,
{type:ha,ext:ca});qa.open("POST",ra);qa.withCredentials=ba.Di();oa&&qa.setRequestHeader("Content-Type",oa);qa.addEventListener("load",function(){if(qa.readyState===qa.DONE&&200===qa.status){var ta=JSON.parse(qa.response);ba.nM=ta.uri;x(ta);la(ta)}});qa.addEventListener("error",function(){ka(qa.statusText+" "+JSON.stringify(qa))});ba.fo&&null!=ba.fo.onProgress&&(qa.upload.onprogress=function(ta){ba.fo.onProgress(ta)});qa.send(fa)})};w.prototype.Lta=function(ba){this.password=ba||null;this.Gn.qv()||
(this.Gn=new n,this.di({t:"pages"}));return this.Gn.promise};w.prototype.UA=function(ba){this.PM=ba||null;this.Gn.qv()||this.di({t:"pages"});return this.Gn.promise};w.prototype.gy=function(ba){ba=Object.assign(ba,{uri:encodeURIComponent(this.nM)});this.PM&&(ba.ext=this.PM);this.Xh&&(ba.c=this.Xh);this.password&&(ba.pswd=this.password);this.Rx&&(ba.cacheKey=this.Rx);this.Pp&&(ba.officeOptions=this.Pp);this.bf&&(ba.rastOptions=this.bf);this.Sx&&(ba.cadOptions=this.Sx.mImpl);return ba};w.prototype.Bua=
function(){0<this.Sv.length()&&10>=this.Tt&&this.Cua(this.Sv.pop().data)};w.prototype.Uda=function(ba){0<this.Sv.length()&&this.Sv.contains(ba)&&this.Sv.remove(ba)};w.prototype.di=function(ba){ba=this.gy(ba);this.mu.send(ba)};w.prototype.n5=function(ba,fa){10<this.Tt?this.Sv.push(ba,fa):(this.Tt++,ba=this.gy(fa),this.mu.send(ba))};w.prototype.Cua=function(ba){this.Tt++;ba=this.gy(ba);this.mu.send(ba)};w.prototype.Jm=function(ba){return ba};w.prototype.l0=function(ba){this.QR&&ba?Object(ea.j)("Server failed health check. Single server mode ignoring check."):
!this.eBa&&ba&&3>=this.Ri?(this.kO=!0,this.mu.wr()):3<this.Ri&&(this.QR=!0)};w.prototype.Bqa=function(ba){var fa=this,x=ba.data,ca=ba.err,ha=ba.t;switch(ha){case "upload":ca?this.Jya.reject(ca):this.Jya.resolve("Success");break;case "pages":ca?this.Gn.reject(ca):na(x,ha,this.Gn)&&this.Gn.resolve(x);break;case "config":if(ca)this.ir.reject(ca);else if(na(x,ha,this.ir)){this.l0(x.unhealthy);x.id&&(this.id=x.id);if(x.auth){var oa=Object(a.a)("wvsQueryParameters");oa.auth=x.auth;Object(a.b)("wvsQueryParameters",
oa)}x.serverVersion&&(this.$I=x.serverVersion,Object(ea.h)("[WebViewer Server] server version: "+this.$I));x.serverID?(this.Ri=x.serverID===this.s5&&this.kO?this.Ri+1:0,this.s5=x.serverID):this.Ri=0;this.kO=!1;this.ir.resolve(x)}break;case "health":ca?this.ir.reject(ca):na(x,ha,this.ir)&&this.l0(x.unhealthy);break;case "pdf":x.url=Object(b.a)(this.Ef+"../"+encodeURI(x.url));ca?this.$f.reject(ca):na(x,ha,this.$f)&&this.$f.resolve(x);break;case "ApString2Xod":x.url=Object(b.a)(this.Ef+"../data/"+encodeURI(x.url));
ca?this.Qj[x.rID].reject(ca):na(x,ha,this.Qj[x.rID])&&this.Qj[x.rID].resolve(x);break;case "docmod":x.url=Object(b.a)(this.Ef+"../"+encodeURI(x.url));ca?this.Qj[x.rID].reject(ca):na(x,ha,this.$f)&&this.Qj[x.rID].resolve(x);break;case "xod":if(ca)this.hf&&this.hf.Kj()&&this.hf.reject(ca),this.gf&&this.gf.Kj()&&this.gf.reject(ca);else if(x.notFound)x.noCreate||this.hf&&this.hf.Kj()&&this.hf.resolve(x),this.gf&&this.gf.Kj()&&this.gf.resolve(x);else{x.url&&(x.url=Object(b.a)(this.Ef+"../"+encodeURI(x.url)));
if(!this.gf||this.gf.qv())this.gf=new n,this.gf.request={t:"xod",noCreate:!0};this.hf||(this.hf=new n,this.hf.request={t:"xod"});this.gf.resolve(x);this.hf.resolve(x)}break;case "cAnnots":oa=this.jg;if(ca)oa.reject(ca);else if(na(x,ha,oa)){oa.hR();var la=[],ka=x.annots;x=function(Na){var Ia=ka[Na].s,Da=ka[Na].e,Oa=qa.Ef+"../"+encodeURI(ka[Na].xfdf),Ca="true"===ka[Na].hasAppearance?Object(b.a)(Oa+".xodapp"):null,Ma=Object(ia.range)(Ia,Da+1);la[Na]={range:Ma,promise:new Promise(function(Aa,Ea){var Fa=
new XMLHttpRequest;Fa.open("GET",Object(b.a)(Oa));Fa.responseType="text";Fa.withCredentials=fa.Di();Fa.addEventListener("load",function(){Fa.readyState===Fa.DONE&&200===Fa.status&&Aa({Ys:Fa.response,ym:Ca,range:Ma})});Fa.addEventListener("error",function(){Ea(Fa.statusText+" "+JSON.stringify(Fa))});Fa.send()})}};var qa=this;for(ca=0;ca<ka.length;ca++)x(ca);oa.resolve(la)}break;case "annots":if(ca)this.jg.reject(ca);else if(na(x,ha,this.jg)){this.jg.hR();var ra=new XMLHttpRequest;oa=this.Ef+"../"+
encodeURI(x.url);var ta=x.hasAppearance?Object(b.a)(oa+".xodapp"):null;ra.open("GET",Object(b.a)(oa));ra.responseType="text";ra.withCredentials=this.Di();ra.addEventListener("load",function(){ra.readyState===ra.DONE&&200===ra.status&&fa.jg.resolve({Ys:ra.response,ym:ta})});ra.addEventListener("error",function(){fa.jg.reject(ra.statusText+" "+JSON.stringify(ra))});ra.send()}break;case "image":this.Tt--;var va=this.Rh[x.p];ca?va.promise.reject(ca):na(x,ha,va)&&(va.result=x,va.result.url=Object(b.a)(this.Ef+
"../"+encodeURI(va.result.url)),va.resolve(va.result));break;case "tiles":this.Tt--;va=x.rID;oa=this.Eg[va];this.Eg[va]=null;this.gF.push(va);if(ca)oa.reject(ca);else if(na(x,ha,oa)){for(ca=0;ca<x.tiles.length;ca++)x.tiles[ca]=Object(b.a)(this.Ef+"../"+encodeURI(x.tiles[ca]));oa.resolve(x)}break;case "text":va=this.Tj[x.p];if(ca)va.reject(ca);else if(na(x,ha,va)){va.hR();var xa=new XMLHttpRequest;x=Object(b.a)(this.Ef+"../"+encodeURI(x.url));xa.open("GET",x);xa.withCredentials=this.Di();xa.addEventListener("load",
function(){xa.readyState===xa.DONE&&200===xa.status&&(va.result=JSON.parse(xa.response),va.resolve(va.result))});xa.addEventListener("error",function(Na){va.reject(xa.statusText+" "+JSON.stringify(Na))});xa.send()}break;case "progress":"loading"===x.t&&this.trigger(f.a.Events.DOCUMENT_LOADING_PROGRESS,[x.bytes,x.total])}this.Bua();!ha&&ba.echo&&ba&&"apstring2xod"===ba.echo.t&&(ba=ba.echo.reqID)&&(2<=parseInt(this.$I,10)?this.Qj[ba].reject("Message unhandled by server"):this.Qj[ba].reject())};w.prototype.Bka=
function(){return Object(ja.b)(this,void 0,void 0,function(){return Object(ja.d)(this,function(ba){switch(ba.label){case 0:return[4,this.Ina()];case 1:return ba.ba(),[2,this.ir.promise]}})})};w.prototype.hka=function(ba){for(var fa=this,x=new XMLHttpRequest,ca=Object(b.a)(this.Ef+"aul",{id:this.id}),ha=new FormData,oa={},la=0;la<ba.body.length;la++){var ka=ba.body[la];oa[ka.id]=ka.eL.w+";"+ka.eL.h;ha.append(ka.id,ka.eL.dataString)}ba={t:"apstring2xod",reqID:this.m2++,parts:oa};var qa=this.gy(ba);
ha.append("msg",JSON.stringify(qa));this.Qj[qa.reqID]=new n;x.open("POST",ca);x.withCredentials=this.Di;ca=new Promise(function(ra,ta){x.onreadystatechange=function(){4===x.readyState&&(200===x.status?ra():ta("An error occurred while sending down appearance strings to the server"))}});x.send(ha);return ca.then(function(){return fa.Qj[qa.reqID].promise})};w.prototype.Jea=function(){var ba=this.$I.split("-")[0].split("."),fa=["1","5","9"];if(3!==ba.length)throw Error("Invalid WVS version length.");
if(3!==fa.length)throw Error("Invalid version length.");for(var x=0;x<ba.length;++x){if(fa.length===x||ba[x]>fa[x])return-1;if(ba[x]!==fa[x])return 1}return 0};w.prototype.dr=function(){return 0>=this.Jea()};w.prototype.YM=function(){this.jg||(this.jg=new n,this.dr()?this.jg.request={t:"cAnnots"}:this.jg.request={t:"annots"},this.di(this.jg.request));return this.jg.promise};w.prototype.VH=function(ba,fa){this.Rh[fa]||(this.Rh[fa]=new n,this.Rh[fa].request={t:"image",p:fa},this.n5(ba,this.Rh[fa].request));
return this.Rh[fa].promise};w.prototype.Mta=function(ba){this.Tj[ba]||(this.Tj[ba]=new n,this.Tj[ba].request={t:"text",p:ba},this.di(this.Tj[ba].request));return this.Tj[ba].promise};w.prototype.Nta=function(ba,fa,x,ca,ha){var oa=this.Eg.length;this.gF.length&&(oa=this.gF.pop());this.Eg[oa]=new n;this.Eg[oa].request={t:"tiles",p:fa,z:x,r:ca,size:ha,rID:oa};this.n5(ba,this.Eg[oa].request);return this.Eg[oa].promise};w.prototype.Q4=function(){this.$f||(this.$f=new n,this.$f.request={t:"pdf"},this.jY?
this.$f.resolve({url:this.nM}):this.di(this.$f.request));return this.$f.promise};w.prototype.m_=function(ba){var fa=this,x=new XMLHttpRequest,ca=Object(b.a)(this.Ef+"aul",{id:this.id}),ha=new FormData,oa={};ba.annots&&(oa.annots="xfdf");ba.watermark&&(oa.watermark="png");ba.redactions&&(oa.redactions="redact");oa={t:"docmod",reqID:this.m2++,parts:oa};ba.print&&(oa.print=!0);var la=this.gy(oa);ha.append("msg",JSON.stringify(la));return Promise.all([ba.annots,ba.watermark,ba.redactions].map(function(ka){return Promise.resolve(ka)})).then(function(ka){var qa=
ka[0],ra=ka[1];ka=ka[2];qa&&ha.append("annots",qa);ra&&ha.append("watermark",ra);ka&&ha.append("redactions",ka);fa.Qj[la.reqID]=new n;x.open("POST",ca);x.withCredentials=fa.Di;qa=new Promise(function(ta,va){x.onreadystatechange=function(){4===x.readyState&&(200===x.status?ta():va("An error occurred while sending down annotation data to the server"))}});x.send(ha);return qa.then(function(){return fa.Qj[la.reqID].promise})})};w.prototype.W_=function(){this.gf||(this.gf=new n,this.gf.request={t:"xod",
noCreate:!0},this.di(this.gf.request));return this.gf.promise};w.prototype.Ota=function(){this.hf||(this.hf=new n,this.hf.request={t:"xod"},this.di(this.hf.request));return this.hf.promise};w.prototype.Wp=function(){return!0};w.prototype.request=function(){};w.prototype.d4=function(){};w.prototype.abort=function(){for(var ba=0;ba<this.Eg.length;ba++)this.Eg[ba]&&(this.Eg[ba].resolve(null),this.Eg[ba]=null,this.gF.push(ba));this.close()};w.prototype.hI=function(ba){this.Xh=this.Xh||{};this.Xh.headers=
ba};w.prototype.$p=function(ba){this.Xh=this.Xh||{};this.Xh.internal=this.Xh.internal||{};this.Xh.internal.withCredentials=ba};w.prototype.Di=function(){return this.Xh&&this.Xh.internal?this.Xh.internal.withCredentials:null};w.prototype.getFileData=function(){return Promise.reject()};return w}();Object(wa.a)(h);Object(e.a)(h);Object(e.b)(h);sa["default"]=h},543:function(wa,sa,h){var pa=h(0),na=h(3),ma=h(27),ja=h(47),ia=h(193),ea=h(85),y=function(){function f(e,a,b,n,r,aa){void 0===b&&(b=null);void 0===
n&&(n=null);void 0===r&&(r=null);void 0===aa&&(aa=null);this.Q1=!1;this.Ri=0;this.aX=this.dza(e);this.url=a?this.aX+"/"+a:this.aX+"/ws";this.bM=b;this.qA=n;this.by=r;this.EQ=aa}f.prototype.dza=function(e){var a=e.indexOf("://"),b="ws://";0>a?a=0:(5===a&&(b="wss://"),a+=3);var n=e.lastIndexOf("/");0>n&&(n=e.length);return b+e.slice(a,n)};f.prototype.send=function(e){this.nq.readyState===WebSocket.CLOSED||this.Q1||this.nq.send(JSON.stringify(e))};f.prototype.pG=function(){return Object(pa.b)(this,void 0,
void 0,function(){var e,a=this;return Object(pa.d)(this,function(){e=Object(ja.a)("wvsQueryParameters");e.bcid=Object(ma.l)(8);Object(ja.b)("wvsQueryParameters",e);return[2,new Promise(function(b,n){var r=Object(ia.a)(a.url);a.nq=new WebSocket(r);a.nq.onopen=function(){a.qA&&a.qA();b()};a.nq.onerror=function(aa){a.Q1=!0;n(aa)};a.nq.onclose=function(aa){var w=aa.code;return Object(pa.b)(a,void 0,void 0,function(){var ba=this;return Object(pa.d)(this,function(fa){switch(fa.label){case 0:return this.by&&
this.by(),3E3===w?[3,3]:8>this.Ri++?[4,new Promise(function(x){return setTimeout(function(){return Object(pa.b)(ba,void 0,void 0,function(){return Object(pa.d)(this,function(ca){switch(ca.label){case 0:return this.EQ(),[4,this.pG()];case 1:return ca.ba(),x(),[2]}})})},3E3)})]:[3,2];case 1:return fa.ba(),[3,3];case 2:n(ea.a),fa.label=3;case 3:return[2]}})})};a.nq.onmessage=function(aa){aa&&aa.data&&(aa=JSON.parse(aa.data),aa.hb?a.send({hb:!0}):aa.end?close():a.bM(aa))}})]})})};f.prototype.wr=function(e){void 0===
e&&(e=!1);this.Ri=0;e?this.nq.close(3E3):this.nq.close();return Promise.resolve()};return f}(),z=function(){function f(e,a,b,n,r,aa,w){void 0===n&&(n=null);void 0===r&&(r=null);void 0===aa&&(aa=null);void 0===w&&(w=null);this.Ri=this.UH=this.id=0;this.Az=!1;this.request=null;e=this.csa(e);this.url=a?e+"/"+a+"pf":e+"/pf";this.SI=b;this.bM=n;this.qA=r;this.by=aa;this.EQ=w}f.prototype.csa=function(e){var a=e.lastIndexOf("/");0>a&&(a=e.length);return e.slice(0,a)};f.prototype.Kfa=function(e){e=e.split("\n");
for(e[e.length-1]&&e.pop();0<e.length&&3>e[e.length-1].length;)"]"===e.pop()&&(this.id=0);0<e.length&&3>e[0].length&&e.shift();for(var a=0;a<e.length;++a)e[a].endsWith(",")&&(e[a]=e[a].substr(0,e[a].length-1));return e};f.prototype.a5=function(){return Object(pa.b)(this,void 0,void 0,function(){var e=this;return Object(pa.d)(this,function(a){switch(a.label){case 0:return 8>this.Ri++?[4,new Promise(function(b){return setTimeout(function(){e.EQ();e.pG();b()},3E3)})]:[3,2];case 1:a.ba(),a.label=2;case 2:return[2]}})})};
f.prototype.esa=function(e){Object(pa.b)(this,void 0,void 0,function(){var a,b;return Object(pa.d)(this,function(n){switch(n.label){case 0:a=null,b=0,n.label=1;case 1:if(!(b<e.length))return[3,6];a=JSON.parse(e[b]);if(!a)return[3,5];if(!a.end)return[3,2];close();return[3,5];case 2:if(!a.id||Number(a.id)===this.id)return[3,4];Object(na.j)("Reconnecting, new server detected");this.wr();return[4,this.a5()];case 3:return n.ba(),[3,5];case 4:a.hb&&Number(a.id)===this.id?this.send({hb:!0}):this.Az||this.bM(a),
n.label=5;case 5:return++b,[3,1];case 6:return[2]}})})};f.prototype.yqa=function(e){Object(pa.b)(this,void 0,void 0,function(){var a,b,n;return Object(pa.d)(this,function(r){switch(r.label){case 0:if(!(3<=e.readyState))return[3,2];try{a=e.responseText.length}catch(aa){return Object(na.h)("caught exception"),[2]}if(0<a)try{b=this.Kfa(e.responseText),0===this.id&&0<b.length&&(n=JSON.parse(b.shift()),this.id=n.id,this.Ri=0),this.esa(b)}catch(aa){}return this.Az?[3,2]:[4,this.dZ()];case 1:r.ba(),r.label=
2;case 2:return[2]}})})};f.prototype.dZ=function(){return Object(pa.b)(this,void 0,void 0,function(){var e=this;return Object(pa.d)(this,function(){return[2,new Promise(function(a,b){function n(){return Object(pa.b)(e,void 0,void 0,function(){return Object(pa.d)(this,function(aa){switch(aa.label){case 0:b(),this.wr(),aa.label=1;case 1:return this.Az&&8>this.Ri?[4,this.a5()]:[3,3];case 2:return aa.ba(),[3,1];case 3:return[2]}})})}e.request=new XMLHttpRequest;e.request.withCredentials=e.SI;var r=Object(ia.a)(e.url,
0!==e.id?{id:String(e.id),uc:String(e.UH)}:{uc:String(e.UH)});e.UH++;e.request.open("GET",r,!0);e.request.setRequestHeader("Cache-Control","no-cache");e.request.setRequestHeader("X-Requested-With","XMLHttpRequest");e.request.onreadystatechange=function(){e.yqa(e.request)};e.request.addEventListener("error",n);e.request.addEventListener("timeout",n);e.request.addEventListener("load",function(){e.qA&&e.qA();a()});e.request.send()})]})})};f.prototype.pG=function(){var e=Object(ja.a)("wvsQueryParameters");
e.bcid=Object(ma.l)(8);Object(ja.b)("wvsQueryParameters",e);this.UH=this.id=0;this.Az=!1;return this.dZ()};f.prototype.send=function(e){var a=this,b=new XMLHttpRequest;b.withCredentials=this.SI;var n=Object(ia.a)(this.url,{id:String(this.id)}),r=new FormData;r.append("data",JSON.stringify(e));b.addEventListener("error",function(){a.wr()});b.open("POST",n);b.setRequestHeader("X-Requested-With","XMLHttpRequest");b.send(r)};f.prototype.wr=function(){this.id=0;this.Az=!0;this.by&&this.by();this.request.abort();
return Promise.resolve()};return f}();wa=function(){function f(e,a,b){this.IX=e;this.target=a;this.SI=b}f.prototype.Kja=function(e,a,b,n,r){void 0===e&&(e=!0);void 0===a&&(a=null);void 0===b&&(b=null);void 0===n&&(n=null);void 0===r&&(r=null);return e?new y(this.IX,this.target,a,b,n,r):new z(this.IX,this.target,this.SI,a,b,n,r)};return f}();sa.a=wa}}]);}).call(this || window)
