/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
<<<<<<< HEAD
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[16],{443:function(Ba,ua,r){function pa(){return!1}function ka(aa,w,ea){if(!(w in n))return!0;w=n[w];for(var ja=0;ja<w.length;ja++){var ba=aa;var ca=w[ja];var ia=ea;if(ca.name in ba){var ha="",la=!1;ba=ba[ca.name];switch(ca.type){case "s":ha="String";la=Object(fa.isString)(ba);break;case "a":ha="Array";la=Object(fa.isArray)(ba);break;case "n":ha="Number";la=Object(fa.isNumber)(ba)&&Object(fa.isFinite)(ba);break;case "o":ha="Object",
la=Object(fa.isObject)(ba)&&!Object(fa.isArray)(ba)}la||ia.reject('Expected response field "'+ca.name+'" to have type '+ha);ca=la}else ia.reject('Response missing field "'+ca.name+'"'),ca=!1;if(!ca)return!1}return!0}r.r(ua);var ma=r(1),fa=r(0);r.n(fa);var da=r(2);Ba=r(49);var z=r(34),x=r(461),y=r(94),f=r(374),e=r(40),b=r(166),a=function(){function aa(){this.request=this.result=null;this.state=0;var w=this;w.promise=new Promise(function(ea,ja){w.resolve=function(){if(0===w.state||4===w.state)w.state=
1,w.result=arguments[0],ea.apply(null,arguments)};w.reject=function(){if(0===w.state||4===w.state)w.state=2,ja.apply(null,arguments)}})}aa.prototype.it=function(){return 1===(this.state&1)};aa.prototype.xea=function(){return 2===(this.state&2)};aa.prototype.Si=function(){return!this.xea()&&!this.it()};aa.prototype.Zda=function(){return 4===(this.state&4)};aa.prototype.rM=function(){this.state|=4};return aa}(),h=function(){function aa(){this.Qs={};this.Gb=[]}aa.prototype.pop=function(){var w=this.Gb.pop();
this.Qs[w.key]=void 0;return w};aa.prototype.push=function(w,ea){ea={key:w,data:ea};this.Gb.push(ea);this.Qs[w]=ea.data};aa.prototype.contains=function(w){return!!this.Qs[w]};aa.prototype.get=function(w){return this.Qs[w]};aa.prototype.set=function(w,ea){var ja=this;this.Qs[w]=ea;this.Gb.forEach(function(ba,ca){ba.key===w&&(ja.Gb[ca]=ba)})};aa.prototype.remove=function(w){var ea=this;this.Qs[w]=void 0;this.Gb.forEach(function(ja,ba){ja.key===w&&ea.Gb.splice(ba,1)})};aa.prototype.length=function(){return this.Gb.length};
return aa}(),n={pages:[{name:"pages",type:"a"}],pdf:[{name:"url",type:"s"}],docmod:[{name:"url",type:"s"},{name:"rID",type:"s"}],health:[],tiles:[{name:"z",type:"n"},{name:"rID",type:"n"},{name:"tiles",type:"a"},{name:"size",type:"n"}],cAnnots:[{name:"annots",type:"a"}],annots:[{name:"url",type:"s"},{name:"name",type:"s"}],image:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],text:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],ApString2Xod:[{name:"url",type:"s"},
{name:"rID",type:"s"}]};r=function(){function aa(w,ea,ja){var ba=this;this.WM=this.oS=!1;this.eh=this.rF=this.su=this.SK=this.yH=this.Fm=null;this.fm=new a;this.zp=new a;this.tB=!1;this.vf=this.Ae=this.Be=this.mf=null;this.Kf=[];this.fC=[];this.cache={};this.timeStamp=0;this.Zg=[];this.cj=[];this.BI=null;this.bS=!1;this.HY=this.id=null;this.FK=this.FU=pa;this.ai=0;this.LJ=!1;this.jW=1;this.Yi={};this.Nr=0;this.Kt=new h;ea.endsWith("/")||(ea+="/");ja=ja||{};this.oS=ja.disableWebsockets||!1;this.WM=
ja.singleServerMode||!1;null!=ja.customQueryParameters&&Object(e.b)("wvsQueryParameters",ja.customQueryParameters);ea.endsWith("blackbox/")||(ea+="blackbox/");this.Fm=ja.uploadData||null;this.su=ja.uriData||null;this.yH=ja.cacheKey||null;this.SK=ja.officeOptions||null;this.Se=ea;this.dI=w;this.yo(!0);this.cs=(new x.a(ea,null,this.Mh())).naa(!this.oS,function(ca){ba.Qfa(ca)},function(){return null},function(){ba.tB=!1},function(){ba.Tia()})}aa.prototype.W7=function(){var w=this;return new Promise(function(ea,
ja){var ba=new XMLHttpRequest;ba.open("GET",w.Se+"ck");ba.withCredentials=w.Mh();ba.onreadystatechange=function(){ba.readyState===XMLHttpRequest.DONE&&(200===ba.status?ea():ja())};ba.send()})};aa.prototype.uka=function(w){this.FU=w||pa;this.FK=pa};aa.prototype.E6=function(){this.kY();return this.cs.Kp(!0)};aa.prototype.kY=function(){Object(ma.b)(this,void 0,void 0,function(){return Object(ma.d)(this,function(w){switch(w.label){case 0:return this.zp=new a,this.fm=new a,this.tB=!1,this.id=null,this.bS=
!1,[4,this.W7()];case 1:return w.ea(),[2]}})})};aa.prototype.Tia=function(){this.FU();this.kY();this.mf&&(this.mf.Si()?this.lh(this.mf.request):this.mf.it()&&this.FK(this.mf.result.url,"pdf")&&(this.mf=null,this.jY()));this.vf&&this.vf.Si()&&this.lh(this.vf.request);this.Be&&this.Be.Si()?this.lh(this.Be.request):this.Ae&&this.Ae.Si()&&this.sU();var w;for(w=0;w<this.Zg.length;w++)this.Zg[w]&&(this.Zg[w].Si()?this.lh(this.Zg[w].request):this.Zg[w].it()&&this.FK(this.Zg[w].result.url,"image")&&(this.Zg[w]=
null,this.rE(Object(fa.uniqueId)(),w)));for(w=0;w<this.cj.length;w++)this.cj[w]&&this.cj[w].Si()&&!this.cj[w].Zda()&&this.lh(this.cj[w].request);for(w=0;w<this.Kf.length;w++)this.Kf[w]&&this.Kf[w].Si()&&this.lh(this.Kf[w].request)};aa.prototype.Jda=function(){return this.tB?Promise.resolve():(this.tB=!0,this.timeStamp=Date.now(),this.cs.bD())};aa.prototype.Mma=function(){var w=this,ea,ja,ba,ca,ia;return new Promise(function(ha,la){if(w.Fm)ea=new FormData,ea.append("file",w.Fm.fileHandle,w.Fm.fileHandle.name),
ja=w.Fm.loadCallback,ca="upload",ba=w.Fm.extension;else if(w.su)ea={uri:w.su.uri,xqa:w.su.shareId},ea=Object.keys(ea).map(function(ra){return ra+"="+(ea[ra]?encodeURIComponent(ea[ra]):"")}).join("&"),ia="application/x-www-form-urlencoded; charset=UTF-8",ja=w.su.loadCallback,ca="url",ba=w.su.extension;else{ha();return}var na=new XMLHttpRequest,qa=Object(z.j)(w.Se,"AuxUpload");qa=Object(b.a)(qa,{type:ca,ext:ba});na.open("POST",qa);na.withCredentials=w.Mh();ia&&na.setRequestHeader("Content-Type",ia);
na.addEventListener("load",function(){if(na.readyState===na.DONE&&200===na.status){var ra=JSON.parse(na.response);w.dI=ra.uri;ja(ra);ha(ra)}});na.addEventListener("error",function(){la(na.statusText+" "+JSON.stringify(na))});w.Fm&&null!=w.Fm.onProgress&&(na.upload.onprogress=function(ra){w.Fm.onProgress(ra)});na.send(ea)})};aa.prototype.Kia=function(w){this.password=w||null;this.fm.it()||(this.fm=new a,this.lh({t:"pages"}));return this.fm.promise};aa.prototype.ay=function(w){this.BI=w||null;this.fm.it()||
this.lh({t:"pages"});return this.fm.promise};aa.prototype.Nv=function(w){w=Object.assign(w,{uri:encodeURIComponent(this.dI)});this.BI&&(w.ext=this.BI);this.eh&&(w.c=this.eh);this.password&&(w.pswd=this.password);this.yH&&(w.cacheKey=this.yH);this.SK&&(w.officeOptions=this.SK);return w};aa.prototype.qja=function(){0<this.Kt.length()&&10>=this.Nr&&this.rja(this.Kt.pop().data)};aa.prototype.f6=function(w){0<this.Kt.length()&&this.Kt.contains(w)&&this.Kt.remove(w)};aa.prototype.lh=function(w){w=this.Nv(w);
this.cs.send(w)};aa.prototype.CY=function(w,ea){10<this.Nr?this.Kt.push(w,ea):(this.Nr++,w=this.Nv(ea),this.cs.send(w))};aa.prototype.rja=function(w){this.Nr++;w=this.Nv(w);this.cs.send(w)};aa.prototype.ll=function(w){return w};aa.prototype.EU=function(w){this.WM&&w?Object(da.j)("Server failed health check. Single server mode ignoring check."):!this.apa&&w&&3>=this.ai?(this.LJ=!0,this.cs.Kp()):3<this.ai&&(this.WM=!0)};aa.prototype.Qfa=function(w){var ea=this,ja=w.data,ba=w.err,ca=w.t;switch(ca){case "upload":ba?
this.Nma.reject(ba):this.Nma.resolve("Success");break;case "pages":ba?this.fm.reject(ba):ka(ja,ca,this.fm)&&this.fm.resolve(ja);break;case "config":if(ba)this.zp.reject(ba);else if(ka(ja,ca,this.zp)){this.EU(ja.unhealthy);ja.id&&(this.id=ja.id);if(ja.auth){var ia=Object(e.a)("wvsQueryParameters");ia.auth=ja.auth;Object(e.b)("wvsQueryParameters",ia)}ja.serverVersion&&(this.rF=ja.serverVersion,Object(da.h)("[WebViewer Server] server version: "+this.rF));ja.serverID?(this.ai=ja.serverID===this.HY&&this.LJ?
this.ai+1:0,this.HY=ja.serverID):this.ai=0;this.LJ=!1;this.zp.resolve(ja)}break;case "health":ba?this.zp.reject(ba):ka(ja,ca,this.zp)&&this.EU(ja.unhealthy);break;case "pdf":ja.url=Object(b.a)(this.Se+"../"+encodeURI(ja.url));ba?this.mf.reject(ba):ka(ja,ca,this.mf)&&this.mf.resolve(ja);break;case "ApString2Xod":ja.url=Object(b.a)(this.Se+"../data/"+encodeURI(ja.url));ba?this.Yi[ja.rID].reject(ba):ka(ja,ca,this.Yi[ja.rID])&&this.Yi[ja.rID].resolve(ja);break;case "docmod":ja.url=Object(b.a)(this.Se+
"../"+encodeURI(ja.url));ba?this.Yi[ja.rID].reject(ba):ka(ja,ca,this.mf)&&this.Yi[ja.rID].resolve(ja);break;case "xod":if(ba)this.Be&&this.Be.Si()&&this.Be.reject(ba),this.Ae&&this.Ae.Si()&&this.Ae.reject(ba);else if(ja.notFound)ja.noCreate||this.Be&&this.Be.Si()&&this.Be.resolve(ja),this.Ae&&this.Ae.Si()&&this.Ae.resolve(ja);else{ja.url&&(ja.url=Object(b.a)(this.Se+"../"+encodeURI(ja.url)));if(!this.Ae||this.Ae.it())this.Ae=new a,this.Ae.request={t:"xod",noCreate:!0};this.Be||(this.Be=new a,this.Be.request=
{t:"xod"});this.Ae.resolve(ja);this.Be.resolve(ja)}break;case "cAnnots":ia=this.vf;if(ba)ia.reject(ba);else if(ka(ja,ca,ia)){ia.rM();var ha=[],la=ja.annots;ja=function(oa){var wa=la[oa].s,Da=la[oa].e,Ha=na.Se+"../"+encodeURI(la[oa].xfdf),La="true"===la[oa].hasAppearance?Object(b.a)(Ha+".xodapp"):null,Ca=Object(fa.range)(wa,Da+1);ha[oa]={range:Ca,promise:new Promise(function(Ka,Ra){var Ma=new XMLHttpRequest;Ma.open("GET",Object(b.a)(Ha));Ma.responseType="text";Ma.withCredentials=ea.Mh();Ma.addEventListener("load",
function(){Ma.readyState===Ma.DONE&&200===Ma.status&&Ka({gr:Ma.response,al:La,range:Ca})});Ma.addEventListener("error",function(){Ra(Ma.statusText+" "+JSON.stringify(Ma))});Ma.send()})}};var na=this;for(ba=0;ba<la.length;ba++)ja(ba);ia.resolve(ha)}break;case "annots":if(ba)this.vf.reject(ba);else if(ka(ja,ca,this.vf)){this.vf.rM();var qa=new XMLHttpRequest;ia=this.Se+"../"+encodeURI(ja.url);var ra=ja.hasAppearance?Object(b.a)(ia+".xodapp"):null;qa.open("GET",Object(b.a)(ia));qa.responseType="text";
qa.withCredentials=this.Mh();qa.addEventListener("load",function(){qa.readyState===qa.DONE&&200===qa.status&&ea.vf.resolve({gr:qa.response,al:ra})});qa.addEventListener("error",function(){ea.vf.reject(qa.statusText+" "+JSON.stringify(qa))});qa.send()}break;case "image":this.Nr--;var ta=this.Zg[ja.p];ba?ta.promise.reject(ba):ka(ja,ca,ta)&&(ta.result=ja,ta.result.url=Object(b.a)(this.Se+"../"+encodeURI(ta.result.url)),ta.resolve(ta.result));break;case "tiles":this.Nr--;ta=ja.rID;ia=this.Kf[ta];this.Kf[ta]=
null;this.fC.push(ta);if(ba)ia.reject(ba);else if(ka(ja,ca,ia)){for(ba=0;ba<ja.tiles.length;ba++)ja.tiles[ba]=Object(b.a)(this.Se+"../"+encodeURI(ja.tiles[ba]));ia.resolve(ja)}break;case "text":ta=this.cj[ja.p];if(ba)ta.reject(ba);else if(ka(ja,ca,ta)){ta.rM();var va=new XMLHttpRequest;ja=Object(b.a)(this.Se+"../"+encodeURI(ja.url));va.open("GET",ja);va.withCredentials=this.Mh();va.addEventListener("load",function(){va.readyState===va.DONE&&200===va.status&&(ta.result=JSON.parse(va.response),ta.resolve(ta.result))});
va.addEventListener("error",function(oa){ta.reject(va.statusText+" "+JSON.stringify(oa))});va.send()}break;case "progress":"loading"===ja.t&&this.trigger(y.a.Events.DOCUMENT_LOADING_PROGRESS,[ja.bytes,ja.total])}this.qja();!ca&&w.echo&&w&&"apstring2xod"===w.echo.t&&(w=w.echo.reqID)&&(2<=parseInt(this.rF,10)?this.Yi[w].reject("Message unhandled by server"):this.Yi[w].reject())};aa.prototype.Uaa=function(){return Object(ma.b)(this,void 0,void 0,function(){return Object(ma.d)(this,function(w){switch(w.label){case 0:return[4,
this.Jda()];case 1:return w.ea(),[2,this.zp.promise]}})})};aa.prototype.Caa=function(w){for(var ea=this,ja=new XMLHttpRequest,ba=Object(b.a)(this.Se+"aul",{id:this.id}),ca=new FormData,ia={},ha=0;ha<w.body.length;ha++){var la=w.body[ha];ia[la.id]=la.lH.w+";"+la.lH.h;ca.append(la.id,la.lH.dataString)}w={t:"apstring2xod",reqID:this.jW++,parts:ia};var na=this.Nv(w);ca.append("msg",JSON.stringify(na));this.Yi[na.reqID]=new a;ja.open("POST",ba);ja.withCredentials=this.Mh;ba=new Promise(function(qa,ra){ja.onreadystatechange=
function(){4===ja.readyState&&(200===ja.status?qa():ra("An error occurred while sending down appearance strings to the server"))}});ja.send(ca);return ba.then(function(){return ea.Yi[na.reqID].promise})};aa.prototype.G6=function(){var w=this.rF.split("-")[0].split("."),ea=["1","5","9"];if(3!==w.length)throw Error("Invalid WVS version length.");if(3!==ea.length)throw Error("Invalid version length.");for(var ja=0;ja<w.length;++ja){if(ea.length===ja||w[ja]>ea[ja])return-1;if(w[ja]!==ea[ja])return 1}return 0};
aa.prototype.vp=function(){return 0>=this.G6()};aa.prototype.KI=function(){this.vf||(this.vf=new a,this.vp()?this.vf.request={t:"cAnnots"}:this.vf.request={t:"annots"},this.lh(this.vf.request));return this.vf.promise};aa.prototype.rE=function(w,ea){this.Zg[ea]||(this.Zg[ea]=new a,this.Zg[ea].request={t:"image",p:ea},this.CY(w,this.Zg[ea].request));return this.Zg[ea].promise};aa.prototype.Lia=function(w){this.cj[w]||(this.cj[w]=new a,this.cj[w].request={t:"text",p:w},this.lh(this.cj[w].request));return this.cj[w].promise};
aa.prototype.Mia=function(w,ea,ja,ba,ca){var ia=this.Kf.length;this.fC.length&&(ia=this.fC.pop());this.Kf[ia]=new a;this.Kf[ia].request={t:"tiles",p:ea,z:ja,r:ba,size:ca,rID:ia};this.CY(w,this.Kf[ia].request);return this.Kf[ia].promise};aa.prototype.jY=function(){this.mf||(this.mf=new a,this.mf.request={t:"pdf"},this.bS?this.mf.resolve({url:this.dI}):this.lh(this.mf.request));return this.mf.promise};aa.prototype.QT=function(w){var ea=this,ja=new XMLHttpRequest,ba=Object(b.a)(this.Se+"aul",{id:this.id}),
ca=new FormData,ia={};w.annots&&(ia.annots="xfdf");w.watermark&&(ia.watermark="png");w.redactions&&(ia.redactions="redact");ia={t:"docmod",reqID:this.jW++,parts:ia};w.print&&(ia.print=!0);var ha=this.Nv(ia);ca.append("msg",JSON.stringify(ha));return Promise.all([w.annots,w.watermark,w.redactions].map(function(la){return Promise.resolve(la)})).then(function(la){var na=la[0],qa=la[1];la=la[2];na&&ca.append("annots",na);qa&&ca.append("watermark",qa);la&&ca.append("redactions",la);ea.Yi[ha.reqID]=new a;
ja.open("POST",ba);ja.withCredentials=ea.Mh;na=new Promise(function(ra,ta){ja.onreadystatechange=function(){4===ja.readyState&&(200===ja.status?ra():ta("An error occurred while sending down annotation data to the server"))}});ja.send(ca);return na.then(function(){return ea.Yi[ha.reqID].promise})})};aa.prototype.sU=function(){this.Ae||(this.Ae=new a,this.Ae.request={t:"xod",noCreate:!0},this.lh(this.Ae.request));return this.Ae.promise};aa.prototype.Nia=function(){this.Be||(this.Be=new a,this.Be.request=
{t:"xod"},this.lh(this.Be.request));return this.Be.promise};aa.prototype.qo=function(){return!0};aa.prototype.request=function(){};aa.prototype.DX=function(){};aa.prototype.abort=function(){for(var w=0;w<this.Kf.length;w++)this.Kf[w]&&(this.Kf[w].resolve(null),this.Kf[w]=null,this.fC.push(w));this.close()};aa.prototype.DE=function(w){this.eh=this.eh||{};this.eh.headers=w};aa.prototype.yo=function(w){this.eh=this.eh||{};this.eh.internal=this.eh.internal||{};this.eh.internal.withCredentials=w};aa.prototype.Mh=
function(){return this.eh&&this.eh.internal?this.eh.internal.withCredentials:null};aa.prototype.getFileData=function(){return Promise.reject()};return aa}();Object(Ba.a)(r);Object(f.a)(r);Object(f.b)(r);ua["default"]=r},461:function(Ba,ua,r){var pa=r(1),ka=r(2),ma=r(34),fa=r(40),da=r(166),z=r(112),x=function(){function f(e,b,a,h,n,aa){void 0===a&&(a=null);void 0===h&&(h=null);void 0===n&&(n=null);void 0===aa&&(aa=null);this.RV=!1;this.ai=0;this.fR=this.hna(e);this.url=b?this.fR+"/"+b:this.fR+"/ws";
this.XH=a;this.Fx=h;this.Lv=n;this.XL=aa}f.prototype.hna=function(e){var b=e.indexOf("://"),a="ws://";0>b?b=0:(5===b&&(a="wss://"),b+=3);var h=e.lastIndexOf("/");0>h&&(h=e.length);return a+e.slice(b,h)};f.prototype.send=function(e){this.Ko.readyState===WebSocket.CLOSED||this.RV||this.Ko.send(JSON.stringify(e))};f.prototype.bD=function(){return Object(pa.b)(this,void 0,void 0,function(){var e,b=this;return Object(pa.d)(this,function(){e=Object(fa.a)("wvsQueryParameters");e.bcid=Object(ma.k)(8);Object(fa.b)("wvsQueryParameters",
e);return[2,new Promise(function(a,h){var n=Object(da.a)(b.url);b.Ko=new WebSocket(n);b.Ko.onopen=function(){b.Fx&&b.Fx();a()};b.Ko.onerror=function(aa){b.RV=!0;h(aa)};b.Ko.onclose=function(aa){var w=aa.code;return Object(pa.b)(b,void 0,void 0,function(){var ea=this;return Object(pa.d)(this,function(ja){switch(ja.label){case 0:return this.Lv&&this.Lv(),3E3===w?[3,3]:8>this.ai++?[4,new Promise(function(ba){return setTimeout(function(){return Object(pa.b)(ea,void 0,void 0,function(){return Object(pa.d)(this,
function(ca){switch(ca.label){case 0:return this.XL(),[4,this.bD()];case 1:return ca.ea(),ba(),[2]}})})},3E3)})]:[3,2];case 1:return ja.ea(),[3,3];case 2:h(z.a),ja.label=3;case 3:return[2]}})})};b.Ko.onmessage=function(aa){aa&&aa.data&&(aa=JSON.parse(aa.data),aa.hb?b.send({hb:!0}):aa.end?close():b.XH(aa))}})]})})};f.prototype.Kp=function(e){void 0===e&&(e=!1);this.ai=0;e?this.Ko.close(3E3):this.Ko.close();return Promise.resolve()};return f}(),y=function(){function f(e,b,a,h,n,aa,w){void 0===h&&(h=
null);void 0===n&&(n=null);void 0===aa&&(aa=null);void 0===w&&(w=null);this.ai=this.qE=this.id=0;this.Sw=!1;this.request=null;e=this.kha(e);this.url=b?e+"/"+b+"pf":e+"/pf";this.kF=a;this.XH=h;this.Fx=n;this.Lv=aa;this.XL=w}f.prototype.kha=function(e){var b=e.lastIndexOf("/");0>b&&(b=e.length);return e.slice(0,b)};f.prototype.F7=function(e){e=e.split("\n");for(e[e.length-1]&&e.pop();0<e.length&&3>e[e.length-1].length;)"]"===e.pop()&&(this.id=0);0<e.length&&3>e[0].length&&e.shift();for(var b=0;b<e.length;++b)e[b].endsWith(",")&&
(e[b]=e[b].substr(0,e[b].length-1));return e};f.prototype.tY=function(){return Object(pa.b)(this,void 0,void 0,function(){var e=this;return Object(pa.d)(this,function(b){switch(b.label){case 0:return 8>this.ai++?[4,new Promise(function(a){return setTimeout(function(){e.XL();e.bD();a()},3E3)})]:[3,2];case 1:b.ea(),b.label=2;case 2:return[2]}})})};f.prototype.mha=function(e){Object(pa.b)(this,void 0,void 0,function(){var b,a;return Object(pa.d)(this,function(h){switch(h.label){case 0:b=null,a=0,h.label=
1;case 1:if(!(a<e.length))return[3,6];b=JSON.parse(e[a]);if(!b)return[3,5];if(!b.end)return[3,2];close();return[3,5];case 2:if(!b.id||Number(b.id)===this.id)return[3,4];Object(ka.j)("Reconnecting, new server detected");this.Kp();return[4,this.tY()];case 3:return h.ea(),[3,5];case 4:b.hb&&Number(b.id)===this.id?this.send({hb:!0}):this.Sw||this.XH(b),h.label=5;case 5:return++a,[3,1];case 6:return[2]}})})};f.prototype.Nfa=function(e){Object(pa.b)(this,void 0,void 0,function(){var b,a,h;return Object(pa.d)(this,
function(n){switch(n.label){case 0:if(!(3<=e.readyState))return[3,2];try{b=e.responseText.length}catch(aa){return Object(ka.h)("caught exception"),[2]}if(0<b)try{a=this.F7(e.responseText),0===this.id&&0<a.length&&(h=JSON.parse(a.shift()),this.id=h.id,this.ai=0),this.mha(a)}catch(aa){}return this.Sw?[3,2]:[4,this.SS()];case 1:n.ea(),n.label=2;case 2:return[2]}})})};f.prototype.SS=function(){return Object(pa.b)(this,void 0,void 0,function(){var e=this;return Object(pa.d)(this,function(){return[2,new Promise(function(b,
a){function h(){return Object(pa.b)(e,void 0,void 0,function(){return Object(pa.d)(this,function(aa){switch(aa.label){case 0:a(),this.Kp(),aa.label=1;case 1:return this.Sw&&8>this.ai?[4,this.tY()]:[3,3];case 2:return aa.ea(),[3,1];case 3:return[2]}})})}e.request=new XMLHttpRequest;e.request.withCredentials=e.kF;var n=Object(da.a)(e.url,0!==e.id?{id:String(e.id),uc:String(e.qE)}:{uc:String(e.qE)});e.qE++;e.request.open("GET",n,!0);e.request.setRequestHeader("Cache-Control","no-cache");e.request.setRequestHeader("X-Requested-With",
"XMLHttpRequest");e.request.onreadystatechange=function(){e.Nfa(e.request)};e.request.addEventListener("error",h);e.request.addEventListener("timeout",h);e.request.addEventListener("load",function(){e.Fx&&e.Fx();b()});e.request.send()})]})})};f.prototype.bD=function(){var e=Object(fa.a)("wvsQueryParameters");e.bcid=Object(ma.k)(8);Object(fa.b)("wvsQueryParameters",e);this.qE=this.id=0;this.Sw=!1;return this.SS()};f.prototype.send=function(e){var b=this,a=new XMLHttpRequest;a.withCredentials=this.kF;
var h=Object(da.a)(this.url,{id:String(this.id)}),n=new FormData;n.append("data",JSON.stringify(e));a.addEventListener("error",function(){b.Kp()});a.open("POST",h);a.setRequestHeader("X-Requested-With","XMLHttpRequest");a.send(n)};f.prototype.Kp=function(){this.id=0;this.Sw=!0;this.Lv&&this.Lv();this.request.abort();return Promise.resolve()};return f}();Ba=function(){function f(e,b,a){this.ER=e;this.target=b;this.kF=a}f.prototype.naa=function(e,b,a,h,n){void 0===e&&(e=!0);void 0===b&&(b=null);void 0===
a&&(a=null);void 0===h&&(h=null);void 0===n&&(n=null);return e?new x(this.ER,this.target,b,a,h,n):new y(this.ER,this.target,this.kF,b,a,h,n)};return f}();ua.a=Ba}}]);}).call(this || window)
=======
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[14],{467:function(Ba,wa,r){function oa(){return!1}function na(z,x,ea){if(!(x in n))return!0;x=n[x];for(var ja=0;ja<x.length;ja++){var ca=z;var ba=x[ja];var ha=ea;if(ba.name in ca){var ia="",la=!1;ca=ca[ba.name];switch(ba.type){case "s":ia="String";la=Object(fa.isString)(ca);break;case "a":ia="Array";la=Object(fa.isArray)(ca);break;case "n":ia="Number";la=Object(fa.isNumber)(ca)&&Object(fa.isFinite)(ca);break;case "o":ia="Object",
la=Object(fa.isObject)(ca)&&!Object(fa.isArray)(ca)}la||ha.reject('Expected response field "'+ba.name+'" to have type '+ia);ba=la}else ha.reject('Response missing field "'+ba.name+'"'),ba=!1;if(!ba)return!1}return!0}r.r(wa);var ma=r(0),fa=r(1);r.n(fa);var da=r(2);Ba=r(48);var aa=r(23),w=r(484),y=r(100),h=r(393),a=r(43),b=r(177),e=function(){function z(){this.request=this.result=null;this.state=0;var x=this;x.promise=new Promise(function(ea,ja){x.resolve=function(){if(0===x.state||4===x.state)x.state=
1,x.result=arguments[0],ea.apply(null,arguments)};x.reject=function(){if(0===x.state||4===x.state)x.state=2,ja.apply(null,arguments)}})}z.prototype.Qt=function(){return 1===(this.state&1)};z.prototype.jha=function(){return 2===(this.state&2)};z.prototype.bj=function(){return!this.jha()&&!this.Qt()};z.prototype.Kga=function(){return 4===(this.state&4)};z.prototype.CN=function(){this.state|=4};return z}(),f=function(){function z(){this.yt={};this.Mb=[]}z.prototype.pop=function(){var x=this.Mb.pop();
this.yt[x.key]=void 0;return x};z.prototype.push=function(x,ea){ea={key:x,data:ea};this.Mb.push(ea);this.yt[x]=ea.data};z.prototype.contains=function(x){return!!this.yt[x]};z.prototype.get=function(x){return this.yt[x]};z.prototype.set=function(x,ea){var ja=this;this.yt[x]=ea;this.Mb.forEach(function(ca,ba){ca.key===x&&(ja.Mb[ba]=ca)})};z.prototype.remove=function(x){var ea=this;this.yt[x]=void 0;this.Mb.forEach(function(ja,ca){ja.key===x&&ea.Mb.splice(ca,1)})};z.prototype.length=function(){return this.Mb.length};
return z}(),n={pages:[{name:"pages",type:"a"}],pdf:[{name:"url",type:"s"}],docmod:[{name:"url",type:"s"},{name:"rID",type:"s"}],health:[],tiles:[{name:"z",type:"n"},{name:"rID",type:"n"},{name:"tiles",type:"a"},{name:"size",type:"n"}],cAnnots:[{name:"annots",type:"a"}],annots:[{name:"url",type:"s"},{name:"name",type:"s"}],image:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],text:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],ApString2Xod:[{name:"url",type:"s"},
{name:"rID",type:"s"}]};r=function(){function z(x,ea,ja){var ca=this;this.jO=this.bU=!1;this.uh=this.jG=this.$u=this.aM=this.zI=this.bn=null;this.Hm=new e;this.Tp=new e;this.eC=!1;this.Gf=this.He=this.Ie=this.yf=null;this.dg=[];this.QC=[];this.cache={};this.timeStamp=0;this.ph=[];this.lj=[];this.FJ=null;this.OT=!1;this.E_=this.id=null;this.ML=this.vW=oa;this.li=0;this.NK=!1;this.fY=1;this.hj={};this.qs=0;this.qu=new f;ea.endsWith("/")||(ea+="/");ja=ja||{};this.bU=ja.disableWebsockets||!1;this.jO=
ja.singleServerMode||!1;null!=ja.customQueryParameters&&Object(a.b)("wvsQueryParameters",ja.customQueryParameters);ea.endsWith("blackbox/")||(ea+="blackbox/");this.bn=ja.uploadData||null;this.$u=ja.uriData||null;this.zI=ja.cacheKey||null;this.aM=ja.officeOptions||null;this.af=ea;this.hJ=x;this.So(!0);this.Hs=(new w.a(ea,null,this.Yh())).Rca(!this.bU,function(ba){ca.Cia(ba)},function(){return null},function(){ca.eC=!1},function(){ca.Ila()})}z.prototype.w$=function(){var x=this;return new Promise(function(ea,
ja){var ca=new XMLHttpRequest;ca.open("GET",x.af+"ck");ca.withCredentials=x.Yh();ca.onreadystatechange=function(){ca.readyState===XMLHttpRequest.DONE&&(200===ca.status?ea():ja())};ca.send()})};z.prototype.zna=function(x){this.vW=x||oa;this.ML=oa};z.prototype.e9=function(){this.h_();return this.Hs.hq(!0)};z.prototype.h_=function(){Object(ma.b)(this,void 0,void 0,function(){return Object(ma.d)(this,function(x){switch(x.label){case 0:return this.Tp=new e,this.Hm=new e,this.eC=!1,this.id=null,this.OT=
!1,[4,this.w$()];case 1:return x.ca(),[2]}})})};z.prototype.Ila=function(){this.vW();this.h_();this.yf&&(this.yf.bj()?this.Bh(this.yf.request):this.yf.Qt()&&this.ML(this.yf.result.url,"pdf")&&(this.yf=null,this.g_()));this.Gf&&this.Gf.bj()&&this.Bh(this.Gf.request);this.Ie&&this.Ie.bj()?this.Bh(this.Ie.request):this.He&&this.He.bj()&&this.iW();var x;for(x=0;x<this.ph.length;x++)this.ph[x]&&(this.ph[x].bj()?this.Bh(this.ph[x].request):this.ph[x].Qt()&&this.ML(this.ph[x].result.url,"image")&&(this.ph[x]=
null,this.iF(Object(fa.uniqueId)(),x)));for(x=0;x<this.lj.length;x++)this.lj[x]&&this.lj[x].bj()&&!this.lj[x].Kga()&&this.Bh(this.lj[x].request);for(x=0;x<this.dg.length;x++)this.dg[x]&&this.dg[x].bj()&&this.Bh(this.dg[x].request)};z.prototype.sga=function(){return this.eC?Promise.resolve():(this.eC=!0,this.timeStamp=Date.now(),this.Hs.OD())};z.prototype.aqa=function(){var x=this,ea,ja,ca,ba,ha;return new Promise(function(ia,la){if(x.bn)ea=new FormData,ea.append("file",x.bn.fileHandle,x.bn.fileHandle.name),
ja=x.bn.loadCallback,ba="upload",ca=x.bn.extension;else if(x.$u)ea={uri:x.$u.uri,Rta:x.$u.shareId},ea=Object.keys(ea).map(function(pa){return pa+"="+(ea[pa]?encodeURIComponent(ea[pa]):"")}).join("&"),ha="application/x-www-form-urlencoded; charset=UTF-8",ja=x.$u.loadCallback,ba="url",ca=x.$u.extension;else{ia();return}var ka=new XMLHttpRequest,qa=Object(aa.k)(x.af,"AuxUpload");qa=Object(b.a)(qa,{type:ba,ext:ca});ka.open("POST",qa);ka.withCredentials=x.Yh();ha&&ka.setRequestHeader("Content-Type",ha);
ka.addEventListener("load",function(){if(ka.readyState===ka.DONE&&200===ka.status){var pa=JSON.parse(ka.response);x.hJ=pa.uri;ja(pa);ia(pa)}});ka.addEventListener("error",function(){la(ka.statusText+" "+JSON.stringify(ka))});x.bn&&null!=x.bn.onProgress&&(ka.upload.onprogress=function(pa){x.bn.onProgress(pa)});ka.send(ea)})};z.prototype.zla=function(x){this.password=x||null;this.Hm.Qt()||(this.Hm=new e,this.Bh({t:"pages"}));return this.Hm.promise};z.prototype.Qy=function(x){this.FJ=x||null;this.Hm.Qt()||
this.Bh({t:"pages"});return this.Hm.promise};z.prototype.tw=function(x){x=Object.assign(x,{uri:encodeURIComponent(this.hJ)});this.FJ&&(x.ext=this.FJ);this.uh&&(x.c=this.uh);this.password&&(x.pswd=this.password);this.zI&&(x.cacheKey=this.zI);this.aM&&(x.officeOptions=this.aM);return x};z.prototype.hma=function(){0<this.qu.length()&&10>=this.qs&&this.ima(this.qu.pop().data)};z.prototype.B8=function(x){0<this.qu.length()&&this.qu.contains(x)&&this.qu.remove(x)};z.prototype.Bh=function(x){x=this.tw(x);
this.Hs.send(x)};z.prototype.z_=function(x,ea){10<this.qs?this.qu.push(x,ea):(this.qs++,x=this.tw(ea),this.Hs.send(x))};z.prototype.ima=function(x){this.qs++;x=this.tw(x);this.Hs.send(x)};z.prototype.Jl=function(x){return x};z.prototype.uW=function(x){this.jO&&x?Object(da.j)("Server failed health check. Single server mode ignoring check."):!this.rsa&&x&&3>=this.li?(this.NK=!0,this.Hs.hq()):3<this.li&&(this.jO=!0)};z.prototype.Cia=function(x){var ea=this,ja=x.data,ca=x.err,ba=x.t;switch(ba){case "upload":ca?
this.bqa.reject(ca):this.bqa.resolve("Success");break;case "pages":ca?this.Hm.reject(ca):na(ja,ba,this.Hm)&&this.Hm.resolve(ja);break;case "config":if(ca)this.Tp.reject(ca);else if(na(ja,ba,this.Tp)){this.uW(ja.unhealthy);ja.id&&(this.id=ja.id);if(ja.auth){var ha=Object(a.a)("wvsQueryParameters");ha.auth=ja.auth;Object(a.b)("wvsQueryParameters",ha)}ja.serverVersion&&(this.jG=ja.serverVersion,Object(da.h)("[WebViewer Server] server version: "+this.jG));ja.serverID?(this.li=ja.serverID===this.E_&&this.NK?
this.li+1:0,this.E_=ja.serverID):this.li=0;this.NK=!1;this.Tp.resolve(ja)}break;case "health":ca?this.Tp.reject(ca):na(ja,ba,this.Tp)&&this.uW(ja.unhealthy);break;case "pdf":ja.url=Object(b.a)(this.af+"../"+encodeURI(ja.url));ca?this.yf.reject(ca):na(ja,ba,this.yf)&&this.yf.resolve(ja);break;case "ApString2Xod":ja.url=Object(b.a)(this.af+"../data/"+encodeURI(ja.url));ca?this.hj[ja.rID].reject(ca):na(ja,ba,this.hj[ja.rID])&&this.hj[ja.rID].resolve(ja);break;case "docmod":ja.url=Object(b.a)(this.af+
"../"+encodeURI(ja.url));ca?this.hj[ja.rID].reject(ca):na(ja,ba,this.yf)&&this.hj[ja.rID].resolve(ja);break;case "xod":if(ca)this.Ie&&this.Ie.bj()&&this.Ie.reject(ca),this.He&&this.He.bj()&&this.He.reject(ca);else if(ja.notFound)ja.noCreate||this.Ie&&this.Ie.bj()&&this.Ie.resolve(ja),this.He&&this.He.bj()&&this.He.resolve(ja);else{ja.url&&(ja.url=Object(b.a)(this.af+"../"+encodeURI(ja.url)));if(!this.He||this.He.Qt())this.He=new e,this.He.request={t:"xod",noCreate:!0};this.Ie||(this.Ie=new e,this.Ie.request=
{t:"xod"});this.He.resolve(ja);this.Ie.resolve(ja)}break;case "cAnnots":ha=this.Gf;if(ca)ha.reject(ca);else if(na(ja,ba,ha)){ha.CN();var ia=[],la=ja.annots;ja=function(va){var sa=la[va].s,xa=la[va].e,Ea=ka.af+"../"+encodeURI(la[va].xfdf),Ha="true"===la[va].hasAppearance?Object(b.a)(Ea+".xodapp"):null,Aa=Object(fa.range)(sa,xa+1);ia[va]={range:Aa,promise:new Promise(function(Ja,La){var Oa=new XMLHttpRequest;Oa.open("GET",Object(b.a)(Ea));Oa.responseType="text";Oa.withCredentials=ea.Yh();Oa.addEventListener("load",
function(){Oa.readyState===Oa.DONE&&200===Oa.status&&Ja({Ar:Oa.response,xl:Ha,range:Aa})});Oa.addEventListener("error",function(){La(Oa.statusText+" "+JSON.stringify(Oa))});Oa.send()})}};var ka=this;for(ca=0;ca<la.length;ca++)ja(ca);ha.resolve(ia)}break;case "annots":if(ca)this.Gf.reject(ca);else if(na(ja,ba,this.Gf)){this.Gf.CN();var qa=new XMLHttpRequest;ha=this.af+"../"+encodeURI(ja.url);var pa=ja.hasAppearance?Object(b.a)(ha+".xodapp"):null;qa.open("GET",Object(b.a)(ha));qa.responseType="text";
qa.withCredentials=this.Yh();qa.addEventListener("load",function(){qa.readyState===qa.DONE&&200===qa.status&&ea.Gf.resolve({Ar:qa.response,xl:pa})});qa.addEventListener("error",function(){ea.Gf.reject(qa.statusText+" "+JSON.stringify(qa))});qa.send()}break;case "image":this.qs--;var ra=this.ph[ja.p];ca?ra.promise.reject(ca):na(ja,ba,ra)&&(ra.result=ja,ra.result.url=Object(b.a)(this.af+"../"+encodeURI(ra.result.url)),ra.resolve(ra.result));break;case "tiles":this.qs--;ra=ja.rID;ha=this.dg[ra];this.dg[ra]=
null;this.QC.push(ra);if(ca)ha.reject(ca);else if(na(ja,ba,ha)){for(ca=0;ca<ja.tiles.length;ca++)ja.tiles[ca]=Object(b.a)(this.af+"../"+encodeURI(ja.tiles[ca]));ha.resolve(ja)}break;case "text":ra=this.lj[ja.p];if(ca)ra.reject(ca);else if(na(ja,ba,ra)){ra.CN();var ua=new XMLHttpRequest;ja=Object(b.a)(this.af+"../"+encodeURI(ja.url));ua.open("GET",ja);ua.withCredentials=this.Yh();ua.addEventListener("load",function(){ua.readyState===ua.DONE&&200===ua.status&&(ra.result=JSON.parse(ua.response),ra.resolve(ra.result))});
ua.addEventListener("error",function(va){ra.reject(ua.statusText+" "+JSON.stringify(va))});ua.send()}break;case "progress":"loading"===ja.t&&this.trigger(y.a.Events.DOCUMENT_LOADING_PROGRESS,[ja.bytes,ja.total])}this.hma();!ba&&x.echo&&x&&"apstring2xod"===x.echo.t&&(x=x.echo.reqID)&&(2<=parseInt(this.jG,10)?this.hj[x].reject("Message unhandled by server"):this.hj[x].reject())};z.prototype.yda=function(){return Object(ma.b)(this,void 0,void 0,function(){return Object(ma.d)(this,function(x){switch(x.label){case 0:return[4,
this.sga()];case 1:return x.ca(),[2,this.Tp.promise]}})})};z.prototype.eda=function(x){for(var ea=this,ja=new XMLHttpRequest,ca=Object(b.a)(this.af+"aul",{id:this.id}),ba=new FormData,ha={},ia=0;ia<x.body.length;ia++){var la=x.body[ia];ha[la.id]=la.mI.w+";"+la.mI.h;ba.append(la.id,la.mI.dataString)}x={t:"apstring2xod",reqID:this.fY++,parts:ha};var ka=this.tw(x);ba.append("msg",JSON.stringify(ka));this.hj[ka.reqID]=new e;ja.open("POST",ca);ja.withCredentials=this.Yh;ca=new Promise(function(qa,pa){ja.onreadystatechange=
function(){4===ja.readyState&&(200===ja.status?qa():pa("An error occurred while sending down appearance strings to the server"))}});ja.send(ba);return ca.then(function(){return ea.hj[ka.reqID].promise})};z.prototype.g9=function(){var x=this.jG.split("-")[0].split("."),ea=["1","5","9"];if(3!==x.length)throw Error("Invalid WVS version length.");if(3!==ea.length)throw Error("Invalid version length.");for(var ja=0;ja<x.length;++ja){if(ea.length===ja||x[ja]>ea[ja])return-1;if(x[ja]!==ea[ja])return 1}return 0};
z.prototype.Pp=function(){return 0>=this.g9()};z.prototype.OJ=function(){this.Gf||(this.Gf=new e,this.Pp()?this.Gf.request={t:"cAnnots"}:this.Gf.request={t:"annots"},this.Bh(this.Gf.request));return this.Gf.promise};z.prototype.iF=function(x,ea){this.ph[ea]||(this.ph[ea]=new e,this.ph[ea].request={t:"image",p:ea},this.z_(x,this.ph[ea].request));return this.ph[ea].promise};z.prototype.Ala=function(x){this.lj[x]||(this.lj[x]=new e,this.lj[x].request={t:"text",p:x},this.Bh(this.lj[x].request));return this.lj[x].promise};
z.prototype.Bla=function(x,ea,ja,ca,ba){var ha=this.dg.length;this.QC.length&&(ha=this.QC.pop());this.dg[ha]=new e;this.dg[ha].request={t:"tiles",p:ea,z:ja,r:ca,size:ba,rID:ha};this.z_(x,this.dg[ha].request);return this.dg[ha].promise};z.prototype.g_=function(){this.yf||(this.yf=new e,this.yf.request={t:"pdf"},this.OT?this.yf.resolve({url:this.hJ}):this.Bh(this.yf.request));return this.yf.promise};z.prototype.CV=function(x){var ea=this,ja=new XMLHttpRequest,ca=Object(b.a)(this.af+"aul",{id:this.id}),
ba=new FormData,ha={};x.annots&&(ha.annots="xfdf");x.watermark&&(ha.watermark="png");x.redactions&&(ha.redactions="redact");ha={t:"docmod",reqID:this.fY++,parts:ha};x.print&&(ha.print=!0);var ia=this.tw(ha);ba.append("msg",JSON.stringify(ia));return Promise.all([x.annots,x.watermark,x.redactions].map(function(la){return Promise.resolve(la)})).then(function(la){var ka=la[0],qa=la[1];la=la[2];ka&&ba.append("annots",ka);qa&&ba.append("watermark",qa);la&&ba.append("redactions",la);ea.hj[ia.reqID]=new e;
ja.open("POST",ca);ja.withCredentials=ea.Yh;ka=new Promise(function(pa,ra){ja.onreadystatechange=function(){4===ja.readyState&&(200===ja.status?pa():ra("An error occurred while sending down annotation data to the server"))}});ja.send(ba);return ka.then(function(){return ea.hj[ia.reqID].promise})})};z.prototype.iW=function(){this.He||(this.He=new e,this.He.request={t:"xod",noCreate:!0},this.Bh(this.He.request));return this.He.promise};z.prototype.Cla=function(){this.Ie||(this.Ie=new e,this.Ie.request=
{t:"xod"},this.Bh(this.Ie.request));return this.Ie.promise};z.prototype.Mo=function(){return!0};z.prototype.request=function(){};z.prototype.AZ=function(){};z.prototype.abort=function(){for(var x=0;x<this.dg.length;x++)this.dg[x]&&(this.dg[x].resolve(null),this.dg[x]=null,this.QC.push(x));this.close()};z.prototype.wF=function(x){this.uh=this.uh||{};this.uh.headers=x};z.prototype.So=function(x){this.uh=this.uh||{};this.uh.internal=this.uh.internal||{};this.uh.internal.withCredentials=x};z.prototype.Yh=
function(){return this.uh&&this.uh.internal?this.uh.internal.withCredentials:null};z.prototype.getFileData=function(){return Promise.reject()};return z}();Object(Ba.a)(r);Object(h.a)(r);Object(h.b)(r);wa["default"]=r},484:function(Ba,wa,r){var oa=r(0),na=r(2),ma=r(23),fa=r(43),da=r(177),aa=r(77),w=function(){function h(a,b,e,f,n,z){void 0===e&&(e=null);void 0===f&&(f=null);void 0===n&&(n=null);void 0===z&&(z=null);this.NX=!1;this.li=0;this.IS=this.xqa(a);this.url=b?this.IS+"/"+b:this.IS+"/ws";this.ZI=
e;this.py=f;this.rw=n;this.fN=z}h.prototype.xqa=function(a){var b=a.indexOf("://"),e="ws://";0>b?b=0:(5===b&&(e="wss://"),b+=3);var f=a.lastIndexOf("/");0>f&&(f=a.length);return e+a.slice(b,f)};h.prototype.send=function(a){this.fp.readyState===WebSocket.CLOSED||this.NX||this.fp.send(JSON.stringify(a))};h.prototype.OD=function(){return Object(oa.b)(this,void 0,void 0,function(){var a,b=this;return Object(oa.d)(this,function(){a=Object(fa.a)("wvsQueryParameters");a.bcid=Object(ma.l)(8);Object(fa.b)("wvsQueryParameters",
a);return[2,new Promise(function(e,f){var n=Object(da.a)(b.url);b.fp=new WebSocket(n);b.fp.onopen=function(){b.py&&b.py();e()};b.fp.onerror=function(z){b.NX=!0;f(z)};b.fp.onclose=function(z){var x=z.code;return Object(oa.b)(b,void 0,void 0,function(){var ea=this;return Object(oa.d)(this,function(ja){switch(ja.label){case 0:return this.rw&&this.rw(),3E3===x?[3,3]:8>this.li++?[4,new Promise(function(ca){return setTimeout(function(){return Object(oa.b)(ea,void 0,void 0,function(){return Object(oa.d)(this,
function(ba){switch(ba.label){case 0:return this.fN(),[4,this.OD()];case 1:return ba.ca(),ca(),[2]}})})},3E3)})]:[3,2];case 1:return ja.ca(),[3,3];case 2:f(aa.a),ja.label=3;case 3:return[2]}})})};b.fp.onmessage=function(z){z&&z.data&&(z=JSON.parse(z.data),z.hb?b.send({hb:!0}):z.end?close():b.ZI(z))}})]})})};h.prototype.hq=function(a){void 0===a&&(a=!1);this.li=0;a?this.fp.close(3E3):this.fp.close();return Promise.resolve()};return h}(),y=function(){function h(a,b,e,f,n,z,x){void 0===f&&(f=null);void 0===
n&&(n=null);void 0===z&&(z=null);void 0===x&&(x=null);this.li=this.hF=this.id=0;this.Ex=!1;this.request=null;a=this.Zja(a);this.url=b?a+"/"+b+"pf":a+"/pf";this.cG=e;this.ZI=f;this.py=n;this.rw=z;this.fN=x}h.prototype.Zja=function(a){var b=a.lastIndexOf("/");0>b&&(b=a.length);return a.slice(0,b)};h.prototype.f$=function(a){a=a.split("\n");for(a[a.length-1]&&a.pop();0<a.length&&3>a[a.length-1].length;)"]"===a.pop()&&(this.id=0);0<a.length&&3>a[0].length&&a.shift();for(var b=0;b<a.length;++b)a[b].endsWith(",")&&
(a[b]=a[b].substr(0,a[b].length-1));return a};h.prototype.p_=function(){return Object(oa.b)(this,void 0,void 0,function(){var a=this;return Object(oa.d)(this,function(b){switch(b.label){case 0:return 8>this.li++?[4,new Promise(function(e){return setTimeout(function(){a.fN();a.OD();e()},3E3)})]:[3,2];case 1:b.ca(),b.label=2;case 2:return[2]}})})};h.prototype.aka=function(a){Object(oa.b)(this,void 0,void 0,function(){var b,e;return Object(oa.d)(this,function(f){switch(f.label){case 0:b=null,e=0,f.label=
1;case 1:if(!(e<a.length))return[3,6];b=JSON.parse(a[e]);if(!b)return[3,5];if(!b.end)return[3,2];close();return[3,5];case 2:if(!b.id||Number(b.id)===this.id)return[3,4];Object(na.j)("Reconnecting, new server detected");this.hq();return[4,this.p_()];case 3:return f.ca(),[3,5];case 4:b.hb&&Number(b.id)===this.id?this.send({hb:!0}):this.Ex||this.ZI(b),f.label=5;case 5:return++e,[3,1];case 6:return[2]}})})};h.prototype.zia=function(a){Object(oa.b)(this,void 0,void 0,function(){var b,e,f;return Object(oa.d)(this,
function(n){switch(n.label){case 0:if(!(3<=a.readyState))return[3,2];try{b=a.responseText.length}catch(z){return Object(na.h)("caught exception"),[2]}if(0<b)try{e=this.f$(a.responseText),0===this.id&&0<e.length&&(f=JSON.parse(e.shift()),this.id=f.id,this.li=0),this.aka(e)}catch(z){}return this.Ex?[3,2]:[4,this.FU()];case 1:n.ca(),n.label=2;case 2:return[2]}})})};h.prototype.FU=function(){return Object(oa.b)(this,void 0,void 0,function(){var a=this;return Object(oa.d)(this,function(){return[2,new Promise(function(b,
e){function f(){return Object(oa.b)(a,void 0,void 0,function(){return Object(oa.d)(this,function(z){switch(z.label){case 0:e(),this.hq(),z.label=1;case 1:return this.Ex&&8>this.li?[4,this.p_()]:[3,3];case 2:return z.ca(),[3,1];case 3:return[2]}})})}a.request=new XMLHttpRequest;a.request.withCredentials=a.cG;var n=Object(da.a)(a.url,0!==a.id?{id:String(a.id),uc:String(a.hF)}:{uc:String(a.hF)});a.hF++;a.request.open("GET",n,!0);a.request.setRequestHeader("Cache-Control","no-cache");a.request.setRequestHeader("X-Requested-With",
"XMLHttpRequest");a.request.onreadystatechange=function(){a.zia(a.request)};a.request.addEventListener("error",f);a.request.addEventListener("timeout",f);a.request.addEventListener("load",function(){a.py&&a.py();b()});a.request.send()})]})})};h.prototype.OD=function(){var a=Object(fa.a)("wvsQueryParameters");a.bcid=Object(ma.l)(8);Object(fa.b)("wvsQueryParameters",a);this.hF=this.id=0;this.Ex=!1;return this.FU()};h.prototype.send=function(a){var b=this,e=new XMLHttpRequest;e.withCredentials=this.cG;
var f=Object(da.a)(this.url,{id:String(this.id)}),n=new FormData;n.append("data",JSON.stringify(a));e.addEventListener("error",function(){b.hq()});e.open("POST",f);e.setRequestHeader("X-Requested-With","XMLHttpRequest");e.send(n)};h.prototype.hq=function(){this.id=0;this.Ex=!0;this.rw&&this.rw();this.request.abort();return Promise.resolve()};return h}();Ba=function(){function h(a,b,e){this.kT=a;this.target=b;this.cG=e}h.prototype.Rca=function(a,b,e,f,n){void 0===a&&(a=!0);void 0===b&&(b=null);void 0===
e&&(e=null);void 0===f&&(f=null);void 0===n&&(n=null);return a?new w(this.kT,this.target,b,e,f,n):new y(this.kT,this.target,this.cG,b,e,f,n)};return h}();wa.a=Ba}}]);}).call(this || window)
>>>>>>> 161efc3... Update lib to 8.10
