/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
<<<<<<< HEAD
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[17],{442:function(Ba,ua,r){r.r(ua);var pa=r(1),ka=r(245);Ba=r(432);var ma=r(94);r=r(374);var fa={},da=function(z){function x(y,f){var e=z.call(this,y,f)||this;e.url=y;e.range=f;e.status=ka.a.NOT_STARTED;return e}Object(pa.c)(x,z);x.prototype.start=function(y){var f=this;"undefined"===typeof fa[this.range.start]&&(fa[this.range.start]={bN:function(e){var b=atob(e),a,h=b.length;e=new Uint8Array(h);for(a=0;a<h;++a)e[a]=b.charCodeAt(a);
b=e.length;a="";for(var n=0;n<b;)h=e.subarray(n,n+1024),n+=1024,a+=String.fromCharCode.apply(null,h);f.bN(a,y)},kpa:function(){f.status=ka.a.ERROR;y({code:f.status})}},window.external.notify(this.url),this.status=ka.a.STARTED);f.BC()};return x}(Ba.ByteRangeRequest);Ba=function(z){function x(y,f,e,b){y=z.call(this,y,e,b)||this;y.Vx=da;return y}Object(pa.c)(x,z);x.prototype.Ov=function(y,f){return y+"?"+f.start+"&"+(f.stop?f.stop:"")};return x}(ma.a);Object(r.a)(Ba);Object(r.b)(Ba);ua["default"]=Ba}}]);}).call(this || window)
=======
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[15],{466:function(Ba,wa,r){r.r(wa);var oa=r(0),na=r(260);Ba=r(456);var ma=r(100);r=r(393);var fa={},da=function(aa){function w(y,h){var a=aa.call(this,y,h)||this;a.url=y;a.range=h;a.status=na.a.NOT_STARTED;return a}Object(oa.c)(w,aa);w.prototype.start=function(y){var h=this;"undefined"===typeof fa[this.range.start]&&(fa[this.range.start]={pO:function(a){var b=atob(a),e,f=b.length;a=new Uint8Array(f);for(e=0;e<f;++e)a[e]=b.charCodeAt(e);
b=a.length;e="";for(var n=0;n<b;)f=a.subarray(n,n+1024),n+=1024,e+=String.fromCharCode.apply(null,f);h.pO(e,y)},Bsa:function(){h.status=na.a.ERROR;y({code:h.status})}},window.external.notify(this.url),this.status=na.a.STARTED);h.nD()};return w}(Ba.ByteRangeRequest);Ba=function(aa){function w(y,h,a,b){y=aa.call(this,y,a,b)||this;y.Ky=da;return y}Object(oa.c)(w,aa);w.prototype.uw=function(y,h){return y+"?"+h.start+"&"+(h.stop?h.stop:"")};return w}(ma.a);Object(r.a)(Ba);Object(r.b)(Ba);wa["default"]=
Ba}}]);}).call(this || window)
>>>>>>> 161efc3... Update lib to 8.10
